#---------- CoD HUD Settings | Svenska | Swedish (CUSTOM)
# Translator: Moka

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD-Gränssnitt

CoDHUD.Client=Klient
CoDHUD.Server=Server
CoDHUD.General=Generell

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Påbörja runda

CoDHUD.RoundStart.Gamemode=Välj spelläge
CoDHUD.RoundStart.Start=Aktivera 'påbörja runda'-processen
CoDHUD.RoundStart.Info=Välj ett spelläge, och tryck sedan på knappen nedanför.

CoDHUD.RoundStart.Notice=Är du säker på att du vill påbörja en ny runda?\nAlla poäng kommer nollställas och alla spelare kommer återuppstå.
CoDHUD.RoundStart.Yes=Påbörja runda
CoDHUD.RoundStart.No=Avbryt

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Aktivera "matchavslut"
CoDHUD.Admin.EndScreen.desc=Aktiverar ett "matchavslut"-system när poängbegränsningen är nådd.

CoDHUD.Admin.EndScreen.StartNext=Påbörja ny runda efter matchavslut
CoDHUD.Admin.EndScreen.StartNext.desc=Om påslaget så kommer en ny runda påbörja efter matchen avslutas.\nOm avaktiverat så kommer alla spelare återuppstå normalt.

CoDHUD.Admin.EndScreen.Scorelimit=Poängbegränsning
CoDHUD.Admin.EndScreen.Scorelimit.desc=Sätter högsta poängbegränsningen som visas på poängräknaren.\nMäts i dråp.

CoDHUD.Admin.FriendlyFire=Tillåt vådaskott
CoDHUD.Admin.FriendlyFire.desc=Om påslaget så kan spelare på samma team skada varandra.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Begränsa team och typ av gränssnitt
CoDHUD.Admin.RestrictType.desc=Välj vilken CoD-typ du vill begränsa spelare till. Ändrande av värdet kommer slumpmässigt ändra allas nuvarande team.\n\nDetta påverkar alla spelares:\n- Val av team \n- CoD-Gränssnittmenyns bakgrund och ljudeffekter

CoDHUD.Type.CoD4=Call of Duty 4: Modern Warfare
CoDHUD.Type.WaW=Call of Duty: World at War
CoDHUD.Type.MW2=Call of Duty: Modern Warfare 2
CoDHUD.Type.BO=Call of Duty: Black Ops
CoDHUD.Type.MW3=Call of Duty: Modern Warfare 3
CoDHUD.Type.BO2=Call of Duty: Black Ops II

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Välj team
CoDHUD.Faction.Select.desc=Välj det teamet du vill representera.\nPåverkar din Vänn-eller-Fiende-status och ändrar din kommentator och tema att matcha teamet.
CoDHUD.Faction.SelectAgain=Du kan byta team i Spawnmenyn via "CoD-Gränssnitt"-knappen i Contextmenyn.

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Snabbåtkomst

CoDHUD.Quick.DisableHUD=Snabbavaktivera alla gränssnittalternativ
CoDHUD.Quick.DisableHUD.desc=Avaktiverar alla CoD-gränssnittalternativ.

# ---------[ AUDIO-RELATED ]---------
CoDHUD.Audio=Ljudinställningar
CoDHUD.Audio.Announcer=Kommentator
CoDHUD.Audio.Music=Musik

CoDHUD.Audio.Announcer.Enable=Aktivera kommentatorröst
CoDHUD.Audio.Announcer.Enable.desc=Aktiverar kommentatorn.

CoDHUD.Audio.Announcer.English=Tvinga engelsk kommentator
CoDHUD.Audio.Announcer.English.desc=Tvingar att engelska kommentatorns röster spelas upp, oavsett vad spelets språk är.

CoDHUD.Audio.Music.Enable=Aktivera musik
CoDHUD.Audio.Music.Enable.desc=Aktiverar musik.

CoDHUD.Audio.Music.Ambient=Aktivera ambientmusik
CoDHUD.Audio.Music.Ambient.desc=Aktiverar ambientmusik som spelas i bakgrunden.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=Gränssnittinställningar

# Multiple
CoDHUD.HUD.Outline=Outlined Text
CoDHUD.HUD.Outline.desc=Activates outlined texts on some elements to make them easier to read in really bright areas.

CoDHUD.HUD.Sound=Play SFX
CoDHUD.HUD.Sound.desc=Plays associated sound effects if the HUD Type supports it.

CoDHUD.HUD.Time.Total=Active Time
CoDHUD.HUD.Time.Total.desc=How long the variable remains on-screen after fully fading in before it fades back out.

CoDHUD.HUD.Time.Fadein=Fade-in Time
CoDHUD.HUD.Time.Fadein.desc=How long it takes for this variable to fade in.

CoDHUD.HUD.Time.Fadeout=Fade-out Time
CoDHUD.HUD.Time.Fadeout.desc=How long it takes for this variable to fade out.

# Scoreboard
CoDHUD.HUD.Scoreboard=Scoreboard

CoDHUD.HUD.Scoreboard.Enable=Enable Scoreboard
CoDHUD.HUD.Scoreboard.Enable.desc=Enables a themed Scoreboard. Displays the factions currently occupied by all players.

# Score Counter
CoDHUD.HUD.Scorecounter=Score Counter

CoDHUD.HUD.Scorecounter.Enable=Enable Score Counter
CoDHUD.HUD.Scorecounter.Enable.desc=Enables a themed server timer, faction icon and score counters.\nSome HUD Types won't display the faction icon.

# Medals
CoDHUD.HUD.Medals=Medals

CoDHUD.HUD.Medals.Enable=Enable Medals
CoDHUD.HUD.Medals.Enable.desc=Enables themed medals, achieved by performing certain actions, such as quick kills or headshots.\nAlso activates associated sound effects.\nNote that some HUD Types have text only, while some have text and icons.

CoDHUD.HUD.Medals.Speedup=Faster if long queue
CoDHUD.HUD.Medals.Speedup.desc=Speeds up the medal queue if there's many of them queued up at once.\nDepending on the HUD Type, also disables the associated SFX if there's more than 3 medals queued.

# Kill Feed
CoDHUD.HUD.Killfeed=Kill Feed

CoDHUD.HUD.Killfeed.Enable=Enable Kill Feed
CoDHUD.HUD.Killfeed.Enable.desc=Enables a themed kill feed.

# Minimap
CoDHUD.HUD.Minimap=Minimap

CoDHUD.HUD.Minimap.Enable=Enable Minimap
CoDHUD.HUD.Minimap.Enable.desc=Enables a themed minimap.

# Hitmarker
CoDHUD.HUD.Hitmarker=Hitmarker

CoDHUD.HUD.Hitmarker.Enable=Enable Hitmarker
CoDHUD.HUD.Hitmarker.Enable.desc=Enables a themed hitmarker and its associated hit sound.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Weapon Info

CoDHUD.HUD.WeaponInfo.Enable=Enable Weapon Info
CoDHUD.HUD.WeaponInfo.Enable.desc=Enables a themed weapon info tab, displaying the weapon name and ammo counter.\nSome HUD Types incorporate the compass here too.

CoDHUD.HUD.WeaponPrompts.Enable=Enable Weapon Prompts
CoDHUD.HUD.WeaponPrompts.Enable.desc=Enables themed weapon prompts, such as low ammo notifications.

# XP Counter
CoDHUD.HUD.XP=XP Prompt

CoDHUD.HUD.XP.Enable=Enable XP Prompt
CoDHUD.HUD.XP.Enable.desc=Enables a themed XP prompt.

# Target ID / IFF
CoDHUD.HUD.IFF=Identify Friend-or-Foe

CoDHUD.HUD.IFF.Enable=Enable IFF
CoDHUD.HUD.IFF.Enable.desc=Enables a themed "Identify Friend-or-Foe" system, displaying the target's name above their heads when aiming near them.

# Death Icon
CoDHUD.HUD.DeathIcon=Death Icon

CoDHUD.HUD.DeathIcon.Enable=Enable Death Icon
CoDHUD.HUD.DeathIcon.Enable.desc=Enables the death icon, displayed where any player on the same faction dies.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Enable Chat
CoDHUD.HUD.Chat.Enable.desc=Enables a themed chat.

# Challenges
CoDHUD.HUD.Challenges=Challenges

CoDHUD.HUD.Challenges.Enable=Enable Challenge Prompts
CoDHUD.HUD.Challenges.Enable.desc=Enables themed challenge prompts.\nDoes not affect the tracking of challenges, nor the unlocking of them.


# ---------[ COD HUD MENU RELATED ]---------
CoDHUD.MenuSettings=Menu Settings

# Fullscreen
CoDHUD.Menu.Fullscreen=Open in Fullscreen
CoDHUD.Menu.Fullscreen.desc=Opens the CoD HUD Menu in fullscreen instead of a smaller window.
