#---------- CoD HUD Settings | Svenska | Swedish (CUSTOM)
# Translator: Moka

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD-Gränssnitt

CoDHUD.Client=Klient
CoDHUD.Server=Server
CoDHUD.General=Generell

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Påbörja runda

CoDHUD.RoundStart.Gamemode=Välj spelläge
CoDHUD.RoundStart.Start=Aktivera 'påbörja runda'-processen
CoDHUD.RoundStart.Info=Välj ett spelläge, och tryck sedan på knappen nedanför.

CoDHUD.RoundStart.Notice=Är du säker på att du vill påbörja en ny runda?\nAlla poäng kommer nollställas och alla spelare kommer återuppstå.
CoDHUD.RoundStart.Yes=Påbörja runda
CoDHUD.RoundStart.No=Avbryt

CoDHUD.RoundStart.Timer='Påbörja runda'-timer
CoDHUD.RoundStart.Timer.desc=Hur många sekunder mellanakt borde det vara innan rundan börjar.

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Aktivera "matchavslut"
CoDHUD.Admin.EndScreen.desc=Aktiverar ett "matchavslut"-system när poängbegränsningen är nådd.

CoDHUD.Admin.EndScreen.StartNext=Påbörja ny runda efter matchavslut
CoDHUD.Admin.EndScreen.StartNext.desc=Om påslaget så kommer en ny runda påbörja efter matchen avslutas.\nOm avaktiverat så kommer alla spelare återuppstå normalt.

CoDHUD.Admin.EndScreen.Scorelimit=Poängbegränsning
CoDHUD.Admin.EndScreen.Scorelimit.desc=Sätter högsta poängbegränsningen som visas på poängräknaren.\nMäts i dråp.

CoDHUD.Admin.FriendlyFire=Tillåt vådaskott
CoDHUD.Admin.FriendlyFire.desc=Om påslaget så kan spelare på samma team skada varandra.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Begränsa team och typ av gränssnitt
CoDHUD.Admin.RestrictType.desc=Välj vilken CoD-typ du vill begränsa spelare till. Ändrande av värdet kommer slumpmässigt ändra allas nuvarande team.\n\nDetta påverkar alla spelares:\n- Val av team \n- CoD-Gränssnittmenyns bakgrund och ljudeffekter

CoDHUD.Type.CoD4=Call of Duty 4: Modern Warfare
CoDHUD.Type.WaW=Call of Duty: World at War
CoDHUD.Type.MW2=Call of Duty: Modern Warfare 2
CoDHUD.Type.BO=Call of Duty: Black Ops
CoDHUD.Type.MW3=Call of Duty: Modern Warfare 3
CoDHUD.Type.BO2=Call of Duty: Black Ops II

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Välj team
CoDHUD.Faction.Select.desc=Välj det teamet du vill representera.\nPåverkar din Vänn-eller-Fiende-status och ändrar din kommentator och tema att matcha teamet.
CoDHUD.Faction.SelectAgain=Du kan byta team i Spawnmenyn via "CoD-Gränssnitt"-knappen i Contextmenyn.

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Snabbåtkomst

CoDHUD.Quick.DisableHUD=Snabbavaktivera alla gränssnittalternativ
CoDHUD.Quick.DisableHUD.desc=Avaktiverar alla CoD-gränssnittalternativ.

# ---------[ AUDIO-RELATED ]---------
CoDHUD.Audio=Ljudinställningar
CoDHUD.Audio.Announcer=Kommentator
CoDHUD.Audio.Music=Musik

CoDHUD.Audio.Announcer.Enable=Aktivera kommentatorröst
CoDHUD.Audio.Announcer.Enable.desc=Aktiverar kommentatorn.

CoDHUD.Audio.Announcer.English=Tvinga engelsk kommentator
CoDHUD.Audio.Announcer.English.desc=Tvingar att engelska kommentatorns röster spelas upp, oavsett vad spelets språk är.

CoDHUD.Audio.Music.Enable=Aktivera musik
CoDHUD.Audio.Music.Enable.desc=Aktiverar musik.

CoDHUD.Audio.Music.Ambient=Aktivera ambientmusik
CoDHUD.Audio.Music.Ambient.desc=Aktiverar ambientmusik som spelas i bakgrunden.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=Gränssnittinställningar

# Multiple
CoDHUD.HUD.Outline=Konturerad text
CoDHUD.HUD.Outline.desc=Aktiverar konturerad text på vissa element för att göra det lättare att läsa i ljusa områden.

CoDHUD.HUD.Sound=Spela ljudeffekt
CoDHUD.HUD.Sound.desc=Spelar den kopplade ljudeffekten om gränssnittalternativet stödjer det.

CoDHUD.HUD.Time.Total=Aktiv tid
CoDHUD.HUD.Time.Total.desc=Hur länge variabeln håller sig uppe på skärmen efter den tonat in innan den tonas ut igen.

CoDHUD.HUD.Time.Fadein=Tona in tid
CoDHUD.HUD.Time.Fadein.desc=Hur länge det tar för denna variabeln att tona in.

CoDHUD.HUD.Time.Fadeout=Tona ut tid
CoDHUD.HUD.Time.Fadeout.desc=Hur länge det tar för denna variabeln att tona ut.

# Scoreboard
CoDHUD.HUD.Scoreboard=Poängtavla

CoDHUD.HUD.Scoreboard.Enable=Aktivera poängtavla
CoDHUD.HUD.Scoreboard.Enable.desc=Aktiverar en temapoängtavla. Visar lagen som har nuvarande spelare i sig.

# Score Counter
CoDHUD.HUD.Scorecounter=Poängräknare

CoDHUD.HUD.Scorecounter.Enable=Aktivera poängräknare
CoDHUD.HUD.Scorecounter.Enable.desc=Aktiverar en tema servertimer, teamikon och poängräknare.\nVissa gränssnittalternativ visar inte teamikonen.

# Medals
CoDHUD.HUD.Medals=Medaljer

CoDHUD.HUD.Medals.Enable=Aktivera medaljer
CoDHUD.HUD.Medals.Enable.desc=Aktiverar temamedaljer som tjänas genom att utföra visa handlingar, exempelvis snabba dråp eller huvudskott.\nNotera att vissa gränssnittalternativ är endast text och vissa har texter och ikoner.

CoDHUD.HUD.Medals.Speedup=Snabbare med lång kö
CoDHUD.HUD.Medals.Speedup.desc=Ökar hastigheten på medaljkön om det finns många i den samtidigt.\nBeroende på gränssnittalternativet så avaktiverar den också den kopplade ljudeffekten om det finns fler än 3 medaljer i kön.

# Kill Feed
CoDHUD.HUD.Killfeed=Dråplista

CoDHUD.HUD.Killfeed.Enable=Aktivera dråplistan
CoDHUD.HUD.Killfeed.Enable.desc=Aktiverar en dråplista.

# Minimap
CoDHUD.HUD.Minimap=Minikarta

CoDHUD.HUD.Minimap.Enable=Aktivera minikarta
CoDHUD.HUD.Minimap.Enable.desc=Aktiverar en minikarta.

# Hitmarker
CoDHUD.HUD.Hitmarker=Träffmarkör

CoDHUD.HUD.Hitmarker.Enable=Aktivera träffmarkör
CoDHUD.HUD.Hitmarker.Enable.desc=Aktiverar en träffmarkör och dess kopplade ljudeffekt.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Vapeninfo

CoDHUD.HUD.WeaponInfo.Enable=Aktivera vapeninfo
CoDHUD.HUD.WeaponInfo.Enable.desc=Aktiverar vapeninfo-flik. Den visar vapnets namn och ammunitionsräknare.\nVissa gränssnittalternativ lägger också till en kompass här.

CoDHUD.HUD.WeaponPrompts.Enable=Aktivera vapennotiser
CoDHUD.HUD.WeaponPrompts.Enable.desc=Aktiverar vapennotiser. Den visar notiser, exempelvis låg ammo.

# XP Counter
CoDHUD.HUD.XP=EP-Räknare

CoDHUD.HUD.XP.Enable=Aktivera EP-räknare
CoDHUD.HUD.XP.Enable.desc=Aktiverar en EP-notis ("Erfarenhetspoäng").

# Target ID / IFF
CoDHUD.HUD.IFF=Identifiera Vänn-eller-Fiende

CoDHUD.HUD.IFF.Enable=Aktivera VEN
CoDHUD.HUD.IFF.Enable.desc=Aktiverar ett "Identifiera vänn-eller-fiende"-system som visar måltavlans namn ovanför dess huvud när du siktar nära dem.

# Death Icon
CoDHUD.HUD.DeathIcon=Dödsikon

CoDHUD.HUD.DeathIcon.Enable=Aktivera dödsikon
CoDHUD.HUD.DeathIcon.Enable.desc=Aktiverar dödsikonen som visar vart spelare på samma team har dött.

# Chat
CoDHUD.HUD.Chat=Chatt

CoDHUD.HUD.Chat.Enable=Aktivera chatt
CoDHUD.HUD.Chat.Enable.desc=Aktiverar chatten.

# Challenges
CoDHUD.HUD.Challenges=Utmaningar

CoDHUD.HUD.Challenges.Enable=Aktivera utmaningsnotiser
CoDHUD.HUD.Challenges.Enable.desc=Aktiverar utmaningsnotiser.\nPåverkar inte spårning eller upplåsning av utmaningar.


# ---------[ COD HUD MENU RELATED ]---------
CoDHUD.MenuSettings=Menyinställningar

# Fullscreen
CoDHUD.Menu.Fullscreen=Öppna i helskärm
CoDHUD.Menu.Fullscreen.desc=Öppnar CoD-Gränssnittmenyn i helskärm istället för i ett mindre fönster.