#---------- MW2 HUD Settings | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Client
MW2HUD.Title=MW2-Gränssnitt

MW2HUD.OpenMenu=Öppna MW2-Gränssnittmenyn

MW2HUD.Client=Klientinställningar
MW2HUD.Server=Serverinställningar

# Factions
MW2HUD.Faction.Select=Välj team
MW2HUD.Faction.Select.desc=Välj vilket team du vill representera.\nPåverkar din "vän eller fiende"-status och ändrar din kommentator och tema för att matcha teamet.

MW2HUD.Faction.SelectAgain=Du kan ändra team i Spawnmenyn under Options > MW2 > Klientinställningar.

# Admin
MW2HUD.Admin=Admin-Inställningar

MW2HUD.Admin.Score=Poängbegränsning
MW2HUD.Admin.Score.desc=Sätter högsta poängbegränsningen på poängräknaren.\nSätt till 0 för "Oändligt", dvs. alltid det lägsta värdet.

MW2HUD.Admin.EndScreen=Aktivera "Matchslut"
MW2HUD.Admin.EndScreen.desc=Aktiverar ett "matchslut"-system när poängbegränsningen är nådd.

MW2HUD.Admin.EndScreen.StartNext=Påbörja ny runda efter matchslut
MW2HUD.Admin.EndScreen.StartNext.desc=Om påslaget så kommer en ny runda påbörja så fort 'matchslut'-tiden har gått ut.\nOm avaktiverat så kommer alla spelare återuppstå normalt.

# Other
MW2HUD.DisableAll.Title=Snabbavaktivering

MW2HUD.DisableAll.HUD=Snabbavaktivera gränssnittalternativ
MW2HUD.DisableAll.HUD.desc=Avaktiverar alla MW2-gränssnittalternativ.

MW2HUD.DisableAll.audio=Snabbavaktivera ljudinställningar
MW2HUD.DisableAll.audio.desc=Avaktiverar alla MW2-ljudinställningar.

MW2HUD.Menu=Menyinställningar

MW2HUD.Menu.Fullscreen=Visa gränssnittmenyn i helskärm
MW2HUD.Menu.Fullscreen.desc=Gränssnittmenyn kommer täcka hela skärmen istället för att vara i ett mindre fönster.\n\nKommer med en ny "Stäng"-knapp och stänger av förmågan att flytta runt fönstret.

# Sounds
MW2HUD.Audio=Ljudinställningar

MW2HUD.Audio.Announcer=Aktivera kommentator
MW2HUD.Audio.Announcer.desc=Aktiverar kommentatorn.

MW2HUD.Audio.Music=Aktivera musik
MW2HUD.Audio.Music.desc=Aktiverar musik.

MW2HUD.Audio.Announcer.English=Tvinga engelsk kommentator
MW2HUD.Audio.Announcer.English.desc=Tvingar att den engelska kommentatorns röst spelas, oavsett vad spelets språk är.

MW2HUD.Audio.Ambient=Aktivera omgivningsmusik
MW2HUD.Audio.Ambient.desc=Aktiverar omgivningsmusik som spelas i bakgrunden.

# HUD
MW2HUD.Enable.Options=Gränssnittinställningar

MW2HUD.Enable.Outline=Konturerad text
MW2HUD.Enable.Outline.desc=Aktiverar konturerad text på vissa element för att göra dem lättare att se i ljusa områden.\nPåverkar: Utmanings- & Dråpmeddelanden, Poängräknaren, Poängtavlan, Matchslut och Påbörja runda.

MW2HUD.Enable.Score=Aktivera poängräknare
MW2HUD.Enable.Score.desc=Aktiverar servertimern, teamikonen och poängräknaren.
MW2HUD.Enable.Score.tip=Tips: Om avaktiverat så rekommenderas det att också avaktivera kommentatorröst och musik.

MW2HUD.Enable.Splash=Aktivera dråpmeddelanden
MW2HUD.Enable.Splash.desc=Aktiverar dråpmeddelanden och avaktiverar deras ljudeffekter.

MW2HUD.Enable.Splash.Outline=Dråpmeddelanden - Konturerad text
MW2HUD.Enable.Splash.Outline.desc=Aktiverar konturerad text på dråpmeddelanden.

MW2HUD.Enable.Splash.Speedup=Dråpmeddelanden - Ökad hastighet
MW2HUD.Enable.Splash.Speedup.desc=Om påslaget så kommer dråpmeddelanden gå åt snabbare om det finns många i kö.\nHindrar också ljudeffekten att spela om det finns 3 eller fler meddelanden i kö.

MW2HUD.Enable.Feed=Aktivera dråplista
MW2HUD.Enable.Feed.desc=Aktiverar dråplistan.

MW2HUD.Enable.Map=Aktivera karta
MW2HUD.Enable.Map.desc=Aktiverar minikartan.

MW2HUD.Enable.Hitmarker=Aktivera träffmarkör
MW2HUD.Enable.Hitmarker.desc=Aktiverar träffmarkören och dess träffljudeffekt.

MW2HUD.Enable.Weapon=Dälj vapeninfo
MW2HUD.Enable.Weapon.desc=Aktiverar vapnets namn, ammo räknaren och kompassen.\n\nOmaktiverar standard HL2 ammo räknare.

MW2HUD.Enable.XP=Aktivera EP-räknare
MW2HUD.Enable.XP.desc=Aktiverar EP-räknaren.

MW2HUD.Enable.Target=Aktivera måltavla-ID
MW2HUD.Enable.Target.desc=Aktiverar måltavlans namn ovanför deras huvud när du siktar nära dem.

MW2HUD.Enable.DeathIcon=Aktivera dödsikon
MW2HUD.Enable.DeathIcon.desc=Aktiverar dödsikonen.

MW2HUD.Enable.Prompt=Aktivera vapennotiser
MW2HUD.Enable.Prompt.desc=Aktiverar vapennotiserna, inklusive "Ladda om", "Låg ammo" och "Ingen ammo".

MW2HUD.Enable.Chat=Aktivera chatt
MW2HUD.Enable.Chat.desc=Aktiverar chatten.

MW2HUD.Enable.Challenges=Aktivera utmaningsnotiser
MW2HUD.Enable.Challenges.desc=Aktiverar utmaningsnotiser.\nPåverkar inte språandet eller upplåsningen av utmaningar.

MW2HUD.Enable.Scoreboard=Aktivera poängtavla
MW2HUD.Enable.Scoreboard.desc=Aktiverar poängtavlan.

MW2HUD.Enable.Throwback=Aktivera 'kasta tillbaka granat'-notis
MW2HUD.Enable.Throwback.desc=Aktiverar en 'kasta tillbaka'-notis när du är nära en handgranat.

# Round Start
MW2HUD.RoundStart=Påbörja runda

MW2HUD.RoundStart.Gamemode=Välj spelläge
MW2HUD.RoundStart.Start=Påbörja "Påbörja runda"-process
MW2HUD.RoundStart.Admin=Detta är en Administratör process!

MW2HUD.RoundStart.Notice=Är du säker på att du vill påbörja en ny runda?\nAlla poäng kommer nollställas och alla spelare kommer återuppstå.
MW2HUD.RoundStart.Yes=Ja, nu kör vi
MW2HUD.RoundStart.No=Nej