#---------- MW2 HUD Settings | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Client
MW2HUD.Client=Klientinställningar

# Factions
MW2HUD.Faction.Select=Välj team
MW2HUD.Faction.Select.desc=Välj vilket team du vill representera.\nPåverkar din "vän eller fiende"-status och ändrar din kommentator och tema för att matcha teamet.

MW2HUD.Faction.SelectAgain=Du kan ändra team i Spawnmenyn under Options > MW2 > Klientinställningar.

# Sounds
MW2HUD.Audio=Ljudinställningar

MW2HUD.Audio.Announcer=Aktivera kommentator
MW2HUD.Audio.Announcer.desc=Aktiverar kommentatorn.

MW2HUD.Audio.Music=Aktivera musik
MW2HUD.Audio.Music.desc=Aktiverar musik.

MW2HUD.Audio.Announcer.English=Tvinga engelsk kommentator
MW2HUD.Audio.Announcer.English.desc=Tvingar att den engelska kommentatorns röst spelas, oavsett vad spelets språk är.

# Disable Options
MW2HUD.Enable.Options=HUD Options

MW2HUD.Enable.Score=Aktivera poängräknare
MW2HUD.Enable.Score.desc=Aktiverar servertimern, teamikonen och poängräknaren.
MW2HUD.Enable.Score.tip=Tips: Om avaktiverat så rekommenderas det att också avaktivera kommentatorröst och musik.

MW2HUD.Enable.Splash=Aktivera dråpmeddelanden
MW2HUD.Enable.Splash.desc=Aktiverar dråpmeddelanden och avaktiverar deras ljudeffekter.

MW2HUD.Enable.Splash.Outline=Konturerad text på dråpmeddelanden
MW2HUD.Enable.Splash.Outline.desc=Aktiverar konturerad text på dråpmeddelanden.

MW2HUD.Enable.Feed=Aktivera dråplista
MW2HUD.Enable.Feed.desc=Aktiverar dråplistan.

MW2HUD.Enable.Map=Aktivera karta
MW2HUD.Enable.Map.desc=Aktiverar minikartan.

MW2HUD.Enable.Hitmarker=Aktivera träffmarkör
MW2HUD.Enable.Hitmarker.desc=Aktiverar träffmarkören och dess träffljudeffekt.

MW2HUD.Enable.Weapon=Dälj vapeninfo
MW2HUD.Enable.Weapon.desc=Aktiverar vapnets namn, ammo räknaren och kompassen.\n\nOmaktiverar standard HL2 ammo räknare.

MW2HUD.Enable.XP=Aktivera EP-räknare
MW2HUD.Enable.XP.desc=Aktiverar EP-räknaren.

MW2HUD.Enable.Target=Aktivera måltavla-ID
MW2HUD.Enable.Target.desc=Aktiverar måltavlans namn ovanför deras huvud när du siktar nära dem.

MW2HUD.Enable.DeathIcon=Aktivera dödsikon
MW2HUD.Enable.DeathIcon.desc=Aktiverar dödsikonen.

MW2HUD.Enable.Prompt=Aktivera vapennotiser
MW2HUD.Enable.Prompt.desc=Aktiverar vapennotiserna, inklusive "Ladda om", "Låg ammo" och "Ingen ammo".

# Admin
MW2HUD.Admin=Admin-Inställningar

MW2HUD.Admin.Score=Poängbegränsning
MW2HUD.Admin.Score.desc=Sätter högsta poängbegränsningen på poängräknaren.\nSätt till 0 för "Oändligt", dvs. alltid det lägsta värdet.