#---------- MW2 HUD Settings | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Client
MW2HUD.Client=Klientinställningar

# Factions
MW2HUD.Faction.Select=Välj team
MW2HUD.Faction.Select.desc=Välj vilket team du vill representera.\nPåverkar din "vän eller fiende"-status och ändrar din kommentator och tema för att matcha teamet.

MW2HUD.Faction.SelectAgain=Du kan ändra team i Spawnmenyn under Options > MW2 > Klientinställningar.

# Disable Options
MW2HUD.Disable=Döljningsinställningar
MW2HUD.Disable.desc=Håll pekaren över inställningen för att se exakt vad som kommer döljas.

MW2HUD.Disable.OnFoot=Till fots
MW2HUD.Disable.InVeh=Under körning

MW2HUD.Disable.Map=Dölj karta
MW2HUD.Disable.Map.desc=Döljer minikartan.

MW2HUD.Disable.Score=Dölj poängräknare
MW2HUD.Disable.Score.desc=Döljer servertimern, teamikonen och poängräknaren.

MW2HUD.Disable.Weapon=Dälj vapeninfo
MW2HUD.Disable.Weapon.desc=Döljer vapnets namn, ammo räknaren och kompassen.\n\nOmaktiverar standard HL2 ammo räknare.

MW2HUD.Disable.Splash=Dölj dråpmeddelanden
MW2HUD.Disable.Splash.desc=Döljer dråpmeddelanden och avaktiverar deras ljudeffekter.

MW2HUD.Disable.XP=Dölj EP-räknare
MW2HUD.Disable.XP.desc=Döljer EP-räknaren.

MW2HUD.Disable.Prompt=Dölj vapennotiser
MW2HUD.Disable.Prompt.desc=Döljer vapennotiserna, inklusive "Ladda om", "Låg ammo" och "Ingen ammo".

# Sounds
MW2HUD.Audio=Ljudinställningar

MW2HUD.Audio.Announcer=Aktivera kommentator
MW2HUD.Audio.Announcer.desc=Aktiverar kommentatorn.

MW2HUD.Audio.Announcer.English=Tvinga engelsk kommentator
MW2HUD.Audio.Announcer.English.desc=Tvingar att den engelska kommentatorns röst spelas, oavsett vad spelets språk är.

MW2HUD.Audio.Music=Aktivera musik
MW2HUD.Audio.Music.desc=Aktiverar musik.

# Admin
MW2HUD.Admin=Admin-Inställningar

MW2HUD.Admin.Score=Poängbegränsning
MW2HUD.Admin.Score.desc=Sätter högsta poängbegränsningen på poängräknaren.\nSätt till 0 för "Oändligt", dvs. alltid det lägsta värdet.