#---------- MW2 HUD | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Factions
MW2_MP_US_ARMY_NAME=Army Rangers
MW2_MP_SEALS_UDT_NAME=Navy SEALs
MW2_MP_MILITIA_NAME=Milis
MW2_MP_TASKFORCE_NAME=Specialförband 141
MW2_MP_OPFOR_NAME=OpFor
MW2_MP_SPETSNAZ_NAME=Spetsnaz

MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_SEALS_UDT_SHORT_NAME=SEALs
MW2_MP_MILITIA_SHORT_NAME=Milis
MW2_MP_TASKFORCE_SHORT_NAME=SF 141
MW2_MPUI_OPFOR_SHORT=OpFor
MW2_MPUI_SPETSNAZ_SHORT=Spetsnaz

# Splashes
MW2_SPLASHES_HEADSHOT=Huvudskott!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Assisterat självmord!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Du hjälpte till med självmordet av en fiende.
MW2_SPLASHES_LONGSHOT=Långskott!
MW2_SPLASHES_LONGSHOT_DESC=Najs dråp från ett avstånd!
MW2_SPLASHES_EXECUTION=Avrättning!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Hämnare!
MW2_SPLASHES_AVENGER_DESC=Du hämnade en lagkamrat.
MW2_SPLASHES_DEFENDER=Räddare!
MW2_SPLASHES_DEFENDER_DESC=Du räddade en lagkamrat.
MW2_SPLASHES_POSTHUMOUS=Livet efter!
MW2_SPLASHES_POSTHUMOUS_DESC=Du dödade en fiende efter du dog.
MW2_SPLASHES_REVENGE=Hämnd!
MW2_SPLASHES_REVENGE_DESC=Du fick hämnd.
MW2_SPLASHES_DOUBLEKILL=Dubbeldråp!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Trippeldråp!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Flerdråp!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Första blodet!
MW2_SPLASHES_FIRSTBLOOD_DESC=Du tog första dråpet.
MW2_SPLASHES_BUZZKILL=Buzzkill!
MW2_SPLASHES_BUZZKILL_DESC=Stoppade en fiende nära en dråpserie.
MW2_SPLASHES_COMEBACK=Återkomst!
MW2_SPLASHES_COMEBACK_DESC=Du kom tillbaks efter flertal dödsfall.
MW2_SPLASHES_FLAGRETURN=Flagga återkommen!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Flaggspringare!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Plats säkrad!
MW2_SPLASHES_CAPTURE_DESC=Du erövrade ett uppdragsmål.
MW2_SPLASHES_DEFEND=Försvar!
MW2_SPLASHES_DEFEND_DESC=Du försvarade ett uppdragsmål.
MW2_SPLASHES_ASSAULT=Offensiv!
MW2_SPLASHES_ASSAULT_DESC=Du dödade en försvarare.
MW2_SPLASHES_PLANT=Sabotör!
MW2_SPLASHES_PLANT_DESC=Du armerade bomben.
MW2_SPLASHES_DEFUSE=Hjälta!
MW2_SPLASHES_DEFUSE_DESC=Du desarmerade bomben.
MW2_SPLASHES_SAB_OVERTIME=Övertid!
MW2_SPLASHES_SAB_OVERTIME_DESC=Basen närmast bomben kommer förstöras.
MW2_SPLASHES_MARTYRDOM_DESC=Du släpper en aktiv granat när du dör.
MW2_SPLASHES_FINALSTAND_DESC=Du får en andra chans när du går ner.
MW2_SPLASHES_ENDGAME_DESC=Du får extra livspoäng under ett par sekunder.
MW2_SPLASHES_C4DEATH_DESC=Ta fram C4 innan du dör.
MW2_SPLASHES_KNIFETHROW_DESC=Du dödade en fiende med en kastbar kniv.
MW2_SPLASHES_KNIFETHROW=Mitt i prick!
MW2_SPLASHES_HIJACKER_DESC=Du erövrade en fiendes förnödenhetslåda.
MW2_SPLASHES_HIJACKER=Tjuv!
MW2_SPLASHES_HIJACKED=%s erövrade din förnödenhetslåda.
MW2_SPLASHES_DEFCON_LOWER=DEFCON Sänkt!
MW2_SPLASHES_DEFCON_RAISE=DEFCON Höjd
MW2_SPLASHES_DEFCON_LOWER_DESC=Dråpserier uppgraderade!
MW2_SPLASHES_DEFCON_RAISE_DESC=Dråpserier nedgraderade.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Matchen börjar!
MW2_SPLASHES_DEFCON_3_DESC=Akuta luftlandsättning inkommande!
MW2_SPLASHES_DEFCON_2_DESC=Dråpserier överrullade!
MW2_SPLASHES_DEFCON_1_DESC=Dubbla poäng för uppdragsmålen!
MW2_SPLASHES_COMBATHIGH_DESC=Ökad livspoäng under en kort period.
MW2_SPLASHES_RESTED=Daglig EP-boost!
MW2_SPLASHES_RESTED_DESC=Tjäna din dagliga bonus-EP!
MW2_SPLASHES_RESTED_DONE=Daglig EP-bonus färdig.
MW2_SPLASHES_RESTED_DONE_DESC=Bonus-EP mottagen.
MW2_SPLASHES_VIP=Du är VIP:n
MW2_SPLASHES_STUCK_SEMTEX=Fast!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Du träffade en fiende med en Semtex!
MW2_SPLASHES_HEROIC=Hjältemod!
MW2_SPLASHES_HEROIC_DESC=Du erövrade ett uppdragsmål i "Sista chansen"!
MW2_SPLASHES_DENIED=Nekad!
MW2_SPLASHES_DENIED_DESC=Du förstörde en fiendes taktisk insättning!
MW2_SPLASHES_DESTROYED_INSERTION=Blockade din T.I.!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Tog din låda!
MW2_SPLASHES_REVIVER_DESC=Du återupplevde en fallen lagkamrat.
MW2_SPLASHES_REVIVER=Återupplevare!
MW2_SPLASHES_GIVEAWAY_SENTRY=...tog ett Vaktgevär
MW2_SPLASHES_GIVEAWAY_AIRDROP=... tog ett luftlandsatt dråpserie.
MW2_SPLASHES_SEMTEX_STUCK=Träffade dig med Semtex
MW2_SPLASHES_ONE_SHOT_KILL="Ett skott"-dråp
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Ett skott... en död
MW2_SPLASHES_NINJA_DEFUSE=Ninja-Desarmering
MW2_SPLASHES_NINJA_DEFUSE_DESC=Vad tyst du var...
MW2_SPLASHES_COPYCAT_DESC=Stjäl din dödares klass under dråpkameran.
MW2_SPLASHES_COPIED=Kopierade klassen!
MW2_SPLASHES_REVIVED=Återupplevde Dig
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Sist vid liv!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Sist vid liv!
MW2_SPLASHES_SHIELDASSIST=Folkmassakontroll!
MW2_SPLASHES_SHIELDASSIST_DESC=Du var en utmärkt distraktion.
MW2_SPLASHES_DESTROYED_HELICOPTER=Förstörde Helikopter!
MW2_SPLASHES_DESTROYED_PAVELOW=Förstörde Pavelow!
MW2_SPLASHES_DESTROYED_UAV=Förstörde Drönare!
MW2_SPLASHES_DESTROYED_HARRIER=Förstörde Harrier!
MW2_SPLASHES_DESTROYED_AC130=Förstörde AC130!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Förstörde Gunship!
MW2_SPLASHES_FLAG_RETURN=Återvände flaggan!
MW2_SPLASHES_FLAG_CAPTURE=Erövrade flaggan!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Tog din flagga!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Tog fiendens flagga!
MW2_SPLASHES_FLAG_PICKUP=Tog flaggan!
MW2_SPLASHES_CAPTURED_NUKE=Atombomb erövrad!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Du erövrade atombomben.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Låste upp Förstorat Magasin!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Låste upp Hjärtslagsensor!
MW2_SPLASHES_UNLOCKED_AKIMBO=Låste upp Akimbo!
MW2_SPLASHES_UNLOCKED_THERMAL=Låste upp Värmesikte!
MW2_SPLASHES_UNLOCKED_EOTECH=Låste upp Holografiskt Sikte!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Låste upp Hagelbössa!
MW2_SPLASHES_GRABBED_THE_FLAG=Tog flaggan!
MW2_SPLASHES_HIJACKED_SENTRY=Tog ditt Vaktgevär!
MW2_SPLASHES_HIJACKED_AIRDROP=Tog din låda!
MW2_SPLASHES_BOMB_PLANTED=Armerade bomben!
MW2_SPLASHES_BOMB_DEFUSED=Desarmerade bomben!
MW2_SPLASHES_TIMEADDED=Tid tillagd!
MW2_SPLASHES_GTNW_OVERTIME=Sudden Death!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Ingen återuppståelse.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Förstörde uppdragsmål!
MW2_SPLASHES_SAVED_OBJECTIVE=Räddade uppdragsmål!
MW2_SPLASHES_CAPTURED_HQ=Erövrade huvudkvarteret!
MW2_SPLASHES_DESTROYED_HQ=Förstörde huvudkvarteret!
MW2_SPLASHES_BOMB_TAKEN=Tog bomben!
MW2_SPLASHES_BOMB_DROPPED=Släppte bomben!
MW2_SPLASHES_KILLED_CARRIER=Dödade bombbäraren!
MW2_SPLASHES_SHAREPACKAGE=Låda delad!
MW2_SPLASHES_SHAREPACKAGE_DESC=En lagkamrat räddade ditt Vårdpaket från fienden!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Återställde drönare!
MW2_SPLASHES_FLAGS_CAPTURE=Erövrade en flagga!
MW2_SPLASHES_FLAG_ASSAULT=Flaggangrepp!
MW2_SPLASHES_FLAG_DEFEND=Flaggförsvar!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Du dödade en som försvarade flaggan.
MW2_SPLASHES_FLAG_DEFEND_DESC=Du försvarade flaggan.
MW2_SPLASHES_FLAG_CAPTURED=Flagga erövrad!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Du erövrade fiendens flagga.
MW2_SPLASHES_SECURED_POSITION=Erövrade position!
MW2_SPLASHES_SECURED_POSITION_A=Erövrade A!
MW2_SPLASHES_SECURED_POSITION_B=Erövrade B!
MW2_SPLASHES_SECURED_POSITION_C=Erövrade C!
MW2_SPLASHES_TIME_ADDED=Tidsförlängning!
MW2_SPLASHES_TIME_ADDED_DESC=Bombplats förstörd. Speltid förlängd.

# Killstreaks
MW2_KILLSTREAKS_UAV=UAV
MW2_KILLSTREAKS_UAV_DESC=Visar fienden på kartan.
MW2_KILLSTREAKS_AIRSTRIKE=Luftangrepp
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Kallar in ett luftangrepp på valda platsen.
MW2_KILLSTREAKS_HELICOPTER=Attackhelikopter
MW2_KILLSTREAKS_HELICOPTER_DESC=Kalla in en understödshelikopter.
MW2_KILLSTREAKS_AC130=AC-130
MW2_KILLSTREAKS_AC130_DESC=Bli skytten i en AC-130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Predator-Robot
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Fjärrstyrd robot.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Helikopterskytt
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Bli skytten i en attackhelikopter.
MW2_KILLSTREAKS_HELICOPTER_MK19=Helikopterskytt
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Fjärrstyr en helikopters granattillsats.
MW2_KILLSTREAKS_DOUBLE_UAV=Avancerad drönare
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=Drönare med snabbare sveptid.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Precisionsluftangrepp
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Kallar in ett riktningsstyrt luftangrepp.
MW2_KILLSTREAKS_AIRDROP=Vårdpaket
MW2_KILLSTREAKS_AIRDROP_DESC=Luftlandsätt en slumpmässig dråpserie eller ammunition.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Vaktgevär
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Luftlandsätt ett placerbart Vaktgevär.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Vårdpaket (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Luftlandsätter en enkel Predator-robot.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Harrier-Angrepp
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Luftangrepp med en flygande Harrier.
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Smygbombare
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Luftangrepp ouptäckbar på fiendens kartor.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Super-Luftangrepp
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Luftangrepp med lite extra kick.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Helikopter Blackbox
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Helikopter som håller sig längre.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Helikopter, försvarbar
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Helikopter med facklor.
MW2_KILLSTREAKS_EMP=EMP
MW2_KILLSTREAKS_EMP_DESC=Avaktiverar temporärligt fiendens elektroniker.
MW2_KILLSTREAKS_TANK=Stridsvagn
MW2_KILLSTREAKS_TANK_DESC=En stridsvagn
MW2_KILLSTREAKS_COUNTER_UAV=Antidrönare
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Avaktiverar temporärligt fiendens radar.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Tungt bepansrad attackhelikopter.
MW2_KILLSTREAKS_NONE=Ingen
MW2_KILLSTREAKS_NONE_DESC=Ingen dråpserie vald.
MW2_KILLSTREAKS_AIRDROP_MEGA=Akut Luftlandsättning
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Luftlandsätt 4 slumpmässiga dråpserier eller ammunition.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Tryck på %s för AKUT LUFTLANDSÄTTNING.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Atombomb
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Avsluta spelet med ett pang.
MW2_KILLSTREAKS_SENTRY=Vaktgevär
  
MW2_MP_EARNED_AIRSTRIKE=Tryck på %s för LUFTANGREPP.
MW2_MP_EARNED_AIRDROP=Tryck på %s för LUFTLANDSÄTTNING.
MW2_MP_EARNED_SENTRY_AIRDROP=Tryck på %s för VAKTGEVÄR LUFTLANDSÄTTNING.
MW2_MP_EARNED_PREDATOR_AIRDROP=Tryck på %s för PREDATOR-LUFTLANDSÄTTNING.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Tryck på %s för PRECISIONLUFTANGREPP.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Tryck på %s för SMYGBOMBARE.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Tryck på %s för HARRIER-LUFTANGREPP.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Tryck på %s för SUPER-LUFTANGREPP.
MW2_MP_EARNED_UAV=Tryck på %s för DRÖNARE.
MW2_MP_EARNED_DOUBLE_UAV=Tryck på %s för AVANCERAD DRÖNARE.
MW2_MP_EARNED_COUNTER_UAV=Tryck på %s för ANTIDRÖNARE.
MW2_MP_EARNED_HELICOPTER=Tryck på %s för ATTACKHELIKOPTER.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Tryck på %s för HELIKOPTERSKYTT.
MW2_MP_EARNED_HELICOPTER_MK19=Tryck på %s för HELIKOPTER MK19.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Tryck på %s för HELICOPTER BLACKBOX.
MW2_MP_EARNED_HELICOPTER_FLARES=Tryck på %s för PAVELOW.
MW2_MP_EARNED_AC130=Tryck på %s för AC-130.
MW2_MP_EARNED_PREDATOR_MISSILE=Tryck på %s för PREDATOR-ROBOT.
MW2_MP_EARNED_NUKE=Tryck på %s för ATOMBOMB.
MW2_MP_EARNED_AUTO_SHOTGUN=Tryck på %s för HAGELBÖSSA.
MW2_MP_EARNED_AUTO_SENTRY=Tryck på %s för VAKTGEVÄR.
MW2_MP_EARNED_AUTO_SENTRY_GL=Tryck på %s för AUTO-GRANATTILLSATS.
MW2_MP_EARNED_THUMPER=Tryck på %s för THUMPER.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Tryck på %s för LITTLEBIRD.
MW2_MP_EARNED_EMP=Tryck på %s för EMP.

# Other
MW2_MP_CONNECTED=%s Anslöt
MW2_MP_DISCONNECTED=%s Kopplade bort
MW2_EXE_LEFTGAME=%s lämnade spelet

MW2_PLATFORM_RELOAD=Ladda om
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Låg ammo
MW2_WEAPON_NO_AMMO=Ingen ammo

MW2_MPUI_WINNING_CAPS=VINNER
MW2_MPUI_LOSING_CAPS=FÖRLORAR
MW2_MPUI_TIED_CAPS=LIKA

MW2_CGAME_SB_SCORE=Poäng
MW2_CGAME_SB_DEATHS=Död
MW2_CGAME_SB_KILLS=Dråp
MW2_CGAME_SB_ASSISTS=Assists
  
# Round Starter
MW2_MP_MATCH_STARTING_IN=Match börjar om:
MW2_MP_MATCH_RESUMING_IN=Match återupptar om:

# Gamemodes
MW2_MPUI_SABOTAGE=Sabotage
MW2_MPUI_DEATHMATCH=Fritt-för-Alla
MW2_MPUI_CAPTURE_THE_FLAG=Erövra flaggan
MW2_MPUI_HEADQUARTERS=Huvudkvarter
MW2_MPUI_SEARCH_AND_DESTROY=Sök & Förstör
MW2_MPUI_WAR=Lag Dödsmatch
MW2_MPUI_DOMINATION=Herravälde
MW2_MPUI_ONE_FLAG=Enkel Flagga
MW2_MPUI_ARENA=Arena
MW2_MPUI_DD=Demolering
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Global Atombombskrig

MW2_MP_OBJ_DM_HINT=Eliminera andra spelare.
MW2_MP_OBJ_WAR_HINT=Eliminera fientliga spelare.
MW2_OBJECTIVES_WAR_HINT=Eliminera fientliga spelare.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Förstör uppdragsmål A eller B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Skydda uppdragsmålen A och B.
MW2_OBJECTIVES_SAB_HINT=Förstör fientliga uppdragsmålet.
MW2_OBJECTIVES_DOM_HINT=Erövra och försvara flaggorna.
MW2_OBJECTIVES_DM_HINT=Eliminera andra spelare.
MW2_OBJECTIVES_KOTH_HINT=Håll huvudkvarteret.
MW2_OBJECTIVES_CTF_HINT=Erövra fiendens flagga.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Erövra fiendens flagga.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Försvara flaggan.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Förstör uppdragsmålen A och B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Skydda uppdragsmålen A och B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Döda VIP:n och hindra honom från att nå extraktionszonen.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Försvara VIP:n och hjälp honom att nå extraktionszonen.
MW2_OBJECTIVES_ARENA_HINT=Eliminera fienden, eller erövra flaggan
MW2_OBJECTIVES_GTNW_HINT=Erövra atombomben.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Ta fiendens flagga.

# Round Ender
MW2_MP_DRAW=Oavgjort
MW2_MP_VICTORY=Seger!
MW2_MP_DEFEAT=Förlust!
MW2_MP_ROUND_DRAW=Oavgjord runda
MW2_MP_ROUND_WIN=Runda vunnen
MW2_MP_ROUND_LOSS=Runda förload
MW2_MP_HALFTIME=Halvtid
MW2_MP_OVERTIME=Övertid
MW2_MP_MATCH_BONUS_IS=Matchbonus: %s

MW2_MP_OPFOR_ELIMINATED=OpFor eliminerades
MW2_MP_OPFOR_FORFEITED=OpFor kapitulerade
MW2_MP_SPETSNAZ_ELIMINATED=Spetsnaz eliminerades
MW2_MP_SPETSNAZ_FORFEITED=Spetsnaz kapitulerade
MW2_MP_US_ARMY_ELIMINATED=Amerikanska arméen eliminerades
MW2_MP_US_ARMY_FORFEITED=Amerikanska arméen kapitulerade
MW2_MP_MILITIA_ELIMINATED=Milisen eliminerades
MW2_MP_MILITIA_FORFEITED=Milisen kapitulerade
MW2_MP_TF141_ELIMINATED=TF141 eliminerades
MW2_MP_TF141_FORFEITED=TF141 kapitulerade
MW2_MP_SEALS_ELIMINATED=SEALs eliminerades
MW2_MP_SEALS_FORFEITED=SEALs kapitulerade