#---------- MW3 HUD | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Factions
MW3_MP_SAS=Special Air Service
MW3_MP_INNERCIRCLE_NAME=Inre Cirkel
MW3_MP_AFRICA_MILITIA_NAME=Afrikansk milis
MW3_MP_DELTA_NAME=Delta Force
MW3_MP_GIGN=GIGN
MW3_MP_SPETSNAZ_NAME=Spetsnaz
MW3_MP_PMC_NAME=Säkerhetsföretag
	
MW3_MP_SAS_SHORT_NAME=SAS
MW3_MP_INNERCIRCLE_SHORT_NAME=I.C.
MW3_MP_AFRICA_MILITIA_SHORT_NAME=Milis
MW3_MP_DELTA_SHORT_NAME=Delta
MW3_MP_GIGN_SHORT_NAME=GIGN
MW3_MPUI_SPETSNAZ_SHORT=Spetsnaz
MW3_MP_PMC_SHORT_NAME=Säkerhetsföretag