#---------- MW2 HUD | 日本語 | Japanese
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=陸軍レンジャー部隊
MW2_MP_SEALS_UDT_NAME=海軍SEALs
MW2_MP_MILITIA_NAME=民兵
MW2_MP_TASKFORCE_NAME=タスクフォース141
MW2_MP_OPFOR_NAME=対抗部隊
MW2_MP_SPETSNAZ_NAME=スペツナズ

MW2_MP_US_ARMY_SHORT_NAME=レンジャー
MW2_MP_SEALS_UDT_SHORT_NAME=SEALs
MW2_MP_MILITIA_SHORT_NAME=民兵
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_SPETSNAZ_SHORT=スペツナズ
MW2_MPUI_OPFOR_SHORT=対抗部隊

# Splashes
MW2_SPLASHES_HEADSHOT=ヘッドショット！
MW2_SPLASHES_HEADSHOT_DESC=
MW2_SPLASHES_ASSISTEDSUICIDE=アシストされた自滅！
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=敵の自滅に手を貸した。
MW2_SPLASHES_LONGSHOT=ロングショット！
MW2_SPLASHES_LONGSHOT_DESC=遠距離からしとめた！
MW2_SPLASHES_EXECUTION=処刑！
MW2_SPLASHES_EXECUTION_DESC=
MW2_SPLASHES_AVENGER=仇討ち！
MW2_SPLASHES_AVENGER_DESC=味方の仇を討った。
MW2_SPLASHES_DEFENDER=救出成功！
MW2_SPLASHES_DEFENDER_DESC=仲間を救出した。
MW2_SPLASHES_POSTHUMOUS=道連れ！
MW2_SPLASHES_POSTHUMOUS_DESC=死亡後に敵を倒した。
MW2_SPLASHES_REVENGE=復讐だ！
MW2_SPLASHES_REVENGE_DESC=恨みを晴らす。
MW2_SPLASHES_DOUBLEKILL=ダブルキル！
MW2_SPLASHES_DOUBLEKILL_DESC=
MW2_SPLASHES_TRIPLEKILL=トリプルキル！
MW2_SPLASHES_TRIPLEKILL_DESC=
MW2_SPLASHES_MULTIKILL=マルチキル！
MW2_SPLASHES_MULTIKILL_DESC=
MW2_SPLASHES_FIRSTBLOOD=先制攻撃！
MW2_SPLASHES_FIRSTBLOOD_DESC=最初のキルをとった。
MW2_SPLASHES_BUZZKILL=ぶち壊し！
MW2_SPLASHES_BUZZKILL_DESC=敵をキルストリーク寸前で食い止めた。
MW2_SPLASHES_COMEBACK=カムバック！
MW2_SPLASHES_COMEBACK_DESC=デスストリークから持ち直した。
MW2_SPLASHES_FLAGRETURN=フラッグ回収！
MW2_SPLASHES_FLAGRETURN_DESC=
MW2_SPLASHES_FLAGPICKUP=フラッグ・ランナー！
MW2_SPLASHES_FLAGPICKUP_DESC=
MW2_SPLASHES_CAPTURE=ポイントを確保！
MW2_SPLASHES_CAPTURE_DESC=目標を奪取した。
MW2_SPLASHES_DEFEND=防衛！
MW2_SPLASHES_DEFEND_DESC=目標を防衛した。
MW2_SPLASHES_ASSAULT=攻撃！
MW2_SPLASHES_ASSAULT_DESC=ディフェンダーを殺した。
MW2_SPLASHES_PLANT=破壊工作！
MW2_SPLASHES_PLANT_DESC=爆薬を設置した。
MW2_SPLASHES_DEFUSE=真の英雄！
MW2_SPLASHES_DEFUSE_DESC=爆弾を解除した。
MW2_SPLASHES_SAB_OVERTIME=オーバータイム！
MW2_SPLASHES_SAB_OVERTIME_DESC=爆弾に最も近い基地が破壊される。
MW2_SPLASHES_MARTYRDOM_DESC=死亡時にピンを抜いたグレネードを落とす。
MW2_SPLASHES_FINALSTAND_DESC=倒れてももう1回だけチャンスがある。
MW2_SPLASHES_ENDGAME_DESC=数秒間だけ体力が増加した状態となる。
MW2_SPLASHES_C4DEATH_DESC=死の間際にC4を取り出す。
MW2_SPLASHES_KNIFETHROW_DESC=敵を投げナイフで倒した。
MW2_SPLASHES_KNIFETHROW=百発百中！
MW2_SPLASHES_HIJACKER_DESC=敵の補給物資の箱を奪取した。
MW2_SPLASHES_HIJACKER=ハイジャック！
MW2_SPLASHES_HIJACKED=%sに補給物資の箱を奪われた。
MW2_SPLASHES_DEFCON_LOWER=DEFCONが低下した！
MW2_SPLASHES_DEFCON_RAISE=DEFCONが上昇した
MW2_SPLASHES_DEFCON_LOWER_DESC=キルストリークがアップグレードされた！
MW2_SPLASHES_DEFCON_RAISE_DESC=キルストリークがダウングレードされた。
MW2_SPLASHES_DEFCON_5=DEFCON5
MW2_SPLASHES_DEFCON_4=DEFCON4
MW2_SPLASHES_DEFCON_3=DEFCON3
MW2_SPLASHES_DEFCON_2=DEFCON2
MW2_SPLASHES_DEFCON_1=DEFCON1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON5
MW2_SPLASHES_DEFCON_4_DESC=対戦開始！
MW2_SPLASHES_DEFCON_3_DESC=緊急空中投下機が接近！
MW2_SPLASHES_DEFCON_2_DESC=キルストリークが持ち越しに！
MW2_SPLASHES_DEFCON_1_DESC=目標のポイントが2倍に！
MW2_SPLASHES_COMBATHIGH_DESC=短時間のみ体力が上昇する。
MW2_SPLASHES_RESTED=日数EXPブースト！
MW2_SPLASHES_RESTED_DESC=日数によるEXPボーナスを獲得！
MW2_SPLASHES_RESTED_DONE=日数EXPブースト完了。
MW2_SPLASHES_RESTED_DONE_DESC=ボーナスEXPを獲得。
MW2_SPLASHES_VIP=VIPに任命された
MW2_SPLASHES_STUCK_SEMTEX=ペッタリ！
MW2_SPLASHES_STUCK_SEMTEX_DESC=敵にセムテックスをくっつけた！
MW2_SPLASHES_HEROIC=英雄のかがみ！
MW2_SPLASHES_HEROIC_DESC=ラストスタンド中に目標を奪取した！
MW2_SPLASHES_DENIED=投入阻止！
MW2_SPLASHES_DENIED_DESC=敵の戦術マーカーを破壊した！
MW2_SPLASHES_DESTROYED_INSERTION=戦術的侵入を阻止された！
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=物資を奪われた！
MW2_SPLASHES_REVIVER_DESC=倒れた仲間を蘇生した。
MW2_SPLASHES_REVIVER=救命救急！
MW2_SPLASHES_GIVEAWAY_SENTRY=…が自動機銃を拾った。
MW2_SPLASHES_GIVEAWAY_AIRDROP=…が空中投下されたキルストリークを拾った。
MW2_SPLASHES_SEMTEX_STUCK=セムテックスをくっつけられた
MW2_SPLASHES_ONE_SHOT_KILL=ワンショットキル
MW2_SPLASHES_ONE_SHOT_KILL_DESC=一撃必殺！
MW2_SPLASHES_NINJA_DEFUSE=ニンジャのごとく
MW2_SPLASHES_NINJA_DEFUSE_DESC=慎重に、慎重に…
MW2_SPLASHES_COPYCAT_DESC=キルカメラ中に、やられた相手のクラスを盗める。
MW2_SPLASHES_COPIED=クラスをコピー！
MW2_SPLASHES_REVIVED=蘇生した
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=味方が最後の1人に！
MW2_SPLASHES_LAST_ENEMY_ALIVE=敵が最後の1人に！
MW2_SPLASHES_SHIELDASSIST=暴徒鎮圧！
MW2_SPLASHES_SHIELDASSIST_DESC=敵の注意を引きつけるにはもってこいだ。
MW2_SPLASHES_DESTROYED_HELICOPTER=ヘリコプターを破壊した！
MW2_SPLASHES_DESTROYED_PAVELOW=ペイブロウを破壊した！
MW2_SPLASHES_DESTROYED_UAV=UAVを破壊した！
MW2_SPLASHES_DESTROYED_HARRIER=ハリアーを破壊した！
MW2_SPLASHES_DESTROYED_AC130=AC-130を破壊した！
MW2_SPLASHES_DESTROYED_MINIGUNNER=ガンシップを破壊した！
MW2_SPLASHES_FLAG_RETURN=フラッグを回収した！
MW2_SPLASHES_FLAG_CAPTURE=フラッグを奪取！
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=味方のフラッグを取った！
MW2_SPLASHES_FLAG_PICKUP_ENEMY=敵のフラッグを取った！
MW2_SPLASHES_FLAG_PICKUP=フラッグを取った！
MW2_SPLASHES_CAPTURED_NUKE=反応弾を確保した！
MW2_SPLASHES_DESC_CAPTURED_NUKE=反応弾を奪取した。
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=拡張マガジンをアンロックした！
MW2_SPLASHES_UNLOCKED_HEARTBEAT=心音センサーをアンロックした！
MW2_SPLASHES_UNLOCKED_AKIMBO=デュアルをアンロックした！
MW2_SPLASHES_UNLOCKED_THERMAL=サーマルスコープをアンロックした！
MW2_SPLASHES_UNLOCKED_EOTECH=ホロサイトをアンロック！
MW2_SPLASHES_UNLOCKED_SHOTGUN=ショットガンをアンロックした！
MW2_SPLASHES_GRABBED_THE_FLAG=フラッグを奪った！
MW2_SPLASHES_HIJACKED_SENTRY=が自動機銃を奪った！
MW2_SPLASHES_HIJACKED_AIRDROP=が物資を奪った！
MW2_SPLASHES_BOMB_PLANTED=爆弾を設置！
MW2_SPLASHES_BOMB_DEFUSED=爆弾を解除！
MW2_SPLASHES_TIMEADDED=タイム追加！
MW2_SPLASHES_GTNW_OVERTIME=サドンデス！
MW2_SPLASHES_GTNW_OVERTIME_DESC=復活なし。
MW2_SPLASHES_DESTROYED_OBJECTIVE=目標を破壊！
MW2_SPLASHES_SAVED_OBJECTIVE=目標を守った！
MW2_SPLASHES_CAPTURED_HQ=司令部を奪取！
MW2_SPLASHES_DESTROYED_HQ=司令部を破壊！
MW2_SPLASHES_BOMB_TAKEN=爆弾を取った！
MW2_SPLASHES_BOMB_DROPPED=爆弾を落とした！
MW2_SPLASHES_KILLED_CARRIER=ボムキャリアを倒した！
MW2_SPLASHES_SHAREPACKAGE=物資を共有！
MW2_SPLASHES_SHAREPACKAGE_DESC=チームメイトが救援物資を敵から守った！
MW2_SPLASHES_DESTROYED_COUNTER_UAV=UAVを復帰させた！
MW2_SPLASHES_FLAGS_CAPTURE=フラッグを奪取した！
MW2_SPLASHES_FLAG_ASSAULT=フラッグアサルト！
MW2_SPLASHES_FLAG_DEFEND=フラッグ防衛！
MW2_SPLASHES_FLAG_ASSAULT_DESC=フラッグの守備者を倒した。
MW2_SPLASHES_FLAG_DEFEND_DESC=フラッグを防衛した。
MW2_SPLASHES_FLAG_CAPTURED=フラッグを奪取した！
MW2_SPLASHES_FLAG_CAPTURED_DESC=敵のフラッグを奪取した。
MW2_SPLASHES_SECURED_POSITION=位置を確保！
MW2_SPLASHES_SECURED_POSITION_A=Aを確保！
MW2_SPLASHES_SECURED_POSITION_B=Bを確保！
MW2_SPLASHES_SECURED_POSITION_C=Cを確保！
MW2_SPLASHES_TIME_ADDED=時間延長！
MW2_SPLASHES_TIME_ADDED_DESC=爆破ポイントを破壊。制限時間が延長された

# Killstreaks
MW2_KILLSTREAKS_UAV=UAV
MW2_KILLSTREAKS_UAV_DESC=敵の位置をミニマップに表示する。
MW2_KILLSTREAKS_AIRSTRIKE=航空支援
MW2_KILLSTREAKS_AIRSTRIKE_DESC=指定した地点に対し対地航空攻撃を\n要請する。
MW2_KILLSTREAKS_HELICOPTER=攻撃ヘリ
MW2_KILLSTREAKS_HELICOPTER_DESC=攻撃ヘリの支援を要請する。
MW2_KILLSTREAKS_AC130=AC-130
MW2_KILLSTREAKS_AC130_DESC=AC-130のガンナー役を務める。
MW2_KILLSTREAKS_PREDATOR_MISSILE=プレデターミサイル
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=遠隔操作式ミサイルを発射する。
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=ヘリガンナー
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=攻撃ヘリのガンナー役を務める。
MW2_KILLSTREAKS_HELICOPTER_MK19=ヘリガンナー
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=ヘリのグレネードランチャーを\n遠隔操作する。
MW2_KILLSTREAKS_DOUBLE_UAV=新型UAV
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=レーダー走査周期の速いUAV。
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=精密爆撃
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=方向指定の航空支援を要請する。
MW2_KILLSTREAKS_AIRDROP=救援物資
MW2_KILLSTREAKS_AIRDROP_DESC=弾薬やキルストリークを投下。
MW2_KILLSTREAKS_AIRDROP_SENTRY=自動機銃
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=設置可能な自動機銃を投下する。
MW2_KILLSTREAKS_AIRDROP_PREDATOR=救援物資（プレデター）
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=プレデターミサイルを投下する。
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=ハリアー攻撃
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=ハリアーの航空支援を要請する。
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=ステルス爆撃機
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=敵マップに表示されない\nステルス爆撃を要請する。
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=高威力の空爆
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=威力の高い航空支援。
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=ヘリコプター（ブラックボックス）
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=効果時間の長いヘリ。
MW2_KILLSTREAKS_HELICOPTER_FLARES=防御型ヘリ
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=フレアーを装備したヘリ。
MW2_KILLSTREAKS_EMP=EMP
MW2_KILLSTREAKS_EMP_DESC=敵の電子機器を一時的に使用不能\nにする。
MW2_KILLSTREAKS_TANK=戦車支援
MW2_KILLSTREAKS_TANK_DESC=戦車に支援を要請。
MW2_KILLSTREAKS_COUNTER_UAV=カウンターUAV
MW2_KILLSTREAKS_COUNTER_UAV_DESC=敵レーダーを一時的に使用不能化。
MW2_KILLSTREAKS_PAVELOW=ペイブロウ
MW2_KILLSTREAKS_PAVELOW_DESC=重装甲の襲撃ヘリを要請する。
MW2_KILLSTREAKS_NONE=なし
MW2_KILLSTREAKS_NONE_DESC=キルストリークが選択されていない。
MW2_KILLSTREAKS_AIRDROP_MEGA=緊急空中投下
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=キルストリークや弾薬をランダムに\n4回分空中投下する。
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=actionslot 4}]で緊急空中投下を行う。\n
MW2_KILLSTREAKS_TACTICAL_NUKE=戦術爆撃
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=とどめの一撃をお見舞いする。
MW2_KILLSTREAKS_SENTRY=自動機銃
  
MP_EARNED_AIRSTRIKE=%s空爆
MP_EARNED_AIRDROP=%s空中投下
MP_EARNED_SENTRY_AIRDROP=%s自動機銃投下
MP_EARNED_PREDATOR_AIRDROP=%sプレデターによる空中投下
MP_EARNED_PRECISION_AIRSTRIKE=%s精密爆撃
MP_EARNED_STEALTH_AIRSTRIKE=%sステルス爆撃機
MP_EARNED_HARRIER_AIRSTRIKE=%sハリアー空爆
MP_EARNED_SUPER_AIRSTRIKE=%s高威力空爆
MP_EARNED_UAV=%sUAV
MP_EARNED_DOUBLE_UAV=%s新型UAV
MP_EARNED_COUNTER_UAV=%sカウンターUAV
MP_EARNED_HELICOPTER=%s攻撃ヘリ
MP_EARNED_HELICOPTER_MINIGUN=%sヘリ機銃掃射
MP_EARNED_HELICOPTER_MK19=%sヘリMK19\n攻撃
MP_EARNED_HELICOPTER_BLACKBOX=%sブラック\nボックス
MP_EARNED_HELICOPTER_FLARES=%sペイブロウ
MP_EARNED_AC130=%sAC-130
MP_EARNED_PREDATOR_MISSILE=%sプレデター
MP_EARNED_NUKE=%s戦術爆撃
MP_EARNED_AUTO_SHOTGUN=%sショットガン
MP_EARNED_AUTO_SENTRY=%s自動警戒\nシステム
MP_EARNED_AUTO_SENTRY_GL=%s自動グレネード\nランチャー
MP_EARNED_THUMPER=%sThumper
MP_EARNED_LITTLEBIRD_SUPPORT=%sリトルバード
MP_EARNED_EMP=%sEMP

# Other
MW2_MP_CONNECTED=%sが接続
MW2_MP_DISCONNECTED=%s切断中
MW2_EXE_LEFTGAME=%sがゲームから退出

MW2_PLATFORM_RELOAD=リロード
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=残弾少
MW2_WEAPON_NO_AMMO=残弾なし

MW2_MPUI_WINNING_CAPS=優勢
MW2_MPUI_LOSING_CAPS=劣勢
MW2_MPUI_TIED_CAPS=引き分け

MW2_CGAME_SB_SCORE=スコア
MW2_CGAME_SB_DEATHS=死亡
MW2_CGAME_SB_KILLS=キル
MW2_CGAME_SB_ASSISTS=支援
  
# Round Starter
MW2_MP_MATCH_STARTING_IN=マッチ開始まで：
MW2_MP_MATCH_RESUMING_IN=マッチ再開まで：

# Gamemodes
MW2_MPUI_SABOTAGE=サボタージュ
MW2_MPUI_DEATHMATCH=フリー・フォー・オール
MW2_MPUI_CAPTURE_THE_FLAG=キャプチャー・ザ・フラッグ
MW2_MPUI_HEADQUARTERS=ヘッドクォーター
MW2_MPUI_SEARCH_AND_DESTROY=サーチ＆デストロイ
MW2_MPUI_WAR=チームデスマッチ
MW2_MPUI_DOMINATION=ドミネーション
MW2_MPUI_ONE_FLAG=ワンフラッグCTF
MW2_MPUI_ARENA=アリーナ
MW2_MPUI_DD=デモリッション
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=全面絶滅戦争

MW2_MP_OBJ_DM_HINT=他のプレイヤーを殲滅しろ。
MW2_MP_OBJ_WAR_HINT=敵プレイヤーの殲滅
MW2_OBJECTIVES_WAR_HINT=敵プレイヤーを殲滅しろ。
MW2_OBJECTIVES_SD_ATTACKER_HINT=目標AもしくはBを破壊しろ。
MW2_OBJECTIVES_SD_DEFENDER_HINT=目標AおよびBを防衛しろ。
MW2_OBJECTIVES_SAB_HINT=敵の目標を破壊しろ。
MW2_OBJECTIVES_DOM_HINT=フラッグを奪取したうえで守り抜け。
MW2_OBJECTIVES_DM_HINT=他のプレイヤーを殲滅しろ。
MW2_OBJECTIVES_KOTH_HINT=司令部を防衛しろ。
MW2_OBJECTIVES_CTF_HINT=敵のフラッグを奪取しろ。
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=敵のフラッグを奪取しろ。
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=フラッグを防衛しろ。
MW2_OBJECTIVES_DD_ATTACKER_HINT=目標AおよびBを破壊しろ。
MW2_OBJECTIVES_DD_DEFENDER_HINT=目標AおよびBを防衛しろ。
MW2_OBJECTIVES_VIP_ATTACKER_HINT=VIPが回収地点に到達する前に暗殺しろ。
MW2_OBJECTIVES_VIP_DEFENDER_HINT=VIPを護衛し、回収地点に到達させろ。
MW2_OBJECTIVES_ARENA_HINT=敵を全滅させるか、フラッグを奪取せよ
MW2_OBJECTIVES_GTNW_HINT=戦術爆撃を確保しろ。
MW2_OBJECTIVES_GRAB_FLAG_HINT=敵のフラッグを奪取しろ。

# Round Ender
MW2_MP_DRAW=引き分け
MW2_MP_VICTORY=勝利！
MW2_MP_DEFEAT=敗北！
MW2_MP_ROUND_DRAW=ラウンド引き分け
MW2_MP_ROUND_WIN=ラウンド勝利
MW2_MP_ROUND_LOSS=ラウンド敗北
MW2_MP_HALFTIME=ハーフタイム
MW2_MP_OVERTIME=延長戦
MW2_MP_MATCH_BONUS_IS=マッチボーナス：%s

MW2_MP_SCORE_LIMIT_REACHED=スコアリミットに到達
MW2_MP_ROUND_LIMIT_REACHED=ラウンドリミットに到達
MW2_MP_TIME_LIMIT_REACHED=タイムリミット

MW2_MP_OPFOR_ELIMINATED=対抗部隊が壊滅
MW2_MP_OPFOR_FORFEITED=対抗部隊にペナルティ
MW2_MP_SPETSNAZ_ELIMINATED=スペツナズが壊滅
MW2_MP_SPETSNAZ_FORFEITED=スペツナズにペナルティ
MW2_MP_US_ARMY_ELIMINATED=陸軍レンジャー部隊が壊滅
MW2_MP_US_ARMY_FORFEITED=陸軍レンジャー部隊にペナルティ
MW2_MP_MILITIA_ELIMINATED=民兵が壊滅
MW2_MP_MILITIA_FORFEITED=民兵にペナルティ
MW2_MP_TF141_ELIMINATED=TF141が壊滅
MW2_MP_TF141_FORFEITED=TF141にペナルティ
MW2_MP_SEALS_ELIMINATED=SEALsが壊滅
MW2_MP_SEALS_FORFEITED=SEALsにペナルティ