#---------- CoD HUD Settings | Turkish
# Translator: Claude (TR Localization)

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=İstemci Ayarları
CoDHUD.Server=Sunucu Ayarları

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.Admin.RoundStart=Raund Başlat

CoDHUD.RoundStart.Gamemode=Oyun Modu Seç
CoDHUD.RoundStart.Start=Raund Başlatma İşlemini Yürüt
CoDHUD.RoundStart.Admin=Bu işlem yalnızca Admin'e özeldir!

CoDHUD.RoundStart.Notice=Yeni bir raund başlatmak istediğine emin misin?\nTüm skorlar sıfırlanacak ve tüm oyuncular yeniden doğacak.
CoDHUD.RoundStart.Yes=Başlat
CoDHUD.RoundStart.No=Vazgeç

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen="Maç Sonu" Ekranını Aç
CoDHUD.Admin.EndScreen.desc=Skor limitine ulaşıldığında "maç sonu" sistemini devreye sokar.

CoDHUD.Admin.EndScreen.StartNext=Maç Sonu'nun ardından Yeni Raund Başlasın
CoDHUD.Admin.EndScreen.StartNext.desc=Açıksa, maç sonu süresi dolduğunda yeni bir raund başlar.\nKapalıysa, oyuncular normal şekilde yeniden doğar.

CoDHUD.Admin.EndScreen.Scorelimit=Skor Limiti
CoDHUD.Admin.EndScreen.Scorelimit.desc=Skor sayacındaki maksimum skor limitini belirler.

# MW2HUD.Admin.FriendlyFire=Allow Friendly Fire
# MW2HUD.Admin.FriendlyFire.desc=If enabled, players on the same faction can damage one another.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Takımları ve HUD Tipini Kısıtla
CoDHUD.Admin.RestrictType.desc=Oyuncuların hangi CoD tipiyle sınırlandırılacağını seç.\n'Serbest' seçilirse, herkes her takımı ve her HUD tipini kullanabilir.

CoDHUD.Type.Open=Serbest
CoDHUD.Type.CoD4=Call of Duty 4: Modern Warfare
CoDHUD.Type.WaW=Call of Duty: World at War
CoDHUD.Type.MW2=Call of Duty: Modern Warfare 2
CoDHUD.Type.BO=Call of Duty: Black Ops
CoDHUD.Type.MW3=Call of Duty: Modern Warfare 3
CoDHUD.Type.BO2=Call of Duty: Black Ops II

CoDHUD.Type.Open.desc=Oyuncuların herhangi bir CoD oyunundan takım ve HUD tipi seçmesine izin ver.
CoDHUD.Type.Closed.desc=Oyuncuları yalnızca seçilen CoD oyununun takımlarıyla ve HUD tipiyle kısıtla.

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Takım Seç
CoDHUD.Faction.Select.desc=Hangi takımı temsil edeceğini seç.\nDost-düşman durumunu etkiler; spikerini ve müziğini takımına göre değiştirir.
CoDHUD.Faction.SelectAgain=Takımını Spawnmenu > CoD HUD > Takım Seç üzerinden değiştirebilirsin; ya da bağlam menüsünden (Context Menu) "CoD HUD" seçeneğine tıklayabilirsin.

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Hızlı Erişim

CoDHUD.Quick.DisableHUD=Tüm HUD Seçeneklerini Anında Kapat
CoDHUD.Quick.DisableHUD.desc=Tüm CoD HUD seçeneklerini devre dışı bırakır.

CoDHUD.Quick.DisableAudio=Tüm Ses Seçeneklerini Anında Kapat
CoDHUD.Quick.DisableAudio.desc=Tüm CoD ses seçeneklerini devre dışı bırakır.

# ---------[ AUDIO-RELATED ]---------
CoDHUD.Audio=Ses Ayarları
CoDHUD.Audio.Announcer=Spiker
CoDHUD.Audio.Music=Müzik

CoDHUD.Audio.Announcer.Enable=Spiker Sesini Aç
CoDHUD.Audio.Announcer.Enable.desc=Spikeri etkinleştirir.

CoDHUD.Audio.Announcer.English=İngilizce Spikeri Zorla
CoDHUD.Audio.Announcer.English.desc=Oyun dili ne olursa olsun spikerin İngilizce seslerini oynatır.

CoDHUD.Audio.Music.Enable=Müziği Aç
CoDHUD.Audio.Music.Enable.desc=Müziği etkinleştirir.

CoDHUD.Audio.Music.Ambient=Ortam Müziğini Aç
CoDHUD.Audio.Music.Ambient.desc=Arka planda çalan ortam müziğini etkinleştirir.

# ---------[ HUD-RELATED ]---------
CoDHUD.Enable.Options=HUD Ayarları

# Multiple
CoDHUD.HUD.Outline=Konturlu Yazı
CoDHUD.HUD.Outline.desc=Bazı öğelerin yazılarına kontur ekler; aşırı aydınlık sahnelerde okumayı kolaylaştırır.

CoDHUD.HUD.Sound=Ses Efektlerini Çal
CoDHUD.HUD.Sound.desc=HUD Tipi destekliyorsa, ilgili ses efektlerini çalar.

CoDHUD.HUD.Time.Total=Ekranda Kalma Süresi
CoDHUD.HUD.Time.Total.desc=Öğe tamamen belirdikten sonra, kaybolmaya başlamadan önce ekranda kalma süresi.

CoDHUD.HUD.Time.Fadein=Belirme Süresi
CoDHUD.HUD.Time.Fadein.desc=Bu öğenin ekranda belirme süresi.

CoDHUD.HUD.Time.Fadeout=Kaybolma Süresi
CoDHUD.HUD.Time.Fadeout.desc=Bu öğenin ekrandan kaybolma süresi.

# Scoreboard
CoDHUD.HUD.Scoreboard=Skor Tablosu

CoDHUD.HUD.Scoreboard.Enable=Skor Tablosunu Aç
CoDHUD.HUD.Scoreboard.Enable.desc=Temalı skor tablosunu açar. Oyuncuların bulunduğu takımları listeler.

# Score Counter
CoDHUD.HUD.Scorecounter=Skor Sayacı

CoDHUD.HUD.Scorecounter.Enable=Skor Sayacını Aç
CoDHUD.HUD.Scorecounter.Enable.desc=Temalı sunucu zamanlayıcısını, takım ikonunu ve skor sayaçlarını açar.\nBazı HUD tiplerinde takım ikonu gösterilmez.

# Medals
CoDHUD.HUD.Medals=Madalyalar

CoDHUD.HUD.Medals.Enable=Madalyaları Aç
CoDHUD.HUD.Medals.Enable.desc=Belirli aksiyonlarla (hızlı öldürme, kafadan atış vs.) kazanılan temalı madalyaları açar.\nİlgili ses efektlerini de devreye sokar.\nBazı HUD tiplerinde sadece yazı, bazılarında yazı ve ikon gözükür.

CoDHUD.HUD.Medals.Speedup=Sıra Uzunsa Hızlandır
CoDHUD.HUD.Medals.Speedup.desc=Aynı anda birden çok madalya birikirse sırayı hızlandırır.\nHUD Tipine göre, 3'ten fazla madalya sırada bekliyorsa ses efektlerini de devre dışı bırakır.

# Kill Feed
CoDHUD.HUD.Options.Killfeed=Öldürme Akışı

CoDHUD.HUD.Killfeed.Enable=Öldürme Akışını Aç
CoDHUD.HUD.Killfeed.Enable.desc=Temalı öldürme akışını (kill feed) açar.

# Minimap
CoDHUD.HUD.Minimap=Mini Harita

CoDHUD.HUD.Minimap.Enable=Mini Haritayı Aç
CoDHUD.HUD.Minimap.Enable.desc=Temalı mini haritayı açar.

# Hitmarker
CoDHUD.HUD.Hitmarker=İsabet İşareti

CoDHUD.HUD.Hitmarker.Enable=İsabet İşaretini Aç
CoDHUD.HUD.Hitmarker.Enable.desc=Temalı isabet işaretini (hitmarker) ve ses efektini açar.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Silah Bilgisi

CoDHUD.HUD.WeaponInfo.Enable=Silah Bilgisini Aç
CoDHUD.HUD.WeaponInfo.Enable.desc=Silah adını ve mermi sayacını gösteren temalı silah panelini açar.\nBazı HUD tiplerinde pusula da buraya entegredir.

CoDHUD.HUD.WeaponPrompts.Enable=Silah Uyarılarını Aç
CoDHUD.HUD.WeaponPrompts.Enable.desc=Düşük mermi bildirimi gibi temalı silah uyarılarını açar.

# XP Counter
CoDHUD.HUD.XP=XP Bildirimi

CoDHUD.HUD.XP.Enable=XP Bildirimini Aç
CoDHUD.HUD.XP.Enable.desc=Temalı XP bildirimini açar.

# Target ID / IFF
CoDHUD.HUD.IFF=Dost-Düşman Tanımlama

CoDHUD.HUD.IFF.Enable=Dost-Düşman Tanımlamayı Aç
CoDHUD.HUD.IFF.Enable.desc=Temalı "Dost-Düşman Tanımlama" sistemini açar; hedefin yakınına nişan aldığında adını başının üstünde gösterir.

# Death Icon
CoDHUD.HUD.DeathIcon=Ölüm İkonu

CoDHUD.HUD.DeathIcon.Enable=Ölüm İkonunu Aç
CoDHUD.HUD.DeathIcon.Enable.desc=Aynı takımdan bir oyuncu öldüğünde o konumda beliren ölüm ikonunu açar.

# Chat
CoDHUD.HUD.Chat=Sohbet

CoDHUD.HUD.Chat.Enable=Sohbeti Aç
CoDHUD.HUD.Chat.Enable.desc=Temalı sohbeti açar.

# Challenges
CoDHUD.HUD.Challenges=Görevler

CoDHUD.HUD.Challenges.Enable=Görev Bildirimlerini Aç
CoDHUD.HUD.Challenges.Enable.desc=Temalı görev bildirimlerini açar.\nGörevlerin takibini ya da açılmasını etkilemez.
