#---------- MW2 HUD | Turkish
# Translator: Claude (TR Localization)

# Factions
MW2_MP_US_ARMY_NAME=Army Rangers
MW2_MP_SEALS_UDT_NAME=Navy SEALs
MW2_MP_MILITIA_NAME=Milis Kuvvetleri
MW2_MP_TASKFORCE_NAME=Task Force 141
MW2_MP_OPFOR_NAME=OpFor
MW2_MP_SPETSNAZ_NAME=Spetsnaz

MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_SEALS_UDT_SHORT_NAME=SEALs
MW2_MP_MILITIA_SHORT_NAME=Milis
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_OPFOR_SHORT=OpFor
MW2_MPUI_SPETSNAZ_SHORT=Spetsnaz

# Splashes
MW2_SPLASHES_HEADSHOT=Kafadan!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=İntihara Yardım!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Bir düşmanın kendini öldürmesine yardım ettin.
MW2_SPLASHES_LONGSHOT=Uzak Mesafe!
MW2_SPLASHES_LONGSHOT_DESC=Uzaktan güzel bir iş çıkardın!
MW2_SPLASHES_EXECUTION=İnfaz!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=İntikamcı!
MW2_SPLASHES_AVENGER_DESC=Takım arkadaşının intikamını aldın.
MW2_SPLASHES_DEFENDER=Kurtarıcı!
MW2_SPLASHES_DEFENDER_DESC=Bir takım arkadaşını kurtardın.
MW2_SPLASHES_POSTHUMOUS=Öbür Dünyadan!
MW2_SPLASHES_POSTHUMOUS_DESC=Öldükten sonra bir düşmanı alt ettin.
MW2_SPLASHES_REVENGE=Rövanş!
MW2_SPLASHES_REVENGE_DESC=İntikamını aldın.
MW2_SPLASHES_DOUBLEKILL=Çifte Kıyım!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Üçlü Kıyım!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Çoklu Kıyım!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=İlk Kan!
MW2_SPLASHES_FIRSTBLOOD_DESC=İlk öldürme senindi.
MW2_SPLASHES_BUZZKILL=Keyif Kaçıran!
MW2_SPLASHES_BUZZKILL_DESC=Düşmanın öldürme serisini bozdun.
MW2_SPLASHES_COMEBACK=Geri Dönüş!
MW2_SPLASHES_COMEBACK_DESC=Üst üste ölmekten kendini topladın.
MW2_SPLASHES_FLAGRETURN=Bayrak İade!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Bayrak Taşıyıcı!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Mevzi Güvende!
MW2_SPLASHES_CAPTURE_DESC=Hedefi ele geçirdin.
MW2_SPLASHES_DEFEND=Savunma!
MW2_SPLASHES_DEFEND_DESC=Hedefi başarıyla savundun.
MW2_SPLASHES_ASSAULT=Saldırı!
MW2_SPLASHES_ASSAULT_DESC=Bir savunucuyu alt ettin.
MW2_SPLASHES_PLANT=Sabotajcı!
MW2_SPLASHES_PLANT_DESC=Bombayı yerleştirdin.
MW2_SPLASHES_DEFUSE=Kahraman!
MW2_SPLASHES_DEFUSE_DESC=Bombayı etkisiz hale getirdin.
MW2_SPLASHES_SAB_OVERTIME=Uzatma!
MW2_SPLASHES_SAB_OVERTIME_DESC=Bombaya en yakın üs yok edilecek.
MW2_SPLASHES_MARTYRDOM_DESC=Öldüğünde yanındaki bombayı düşüreceksin.
MW2_SPLASHES_FINALSTAND_DESC=Yere düştüğünde ikinci bir şansın olacak.
MW2_SPLASHES_ENDGAME_DESC=Birkaç saniyeliğine ekstra canın var.
MW2_SPLASHES_C4DEATH_DESC=Ölmeden önce C4'ü eline al.
MW2_SPLASHES_KNIFETHROW_DESC=Bir düşmanı fırlatma bıçağıyla alt ettin.
MW2_SPLASHES_KNIFETHROW=Onikiden!
MW2_SPLASHES_HIJACKER_DESC=Düşmanın erzak sandığını ele geçirdin.
MW2_SPLASHES_HIJACKER=Gaspçı!
MW2_SPLASHES_HIJACKED=%s senin erzak sandığını aldı.
MW2_SPLASHES_DEFCON_LOWER=DEFCON Düştü!
MW2_SPLASHES_DEFCON_RAISE=DEFCON Yükseldi
MW2_SPLASHES_DEFCON_LOWER_DESC=Öldürme serileri geliştirildi!
MW2_SPLASHES_DEFCON_RAISE_DESC=Öldürme serileri zayıfladı.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Maç başlıyor!
MW2_SPLASHES_DEFCON_3_DESC=Acil havadan erzak geliyor!
MW2_SPLASHES_DEFCON_2_DESC=Öldürme serileri devrediyor!
MW2_SPLASHES_DEFCON_1_DESC=Hedef puanları iki katına!
MW2_SPLASHES_COMBATHIGH_DESC=Kısa süreliğine artırılmış can.
MW2_SPLASHES_RESTED=Günlük XP Bonusu!
MW2_SPLASHES_RESTED_DESC=Günlük bonus XP'ni topluyorsun!
MW2_SPLASHES_RESTED_DONE=Günlük XP Bonusu Bitti.
MW2_SPLASHES_RESTED_DONE_DESC=Bonus XP kazanıldı.
MW2_SPLASHES_VIP=Sen VIP'sin
MW2_SPLASHES_STUCK_SEMTEX=Yapıştı!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Düşmana Semtex yapıştırdın!
MW2_SPLASHES_HEROIC=Destansı!
MW2_SPLASHES_HEROIC_DESC=Son anında hedefi ele geçirdin!
MW2_SPLASHES_DENIED=Reddedildi!
MW2_SPLASHES_DENIED_DESC=Düşmanın taktiksel doğum noktasını yok ettin!
MW2_SPLASHES_DESTROYED_INSERTION=Doğum noktanı bloke etti!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Erzak sandığını çaldı!
MW2_SPLASHES_REVIVER_DESC=Düşen bir takım arkadaşını dirilttin.
MW2_SPLASHES_REVIVER=Dirilten!
MW2_SPLASHES_GIVEAWAY_SENTRY=...bir Sentry Gun aldı
MW2_SPLASHES_GIVEAWAY_AIRDROP=...havadan gelen bir öldürme ödülünü aldı.
MW2_SPLASHES_SEMTEX_STUCK=Sana Semtex yapıştırdı
MW2_SPLASHES_ONE_SHOT_KILL=Tek Atışta Ölüm
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Tek atış... tek ölüm
MW2_SPLASHES_NINJA_DEFUSE=Ninja Etkisizleştirme
MW2_SPLASHES_NINJA_DEFUSE_DESC=Sinsi ha sinsi...
MW2_SPLASHES_COPYCAT_DESC=Killcam sırasında katilinin sınıfını çal.
MW2_SPLASHES_COPIED=Sınıf kopyalandı!
MW2_SPLASHES_REVIVED=Seni diriltti
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Son Kalan Sensin!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Son Kalan Sensin!
MW2_SPLASHES_SHIELDASSIST=Dikkat Dağıtma!
MW2_SPLASHES_SHIELDASSIST_DESC=Harika bir yem oluyorsun.
MW2_SPLASHES_DESTROYED_HELICOPTER=Helikopter Düşürüldü!
MW2_SPLASHES_DESTROYED_PAVELOW=Pave Low Düşürüldü!
MW2_SPLASHES_DESTROYED_UAV=UAV Düşürüldü!
MW2_SPLASHES_DESTROYED_HARRIER=Harrier Düşürüldü!
MW2_SPLASHES_DESTROYED_AC130=AC130 Düşürüldü!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Gunship Düşürüldü!
MW2_SPLASHES_FLAG_RETURN=Bayrak İade Edildi!
MW2_SPLASHES_FLAG_CAPTURE=Bayrak Ele Geçirildi!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Bayrağını Aldı!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Düşman Bayrağını Aldı!
MW2_SPLASHES_FLAG_PICKUP=Bayrağı Aldı!
MW2_SPLASHES_CAPTURED_NUKE=Nükleer Ele Geçirildi!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Nükleeri ele geçirdin.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Genişletilmiş Şarjör açıldı!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Kalp Atışı Sensörü açıldı!
MW2_SPLASHES_UNLOCKED_AKIMBO=Çift Silah (Akimbo) açıldı!
MW2_SPLASHES_UNLOCKED_THERMAL=Termal Dürbün açıldı!
MW2_SPLASHES_UNLOCKED_EOTECH=Holografik Nişangah açıldı!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Pompalı Tüfek açıldı!
MW2_SPLASHES_GRABBED_THE_FLAG=Bayrağı kaptı!
MW2_SPLASHES_HIJACKED_SENTRY=Sentry'ni Çaldı!
MW2_SPLASHES_HIJACKED_AIRDROP=Sandığını Çaldı!
MW2_SPLASHES_BOMB_PLANTED=Bomba Yerleştirildi!
MW2_SPLASHES_BOMB_DEFUSED=Bomba Etkisiz Hale Getirildi!
MW2_SPLASHES_TIMEADDED=Süre Eklendi!
MW2_SPLASHES_GTNW_OVERTIME=Ani Ölüm!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Yeniden doğum yok.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Hedef Yok Edildi!
MW2_SPLASHES_SAVED_OBJECTIVE=Hedef Kurtarıldı!
MW2_SPLASHES_CAPTURED_HQ=Karargah Ele Geçirildi!
MW2_SPLASHES_DESTROYED_HQ=Karargah Yok Edildi!
MW2_SPLASHES_BOMB_TAKEN=Bomba Alındı!
MW2_SPLASHES_BOMB_DROPPED=Bomba Düşürüldü!
MW2_SPLASHES_KILLED_CARRIER=Bomba Taşıyıcısı Öldürüldü!
MW2_SPLASHES_SHAREPACKAGE=Paylaşılan Paket!
MW2_SPLASHES_SHAREPACKAGE_DESC=Bir takım arkadaşın Erzak Sandığını düşmandan kurtardı!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=UAV Geri Döndü!
MW2_SPLASHES_FLAGS_CAPTURE=Bayrak Ele Geçirildi!
MW2_SPLASHES_FLAG_ASSAULT=Bayrak Saldırısı!
MW2_SPLASHES_FLAG_DEFEND=Bayrak Savunması!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Bir bayrak savunucusunu alt ettin.
MW2_SPLASHES_FLAG_DEFEND_DESC=Bayrağı savundun.
MW2_SPLASHES_FLAG_CAPTURED=Bayrak Ele Geçirildi!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Düşman bayrağını ele geçirdin.
MW2_SPLASHES_SECURED_POSITION=Mevzi Alındı!
MW2_SPLASHES_SECURED_POSITION_A=A Mevzisi Alındı!
MW2_SPLASHES_SECURED_POSITION_B=B Mevzisi Alındı!
MW2_SPLASHES_SECURED_POSITION_C=C Mevzisi Alındı!
MW2_SPLASHES_TIME_ADDED=Ek Süre!
MW2_SPLASHES_TIME_ADDED_DESC=Bomba noktası yok edildi. Oyun süresi uzatıldı.

# Other
MW2_MP_CONNECTED=%s Bağlandı
MW2_MP_DISCONNECTED=%s Bağlantısı Kesildi
MW2_EXE_LEFTGAME=%s oyundan ayrıldı

MW2_PLATFORM_RELOAD=Şarjör Değiştir
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Az Mermi
MW2_WEAPON_NO_AMMO=Mermi Yok

MW2_MPUI_WINNING_CAPS=KAZANIYOR
MW2_MPUI_LOSING_CAPS=KAYBEDİYOR
MW2_MPUI_TIED_CAPS=BERABERE

MW2_CGAME_SB_SCORE=Skor
MW2_CGAME_SB_DEATHS=Ölüm
MW2_CGAME_SB_KILLS=Öldürme
MW2_CGAME_SB_ASSISTS=Asist

MW2_PLATFORM_THROWBACKGRENADE=Geri at: %s

# Round Starter
MW2_MP_MATCH_STARTING_IN=Maç başlıyor:
MW2_MP_MATCH_RESUMING_IN=Maç devam ediyor:

# Gamemodes
MW2_MPUI_SABOTAGE=Sabotaj
MW2_MPUI_DEATHMATCH=Herkes Kendine
MW2_MPUI_CAPTURE_THE_FLAG=Bayrağı Ele Geçir
MW2_MPUI_HEADQUARTERS=Karargah
MW2_MPUI_SEARCH_AND_DESTROY=Bul ve Yok Et
MW2_MPUI_WAR=Takım Ölüm Maçı
MW2_MPUI_DOMINATION=Hakimiyet
MW2_MPUI_ONE_FLAG=Tek Bayrak CTF
MW2_MPUI_ARENA=Arena
MW2_MPUI_DD=Demolition
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Küresel Termonükleer Savaş

MW2_MP_OBJ_DM_HINT=Diğer oyuncuları elimine et.
MW2_MP_OBJ_WAR_HINT=Düşman oyuncuları elimine et.
MW2_OBJECTIVES_WAR_HINT=Düşman oyuncuları elimine et.
MW2_OBJECTIVES_SD_ATTACKER_HINT=A veya B hedefini yok et.
MW2_OBJECTIVES_SD_DEFENDER_HINT=A ve B hedeflerini koru.
MW2_OBJECTIVES_SAB_HINT=Düşman hedefini yok et.
MW2_OBJECTIVES_DOM_HINT=Bayrakları ele geçir ve savun.
MW2_OBJECTIVES_DM_HINT=Diğer oyuncuları elimine et.
MW2_OBJECTIVES_KOTH_HINT=Karargahı elinde tut.
MW2_OBJECTIVES_CTF_HINT=Düşman bayrağını ele geçir.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Düşman bayrağını ele geçir.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Bayrağı savun.
MW2_OBJECTIVES_DD_ATTACKER_HINT=A ve B hedeflerini yok et.
MW2_OBJECTIVES_DD_DEFENDER_HINT=A ve B hedeflerini koru.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=VIP'yi öldür; tahliye noktasına ulaşmasını engelle.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=VIP'yi koru; tahliye noktasına ulaşmasına yardım et.
MW2_OBJECTIVES_ARENA_HINT=Düşmanı elimine et ya da bayrağı ele geçir.
MW2_OBJECTIVES_GTNW_HINT=Nükleeri ele geçir.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Düşman bayrağını kap.

# Round Ender
MW2_MP_DRAW=Berabere
MW2_MP_VICTORY=Zafer!
MW2_MP_DEFEAT=Yenilgi!
MW2_MP_ROUND_DRAW=Raund Berabere
MW2_MP_ROUND_WIN=Raund Galibiyeti
MW2_MP_ROUND_LOSS=Raund Yenilgisi
MW2_MP_HALFTIME=Devre Arası
MW2_MP_OVERTIME=Uzatma
MW2_MP_MATCH_BONUS_IS=Maç Bonusu: %s

MW2_MP_SCORE_LIMIT_REACHED=Skor limitine ulaşıldı
MW2_MP_ROUND_LIMIT_REACHED=Raund limitine ulaşıldı
MW2_MP_TIME_LIMIT_REACHED=Süre limitine ulaşıldı