#---------- MW2 HUD | Polska | Polish
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Rangersi US Army
MW2_MP_SEALS_UDT_NAME=Navy SEAL
MW2_MP_MILITIA_NAME=Milicja
MW2_MP_TASKFORCE_NAME=Zespół specjalny 141
MW2_MP_OPFOR_NAME=Przeciwnik
MW2_MP_SPETSNAZ_NAME=Specnaz

MW2_MP_US_ARMY_SHORT_NAME=Rangersi
MW2_MP_SEALS_UDT_SHORT_NAME=SEAL
MW2_MP_MILITIA_SHORT_NAME=Milicja
MW2_MP_TASKFORCE_SHORT_NAME=ZS 141
MW2_MPUI_OPFOR_SHORT=Przeciwnik
MW2_MPUI_SPETSNAZ_SHORT=Specnaz

# Splashes
MW2_SPLASHES_HEADSHOT=Trafienie w głowę!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Asysta przy samobójstwie!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Asystowałeś przy samobójstwie nieprzyjaciela.
MW2_SPLASHES_LONGSHOT=Daleki strzał!
MW2_SPLASHES_LONGSHOT_DESC=Piękne trafienie z dystansu!
MW2_SPLASHES_EXECUTION=Egzekucja!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Mściciel!
MW2_SPLASHES_AVENGER_DESC=Pomściłeś członka drużyny.
MW2_SPLASHES_DEFENDER=Ratownik!
MW2_SPLASHES_DEFENDER_DESC=Udało ci się uratować członka drużyny.
MW2_SPLASHES_POSTHUMOUS=Życie po śmierci!
MW2_SPLASHES_POSTHUMOUS_DESC=Zabiłeś nieprzyjaciela po swojej śmierci.
MW2_SPLASHES_REVENGE=Zapłata!
MW2_SPLASHES_REVENGE_DESC=Zemściłeś się.
MW2_SPLASHES_DOUBLEKILL=Podwójne zabicie!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Potrójne zabicie!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Wiele ofiar!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Pierwsza krew!
MW2_SPLASHES_FIRSTBLOOD_DESC=Pierwszy zabiłeś nieprzyjaciela.
MW2_SPLASHES_BUZZKILL=Zabójca!
MW2_SPLASHES_BUZZKILL_DESC=Zatrzymałeś nieprzyjaciela przed osiągnięciem serii ofiar.
MW2_SPLASHES_COMEBACK=Powrót!
MW2_SPLASHES_COMEBACK_DESC=Udało ci się odzyskać siły po serii śmierci.
MW2_SPLASHES_FLAGRETURN=Flaga zwrócona!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Uciekinier z flagą!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Pozycja zabezpieczona!
MW2_SPLASHES_CAPTURE_DESC=Zająłeś cel.
MW2_SPLASHES_DEFEND=Obrona!
MW2_SPLASHES_DEFEND_DESC=Udało ci się obronić cel.
MW2_SPLASHES_ASSAULT=Atak!
MW2_SPLASHES_ASSAULT_DESC=Zabiłeś obrońcę.
MW2_SPLASHES_PLANT=Sabotażysta!
MW2_SPLASHES_PLANT_DESC=Podłożyłeś bombę.
MW2_SPLASHES_DEFUSE=Bohater!
MW2_SPLASHES_DEFUSE_DESC=Rozbroiłeś bombę.
MW2_SPLASHES_SAB_OVERTIME=Dodatkowy czas!
MW2_SPLASHES_SAB_OVERTIME_DESC=Baza znajdująca się najbliżej bomby zostanie zniszczona.
MW2_SPLASHES_MARTYRDOM_DESC=Gdy będziesz umierał, rzucisz odbezpieczony granat.
MW2_SPLASHES_FINALSTAND_DESC=Przed śmiercią masz jeszcze jedną szansę.
MW2_SPLASHES_ENDGAME_DESC=Przez kilka sekund poziom zdrowia twojej postaci jest zwiększony.
MW2_SPLASHES_C4DEATH_DESC=Wyciągnij C4, zanim zginiesz.
MW2_SPLASHES_KNIFETHROW_DESC=Zabiłeś nieprzyjaciela, rzucając w niego nożem.
MW2_SPLASHES_KNIFETHROW=W dziesiątkę!
MW2_SPLASHES_HIJACKER_DESC=Zdobyłeś skrzynkę z zapasami nieprzyjaciela.
MW2_SPLASHES_HIJACKER=Porywacz!
MW2_SPLASHES_HIJACKED=%s przejął twoją skrzynkę z zapasami.
MW2_SPLASHES_DEFCON_LOWER=DEFCON obniżony!
MW2_SPLASHES_DEFCON_RAISE=DEFCON podwyższony!
MW2_SPLASHES_DEFCON_LOWER_DESC=Seria ofiar ulepszona!
MW2_SPLASHES_DEFCON_RAISE_DESC=Seria ofiar obniżona.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Rozpoczęcie meczu!
MW2_SPLASHES_DEFCON_3_DESC=Nadciąga zrzut awaryjny!
MW2_SPLASHES_DEFCON_2_DESC=Przebicie serii ofiar!
MW2_SPLASHES_DEFCON_1_DESC=Podwójne punkty za cele!
MW2_SPLASHES_COMBATHIGH_DESC=Tymczasowo zwiększony poziom zdrowia.
MW2_SPLASHES_RESTED=Dzienny dodatek do PD!
MW2_SPLASHES_RESTED_DESC=Zdobądź dzienny dodatek do PD!
MW2_SPLASHES_RESTED_DONE=Dzienny dodatek do PD zakończony.
MW2_SPLASHES_RESTED_DONE_DESC=Uzyskano dodatkowe PD.
MW2_SPLASHES_VIP=Jesteś VIP-em
MW2_SPLASHES_STUCK_SEMTEX=Unieruchomiony!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Unieruchomiłeś wroga semteksem!
MW2_SPLASHES_HEROIC=Bohatersko!
MW2_SPLASHES_HEROIC_DESC=Zająłeś cel w ostatnim punkcie oporu!
MW2_SPLASHES_DENIED=Obroniono!
MW2_SPLASHES_DENIED_DESC=Zniszczyłeś taktyczny zrzut przeciwnika!
MW2_SPLASHES_DESTROYED_INSERTION=Zablokował twój zrzut taktyczny!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Zabierz skrzynkę!
MW2_SPLASHES_REVIVER_DESC=Wyleczyłeś członka drużyny.
MW2_SPLASHES_REVIVER=Lekarz!
MW2_SPLASHES_GIVEAWAY_SENTRY=...zajął karabin strażniczy.
MW2_SPLASHES_GIVEAWAY_AIRDROP=...zajął zrzuconą serię ofiar.
MW2_SPLASHES_SEMTEX_STUCK=Unieruchomił cię semteksem
MW2_SPLASHES_ONE_SHOT_KILL=Jeden strzał zabija
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Jeden strzał... jedna ofiara
MW2_SPLASHES_NINJA_DEFUSE=Rozbrojenie w stylu ninja
MW2_SPLASHES_NINJA_DEFUSE_DESC=Podstępnie...
MW2_SPLASHES_COPYCAT_DESC=Ukradnij klasę zabójcy podczas kamery śmierci.
MW2_SPLASHES_COPIED=Klasa skopiowana!
MW2_SPLASHES_REVIVED=Wyleczył cię
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Jedyny ocalały!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Jedyny ocalały!
MW2_SPLASHES_SHIELDASSIST=Kontrola nad tłumem!
MW2_SPLASHES_SHIELDASSIST_DESC=Doskonale odwracasz uwagę.
MW2_SPLASHES_DESTROYED_HELICOPTER=Zniszczył śmigłowiec!
MW2_SPLASHES_DESTROYED_PAVELOW=Zniszczył Pave Lowa!
MW2_SPLASHES_DESTROYED_UAV=Zniszczył BSP!
MW2_SPLASHES_DESTROYED_HARRIER=Zniszczył Harriera!
MW2_SPLASHES_DESTROYED_AC130=Zniszczył AC130!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Zniszczył śmigłowiec szturmowy!
MW2_SPLASHES_FLAG_RETURN=Zwrócił flagę!
MW2_SPLASHES_FLAG_CAPTURE=Zdobył flagę!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Zabrał twoją flagę!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Zabrał flagę nieprzyjaciela!
MW2_SPLASHES_FLAG_PICKUP=Zabrał flagę!
MW2_SPLASHES_CAPTURED_NUKE=Przejęcie atomówki!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Udało ci się zdobyć atomówkę.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Odblokowano powiększony magazynek!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Odblokowano czujnik pulsu!
MW2_SPLASHES_UNLOCKED_AKIMBO=Odblokowano akimbo!
MW2_SPLASHES_UNLOCKED_THERMAL=Odblokowano celownik termowizyjny!
MW2_SPLASHES_UNLOCKED_EOTECH=Odblokowano celownik holograficzny!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Odblokowano strzelbę!
MW2_SPLASHES_GRABBED_THE_FLAG=Zabrał flagę!
MW2_SPLASHES_HIJACKED_SENTRY=Zabrał twoje działko strażnicze!
MW2_SPLASHES_HIJACKED_AIRDROP=Zabrał twój pakiet!
MW2_SPLASHES_BOMB_PLANTED=Podłożył bombę!
MW2_SPLASHES_BOMB_DEFUSED=Rozbroił bombę!
MW2_SPLASHES_TIMEADDED=Dodano więcej czasu!
MW2_SPLASHES_GTNW_OVERTIME=Nagła śmierć!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Bez odradzania.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Zniszczył cel!
MW2_SPLASHES_SAVED_OBJECTIVE=Ocalił cel!
MW2_SPLASHES_CAPTURED_HQ=Zajął sztab!
MW2_SPLASHES_DESTROYED_HQ=Zniszczył sztab!
MW2_SPLASHES_BOMB_TAKEN=Zabrał bombę!
MW2_SPLASHES_BOMB_DROPPED=Porzucił bombę!
MW2_SPLASHES_KILLED_CARRIER=Zabił niosącego bombę!
MW2_SPLASHES_SHAREPACKAGE=Podzielił pakiet!
MW2_SPLASHES_SHAREPACKAGE_DESC=Kolega z drużyny ocalił twój pakiet pomocy!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Przywrócił BSP!
MW2_SPLASHES_FLAGS_CAPTURE=Przejął flagę!
MW2_SPLASHES_FLAG_ASSAULT=Atak na flagę!
MW2_SPLASHES_FLAG_DEFEND=Flaga obroniona!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Zabiłeś obrońcę flagi.
MW2_SPLASHES_FLAG_DEFEND_DESC=Udało ci się obronić flagę.
MW2_SPLASHES_FLAG_CAPTURED=Flaga zdobyta!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Zabrałeś flagę nieprzyjaciela.
MW2_SPLASHES_SECURED_POSITION=Pozycja zabezpieczona!
MW2_SPLASHES_SECURED_POSITION_A=Zabezpieczono A!
MW2_SPLASHES_SECURED_POSITION_B=Zabezpieczono B!
MW2_SPLASHES_SECURED_POSITION_C=Zabezpieczono C!
MW2_SPLASHES_TIME_ADDED=Dodatkowy czas!
MW2_SPLASHES_TIME_ADDED_DESC=Cel zniszczony. Czas gry został wydłużony.

# Killstreaks
MW2_KILLSTREAKS_UAV=BSP
MW2_KILLSTREAKS_UAV_DESC=Pokazuje przeciwników na minimapie.
MW2_KILLSTREAKS_AIRSTRIKE=Nalot
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Wezwij nalot na wybraną pozycję.
MW2_KILLSTREAKS_HELICOPTER=Śmigłowiec
MW2_KILLSTREAKS_HELICOPTER_DESC=Wezwij śmigłowiec wsparcia.
MW2_KILLSTREAKS_AC130=AC130
MW2_KILLSTREAKS_AC130_DESC=Bądź strzelcem AC130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Pocisk Predator
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Zdalnie kieruj pociskiem.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Strzelec śmigł.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Bądź strzelcem śmigłowca szturmowego.
MW2_KILLSTREAKS_HELICOPTER_MK19=Strzelec śmigł.
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Zdalne sterowanie granatnikiem śmigłowca.
MW2_KILLSTREAKS_DOUBLE_UAV=Zaawansowany BSP
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=BSP z szybszym czasem przeczesywania.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Nalot precyzyjny
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Wezwij nalot kierunkowy.
MW2_KILLSTREAKS_AIRDROP=Pakiet pomocy
MW2_KILLSTREAKS_AIRDROP_DESC=Zrzuć losową serię ofiar lub amunicję.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Działko strażnicze
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Zrzuć rozstawiane działko strażnicze.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Pakiet pomocy (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Zrzuca pojedynczy pocisk predatora.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Nalot Harriera
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Nalot Harriera w zawisie.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Bomb. stealth
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Nalot niewidoczny na mapie wroga.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Supernalot
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Nalot z dodatkową siłą.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Czarna skrzynka śmigłowca
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Mocniejszy śmigłowiec.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Śmigłowiec obronny.
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Śmigłowiec z flarami
MW2_KILLSTREAKS_EMP=Impuls EM
MW2_KILLSTREAKS_EMP_DESC=Czasowo wyłącza elektronikę wroga.
MW2_KILLSTREAKS_TANK=Czołg
MW2_KILLSTREAKS_TANK_DESC=Czołg.
MW2_KILLSTREAKS_COUNTER_UAV=Kontr-BSP
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Czasowo wyłącza radar przeciwnika.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Ciężko opancerzony śmigłowiec.
MW2_KILLSTREAKS_NONE=Brak
MW2_KILLSTREAKS_NONE_DESC=Nie wybrano serii ofiar.
MW2_KILLSTREAKS_AIRDROP_MEGA=Zrzut awaryjny
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Zrzuć 4 losowe serie ofiar lub amunicję.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Naciśnij %s, żeby wezwać AWARYJNY ZRZUT.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Atomówka
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Zakończ grę wielkim bum.
MW2_KILLSTREAKS_SENTRY=Działko strażnicze

MW2_MP_EARNED_AIRSTRIKE=Naciśnij %s, by wezwać NALOT.
MW2_MP_EARNED_AIRDROP=Naciśnij %s, by wezwać ZRZUT POWIETRZNY.
MW2_MP_EARNED_SENTRY_AIRDROP=Naciśnij %s, by wezwać ZRZUT WIEŻYCZKI.
MW2_MP_EARNED_PREDATOR_AIRDROP=Naciśnij %s, by wezwać ZRZUT PREDATORA.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Naciśnij %s, by wezwać NALOT PRECYZYJNY.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Naciśnij %s, by wezwać BOMBOWIEC STEALTH.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Naciśnij %s, by wezwać NALOT HARRIERA.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Naciśnij %s, by wezwać SUPERNALOT.
MW2_MP_EARNED_UAV=Naciśnij %s, by wezwać BSP.
MW2_MP_EARNED_DOUBLE_UAV=Naciśnij %s, by użyć ZAAWANSOWANEGO BSP.
MW2_MP_EARNED_COUNTER_UAV=Naciśnij %s, by użyć ANTY-BSP.
MW2_MP_EARNED_HELICOPTER=Naciśnij %s, by wezwać ŚMIGŁOWIEC SZTURMOWY.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Naciśnij %s, by przełączyć na STRZELCA ŚMIGŁOWCA.
MW2_MP_EARNED_HELICOPTER_MK19=Naciśnij %s, by użyć MK19 ŚMIGŁOWCA.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Naciśnij %s, by użyć CZARNEJ SKRZYNKI ŚMIGŁOWCA.
MW2_MP_EARNED_HELICOPTER_FLARES=Naciśnij %s, by użyć ŚMIGŁOWCA PAVE LOW.
MW2_MP_EARNED_AC130=Naciśnij %s, by wezwać AC130.
MW2_MP_EARNED_PREDATOR_MISSILE=Naciśnij %s, by użyć POCISKU PREDATOR.
MW2_MP_EARNED_NUKE=Naciśnij %s, by użyć ATOMÓWKI TAKTYCZNEJ.
MW2_MP_EARNED_AUTO_SHOTGUN=Naciśnij %s, by użyć STRZELBY.
MW2_MP_EARNED_AUTO_SENTRY=Naciśnij %s, by użyć AUTOMATYCZNEJ WIEŻYCZKI.
MW2_MP_EARNED_AUTO_SENTRY_GL=Naciśnij %s, by użyć AUTOMATYCZNEGO GRANATNIKA.
MW2_MP_EARNED_THUMPER=Naciśnij %s, by wezwać KOLOSA.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Naciśnij %s, by wezwać LITTLEBIRDA.
MW2_MP_EARNED_EMP=Naciśnij %s, by użyć IMPULSU ELEKTROMAGNETYCZNEGO.

# Other
MW2_MP_CONNECTED=%s połączony
MW2_MP_DISCONNECTED=%s odłączony
MW2_EXE_LEFTGAME=%s opuścił grę

MW2_PLATFORM_RELOAD=Przeładowanie
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Mało amunicji
MW2_WEAPON_NO_AMMO=Brak amunicji

MW2_MPUI_WINNING_CAPS=ZWYCIʯA
MW2_MPUI_LOSING_CAPS=PRZEGRYWA
MW2_MPUI_TIED_CAPS=REMIS

MW2_CGAME_SB_SCORE=Wynik
MW2_CGAME_SB_DEATHS=Zgony
MW2_CGAME_SB_KILLS=Zabici
MW2_CGAME_SB_ASSISTS=Asyst

# Round Starter
MW2_MP_MATCH_STARTING_IN=Mecz zacznie się za:
MW2_MP_MATCH_RESUMING_IN=Wznowienie meczu za:

# Gamemodes
MW2_MPUI_SABOTAGE=Sabotaż
MW2_MPUI_DEATHMATCH=Dowolna
MW2_MPUI_CAPTURE_THE_FLAG=Zdobycie flagi
MW2_MPUI_HEADQUARTERS=Sztab
MW2_MPUI_SEARCH_AND_DESTROY=Znajdż i zniszcz
MW2_MPUI_WAR=Drużynowy Deathmatch
MW2_MPUI_DOMINATION=Dominacja
MW2_MPUI_ONE_FLAG=Zdobycie flagi
MW2_MPUI_ARENA=Arena
MW2_MPUI_DD=Wysadzanie
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Globalna wojna atomowa

MW2_MP_OBJ_DM_HINT=Wyeliminuj pozostałych graczy.
MW2_MP_OBJ_WAR_HINT=Wyeliminuj graczy nieprzyjaciela.
MW2_OBJECTIVES_WAR_HINT=Eliminuj graczy wroga.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Zniszcz cel A albo B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Chroń cele A i B.
MW2_OBJECTIVES_SAB_HINT=Zniszcz nieprzyjacielski cel.
MW2_OBJECTIVES_DOM_HINT=Zdobywaj flagi i broń ich.
MW2_OBJECTIVES_DM_HINT=Zlikwiduj innych graczy.
MW2_OBJECTIVES_KOTH_HINT=Broń sztabu.
MW2_OBJECTIVES_CTF_HINT=Zdobądź flagę wroga.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Zdobądź flagę wroga.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Broń flagi.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Zniszcz cele A i B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Chroń cele A i B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Zabij VIP-a, zanim dotrze do strefy ewakuacji.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Broń VIP-a i pomóż mu dotrzeć do strefy ewakuacji.
MW2_OBJECTIVES_ARENA_HINT=Zlikwiduj wroga lub zdobądź flagę
MW2_OBJECTIVES_GTNW_HINT=Zdobądź atomówkę.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Weź flagę wroga.

# Round Ender
MW2_MP_DRAW=Remis
MW2_MP_VICTORY=Zwycięstwo!
MW2_MP_DEFEAT=Porąbka!
MW2_MP_ROUND_DRAW=Remis w rundzie
MW2_MP_ROUND_WIN=Runda wygrana
MW2_MP_ROUND_LOSS=Runda przegrana
MW2_MP_HALFTIME=Połowa
MW2_MP_OVERTIME=Dodatkowy czas
MW2_MP_MATCH_BONUS_IS=Premia meczu: %s

MW2_MP_SCORE_LIMIT_REACHED=Osiągnięto limit wyniku
MW2_MP_ROUND_LIMIT_REACHED=Osiągnięto limit rundy
MW2_MP_TIME_LIMIT_REACHED=Osiągnięto limit czasu

MW2_MP_OPFOR_ELIMINATED=Przeciwnik wyeliminowany
MW2_MP_OPFOR_FORFEITED=Przeciwnik poddał
MW2_MP_SPETSNAZ_ELIMINATED=Specnaz zlikwidowany
MW2_MP_SPETSNAZ_FORFEITED=Specnaz poddał
MW2_MP_US_ARMY_ELIMINATED=US Army zlikwidowana
MW2_MP_US_ARMY_FORFEITED=US Army poddała
MW2_MP_MILITIA_ELIMINATED=Milicja zlikwidowana
MW2_MP_MILITIA_FORFEITED=Milicja poddała
MW2_MP_TF141_ELIMINATED=ZS 141 wyeliminowany
MW2_MP_TF141_FORFEITED=ZS 141 poddał
MW2_MP_SEALS_ELIMINATED=SEAL zlikwidowani
MW2_MP_SEALS_FORFEITED=SEAL polegli