#---------- MW2 HUD | Deutsch | German
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Army Rangers
MW2_MP_SEALS_UDT_NAME=Navy SEALs
MW2_MP_MILITIA_NAME=Miliz
MW2_MP_TASKFORCE_NAME=Sonderkommando 141
MW2_MP_OPFOR_NAME=OpFor
MW2_MP_SPETSNAZ_NAME=Speznas

MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_SEALS_UDT_SHORT_NAME=SEALs
MW2_MP_MILITIA_SHORT_NAME=Miliz
MW2_MP_TASKFORCE_SHORT_NAME=SK 141
MW2_MPUI_OPFOR_SHORT=OpFor
MW2_MPUI_SPETSNAZ_SHORT=Speznas

# Splashes
MW2_SPLASHES_HEADSHOT=Volltreffer!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Selbstmordhilfe!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Sie haben zum Selbstmord eines Feindes beigetragen.
MW2_SPLASHES_LONGSHOT=Fernkämpfer!
MW2_SPLASHES_LONGSHOT_DESC=Gelungener Fernangriff!
MW2_SPLASHES_EXECUTION=Vollstrecker!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Rächer!
MW2_SPLASHES_AVENGER_DESC=Sie haben die Rechnung eines Teammitglieds beglichen.
MW2_SPLASHES_DEFENDER=Retter!
MW2_SPLASHES_DEFENDER_DESC=Sie haben ein Teammitglied gerettet.
MW2_SPLASHES_POSTHUMOUS=Nicht totzukriegen!
MW2_SPLASHES_POSTHUMOUS_DESC=Sie haben einen Feind getötet, nachdem Sie selbst gestorben sind.
MW2_SPLASHES_REVENGE=Zahltag!
MW2_SPLASHES_REVENGE_DESC=Sie haben eine Rechnung beglichen.
MW2_SPLASHES_DOUBLEKILL=Doppelabschuss!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Dreifachabschuss!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Multiabschuss!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Starter!
MW2_SPLASHES_FIRSTBLOOD_DESC=Sie haben den ersten Abschuss gelandet.
MW2_SPLASHES_BUZZKILL=Spielverderber!
MW2_SPLASHES_BUZZKILL_DESC=Sie haben den Feind kurz vor einer Abschussserie gestoppt.
MW2_SPLASHES_COMEBACK=Comeback!
MW2_SPLASHES_COMEBACK_DESC=Sie haben sich von einer Todesserie erholt.
MW2_SPLASHES_FLAGRETURN=Flaggenrückkehr!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Flaggenläufer!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Position gesichert!
MW2_SPLASHES_CAPTURE_DESC=Sie haben ein Ziel erlangt.
MW2_SPLASHES_DEFEND=Verteidigung!
MW2_SPLASHES_DEFEND_DESC=Sie haben das Ziel verteidigt.
MW2_SPLASHES_ASSAULT=Angriff!
MW2_SPLASHES_ASSAULT_DESC=Sie haben einen Verteidiger ausgeschaltet.
MW2_SPLASHES_PLANT=Saboteur!
MW2_SPLASHES_PLANT_DESC=Sie haben die Bombe platziert.
MW2_SPLASHES_DEFUSE=Held!
MW2_SPLASHES_DEFUSE_DESC=Sie haben die Bombe entschärft.
MW2_SPLASHES_SAB_OVERTIME=Überstunden!
MW2_SPLASHES_SAB_OVERTIME_DESC=Die der Bombe nächste Basis wird zerstört.
MW2_SPLASHES_MARTYRDOM_DESC=Sie lassen eine scharfe Granate beim Tod fallen.
MW2_SPLASHES_FINALSTAND_DESC=Sie erhalten eine zweite Chance, wenn Sie zu Boden gegangen sind.
MW2_SPLASHES_ENDGAME_DESC=Sie haben die nächsten Sekunden über einen Gesundheitsbonus.
MW2_SPLASHES_C4DEATH_DESC=Holen Sie C4 raus, bevor Sie sterben.
MW2_SPLASHES_KNIFETHROW_DESC=Sie haben einen Feind mit einem Wurfmesser getötet.
MW2_SPLASHES_KNIFETHROW=Messerwerfer!
MW2_SPLASHES_HIJACKER_DESC=Sie haben eine Versorgungskiste des Feindes erlangt.
MW2_SPLASHES_HIJACKER=Dieb!
MW2_SPLASHES_HIJACKED=%s hat Ihre Versorgungskiste an sich genommen.
MW2_SPLASHES_DEFCON_LOWER=DEFCON gesenkt!
MW2_SPLASHES_DEFCON_RAISE=DEFCON erhöht!
MW2_SPLASHES_DEFCON_LOWER_DESC=Abschussserien verbessert!
MW2_SPLASHES_DEFCON_RAISE_DESC=Abschussserien verschlechtert.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Spiel beginnt!
MW2_SPLASHES_DEFCON_3_DESC=Notfall-Abwurf unterwegs!
MW2_SPLASHES_DEFCON_2_DESC=Abschussserien ohne Unterbrechung!
MW2_SPLASHES_DEFCON_1_DESC=Doppelte Punktzahl für Ziele!
MW2_SPLASHES_COMBATHIGH_DESC=Kurzzeitig verbesserte Gesundheit.
MW2_SPLASHES_RESTED=Täglicher EP-Bonus!
MW2_SPLASHES_RESTED_DESC=Verdienen Sie täglich Bonus-EP!
MW2_SPLASHES_RESTED_DONE=EP-Bonus vorbei.
MW2_SPLASHES_RESTED_DONE_DESC=Bonus-EP erhalten.
MW2_SPLASHES_VIP=Sie sind der VIP
MW2_SPLASHES_STUCK_SEMTEX=Klette!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Sie haben einem Feind eine Semtex-Granate angeheftet!
MW2_SPLASHES_HEROIC=Heldenhaft!
MW2_SPLASHES_HEROIC_DESC=Sie haben ein Ziel in allerletzter Minute erlangt!
MW2_SPLASHES_DENIED=Pech gehabt!
MW2_SPLASHES_DENIED_DESC=Sie haben einen Taktikeinstieg des Feindes zerstört.
MW2_SPLASHES_DESTROYED_INSERTION=Taktikeinstieg blockiert!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Kiste geschnappt!
MW2_SPLASHES_REVIVER_DESC=Sie haben ein gefallenes Teammitglied wiederbelebt.
MW2_SPLASHES_REVIVER=Rettender Engel!
MW2_SPLASHES_GIVEAWAY_SENTRY=... hat ein Geschütz aufgenommen
MW2_SPLASHES_GIVEAWAY_AIRDROP=... hat eine Abwurf-Abschussserie aufgenommen.
MW2_SPLASHES_SEMTEX_STUCK=heftete Semtex an Sie
MW2_SPLASHES_ONE_SHOT_KILL=Kurzer Prozess
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Ein Schuss, ein Volltreffer.
MW2_SPLASHES_NINJA_DEFUSE=Ninja-Entschärfen
MW2_SPLASHES_NINJA_DEFUSE_DESC=Immer schön unauffällig ...
MW2_SPLASHES_COPYCAT_DESC=Stehlen Sie die Klasse Ihres Bezwingers in der Abschusskamera.
MW2_SPLASHES_COPIED=Kopierte Klasse!
MW2_SPLASHES_REVIVED=hat Sie wiederbelebt
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Letzter Überlebender!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Letzter Überlebender!
MW2_SPLASHES_SHIELDASSIST=Alles im Griff!
MW2_SPLASHES_SHIELDASSIST_DESC=Sie sorgen für eine ausgezeichnete Ablenkung.
MW2_SPLASHES_DESTROYED_HELICOPTER=Helikopter zerstört!
MW2_SPLASHES_DESTROYED_PAVELOW=Pave Low zerstört!
MW2_SPLASHES_DESTROYED_UAV=Drohne zerstört!
MW2_SPLASHES_DESTROYED_HARRIER=Harrier zerstört!
MW2_SPLASHES_DESTROYED_AC130=AC-130 zerstört!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Hubschr. zerstört!
MW2_SPLASHES_FLAG_RETURN=Flagge zurückgeholt!
MW2_SPLASHES_FLAG_CAPTURE=Flagge eingenommen!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Hat ihre Flagge!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Hat die feindliche Flagge!
MW2_SPLASHES_FLAG_PICKUP=Hat die Flagge!
MW2_SPLASHES_CAPTURED_NUKE=Atombombe eingenommen!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Sie haben die Atombombe eingenommen.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Magazinerweiterung freigeschaltet!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Herzschlagsensor freigeschaltet!
MW2_SPLASHES_UNLOCKED_AKIMBO=Akimbo freigeschaltet!
MW2_SPLASHES_UNLOCKED_THERMAL=Thermalzielfernrohr freigeschaltet!
MW2_SPLASHES_UNLOCKED_EOTECH=Holographisches Visier freigeschaltet!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Schrotflinte freigeschaltet!
MW2_SPLASHES_GRABBED_THE_FLAG=hat die Flagge geschnappt!
MW2_SPLASHES_HIJACKED_SENTRY=hat Ihr Geschütz genommen!
MW2_SPLASHES_HIJACKED_AIRDROP=nahm Ihre Kiste!
MW2_SPLASHES_BOMB_PLANTED=Bombe platziert!
MW2_SPLASHES_BOMB_DEFUSED=Bombe entschärft!
MW2_SPLASHES_TIMEADDED=Zusätzliche Zeit!
MW2_SPLASHES_GTNW_OVERTIME=Sudden Death!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Kein Wiedereinstieg.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Ziel zerstört!
MW2_SPLASHES_SAVED_OBJECTIVE=Ziel gerettet!
MW2_SPLASHES_CAPTURED_HQ=HQ eingenommen!
MW2_SPLASHES_DESTROYED_HQ=HQ zerstört!
MW2_SPLASHES_BOMB_TAKEN=Bombe aufgenommen!
MW2_SPLASHES_BOMB_DROPPED=Bombe fallengelassen!
MW2_SPLASHES_KILLED_CARRIER=Bombenträger ausgeschaltet!
MW2_SPLASHES_SHAREPACKAGE=Vorräte teilen!
MW2_SPLASHES_SHAREPACKAGE_DESC=Ein Teamkamerad hat Ihre Vorräte vor dem Feind geschützt!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Drohne wiederhergestellt!
MW2_SPLASHES_FLAGS_CAPTURE=Flagge erobert!
MW2_SPLASHES_FLAG_ASSAULT=Flaggenangriff!
MW2_SPLASHES_FLAG_DEFEND=Flaggenverteidigung!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Sie haben einen Flaggenverteidiger ausgeschaltet.
MW2_SPLASHES_FLAG_DEFEND_DESC=Sie haben die Flagge verteidigt.
MW2_SPLASHES_FLAG_CAPTURED=Flagge eingenommen!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Sie haben die feindliche Flagge erobert.
MW2_SPLASHES_SECURED_POSITION=Position gesichert!
MW2_SPLASHES_SECURED_POSITION_A=A gesichert!
MW2_SPLASHES_SECURED_POSITION_B=B gesichert!
MW2_SPLASHES_SECURED_POSITION_C=C gesichert!
MW2_SPLASHES_TIME_ADDED=Zeitverlängerung!
MW2_SPLASHES_TIME_ADDED_DESC=Bombenplatz zerstört. Spielzeit verlängert.

# Killstreaks
MW2_KILLSTREAKS_UAV=Drohne
MW2_KILLSTREAKS_UAV_DESC=Zeigt Feinde auf der Minikarte.
MW2_KILLSTREAKS_AIRSTRIKE=Luftschlag
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Luftschlag auf ausgewählte Position anfordern.
MW2_KILLSTREAKS_HELICOPTER=Kampfhubschrauber
MW2_KILLSTREAKS_HELICOPTER_DESC=Kampfhubschrauber anfordern.
MW2_KILLSTREAKS_AC130=AC-130
MW2_KILLSTREAKS_AC130_DESC=Schütze in einer AC-130 sein.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Predator-Rakete
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Ferngesteuerte Rakete.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Hubschr.-Schütze
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Schütze in einem Kampfhubschrauber sein.
MW2_KILLSTREAKS_HELICOPTER_MK19=Helikopter-Schütze
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Fernsteuerung eines Helikopter-Granatwerfers.
MW2_KILLSTREAKS_DOUBLE_UAV=Verbesserte Drohne
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=Drohne mit höherem Suchtempo.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Präz.-Luftschlag
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Positionsgebundenen Luftschlag anfordern.
MW2_KILLSTREAKS_AIRDROP=Vorräte
MW2_KILLSTREAKS_AIRDROP_DESC=Zufällige Abschussserie oder Munition.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Geschütz
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Abwurf eines aufstellbaren Geschützes.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Vorräte (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Abwurf einer einzelnen Predator-Rakete
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Harrier-Schlag
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Luftschlag mit einer schwebenden Harrier.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Stealth-Bomber
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Luftschlag auf feindlicher Karte unsichtbar.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Super-Luftschlag
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Besonders wirkungsvoller Luftschlag.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Helikopter-Blackbox
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Länger vorhandener Helikopter
MW2_KILLSTREAKS_HELICOPTER_FLARES=Defensiv-Helikopter
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Helikopter mit Täuschungskörpern.
MW2_KILLSTREAKS_EMP=EMP
MW2_KILLSTREAKS_EMP_DESC=Feindliche Elektronik temporär deaktivieren.
MW2_KILLSTREAKS_TANK=Panzer
MW2_KILLSTREAKS_TANK_DESC=Ein Panzer
MW2_KILLSTREAKS_COUNTER_UAV=Konter-Drohne
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Deaktiviert feindliches Radar vorübergehend.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Schwer bewaffneter Kampfhubschrauber.
MW2_KILLSTREAKS_NONE=Ohne
MW2_KILLSTREAKS_NONE_DESC=Keine Abschussserie gewählt
MW2_KILLSTREAKS_AIRDROP_MEGA=Notfall-Abwurf
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=4 zufällige Abschussserien oder Munition.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Drücken Sie %s für einen NOTFALL-ABWURF.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Atombombe
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Beendet das Spiel mit einem Knall.
MW2_KILLSTREAKS_SENTRY=Geschütz

MW2_MP_EARNED_AIRSTRIKE=Drücken Sie %s für LUFTSCHLAG.
MW2_MP_EARNED_AIRDROP=Drücken Sie %s für den ABWURF.
MW2_MP_EARNED_SENTRY_AIRDROP=Drücken Sie %s für den GESCHÜTZ-ABWURF.
MW2_MP_EARNED_PREDATOR_AIRDROP=Drücken Sie %s für den PREDATOR-ABWURF.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Drücken Sie %s für den PRÄZISIONS-LUFTSCHLAG.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Drücken Sie %s für den STEALTH-BOMBER.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Drücken Sie %s für den HARRIER-LUFTSCHLAG.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Drücken Sie %s für den SUPER-LUFTSCHLAG.
MW2_MP_EARNED_UAV=Drücken Sie %s für die DROHNE.
MW2_MP_EARNED_DOUBLE_UAV=Drücken Sie %s für die VERBESSERTE DROHNE.
MW2_MP_EARNED_COUNTER_UAV=Drücken Sie %s für die KONTER-DROHNE.
MW2_MP_EARNED_HELICOPTER=Drücken Sie %s für ANGRIFFSHELIKOPTER.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Drücken Sie %s für den HELIKOPTER-SCHÜTZEN.
MW2_MP_EARNED_HELICOPTER_MK19=Drücken Sie %s für die HELIKOPTER-MK19.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Drücken Sie %s für die HELIKOPTER-BLACKBOX.
MW2_MP_EARNED_HELICOPTER_FLARES=Drücken Sie %s für den PAVE LOW.
MW2_MP_EARNED_AC130=Drücken Sie %s für die AC-130.
MW2_MP_EARNED_PREDATOR_MISSILE=Drücken Sie %s für die PREDATOR-RAKETE.
MW2_MP_EARNED_NUKE=Drücken Sie %s für die ATOMBOMBE.
MW2_MP_EARNED_AUTO_SHOTGUN=Drücken Sie %s für die SCHROTFLINTE.
MW2_MP_EARNED_AUTO_SENTRY=Drücken Sie %s für das AUTOMATIK-GESCHÜTZ.
MW2_MP_EARNED_AUTO_SENTRY_GL=Drücken Sie %s für den AUTOMATIK-GRANATWERFER.
MW2_MP_EARNED_THUMPER=Drücken Sie %s für den THUMPER.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Drücken Sie %s für den LITTLEBIRD.
MW2_MP_EARNED_EMP=Drücken Sie %s für den EMP.

# Other
MW2_MP_CONNECTED=%s hat sich angeschlossen
MW2_MP_DISCONNECTED=%s hat sich abgemeldet
MW2_EXE_LEFTGAME=%s Hat das Spiel verlassen

MW2_PLATFORM_RELOAD=Nachladen
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Wenig Munition
MW2_WEAPON_NO_AMMO=Keine Munition

MW2_MPUI_WINNING_CAPS=SIE GEWINNEN
MW2_MPUI_LOSING_CAPS=SIE VERLIEREN
MW2_MPUI_TIED_CAPS=UNENTSCHIEDEN

MW2_CGAME_SB_SCORE=Pkt.
MW2_CGAME_SB_DEATHS=Tode
MW2_CGAME_SB_KILLS=Absch.
MW2_CGAME_SB_ASSISTS=Assis.

# Round Starter
MW2_MP_MATCH_STARTING_IN=Spiel beginnt in:
MW2_MP_MATCH_RESUMING_IN=Partie wird fortgesetzt in:

# Gamemodes
MW2_MPUI_SABOTAGE=Sabotage
MW2_MPUI_DEATHMATCH=Frei für alle
MW2_MPUI_CAPTURE_THE_FLAG=Capture the Flag
MW2_MPUI_HEADQUARTERS=Hauptquartier
MW2_MPUI_SEARCH_AND_DESTROY=Suchen und Zerstören
MW2_MPUI_WAR=Team-Deathmatch
MW2_MPUI_DOMINATION=Herrschaft
MW2_MPUI_ONE_FLAG=CTF - Eine Flagge
MW2_MPUI_ARENA=Arena
MW2_MPUI_DD=Sprengkommando
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Thermonuklearer Krieg

MW2_MP_OBJ_DM_HINT=Schalten Sie alle Spieler aus.
MW2_MP_OBJ_WAR_HINT=Schalten Sie die feindlichen Spieler aus.
MW2_OBJECTIVES_WAR_HINT=Schalten Sie die feindlichen Spieler aus.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Zerstören Sie Ziel A oder B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Beschützen Sie Ziele A und B.
MW2_OBJECTIVES_SAB_HINT=Zerstören Sie das feindliche Ziel.
MW2_OBJECTIVES_DOM_HINT=Erobern Sie die Flaggen und verteidigen Sie sie.
MW2_OBJECTIVES_DM_HINT=Schalten Sie alle Spieler aus.
MW2_OBJECTIVES_KOTH_HINT=Halten Sie das Hauptquartier!
MW2_OBJECTIVES_CTF_HINT=Nehmen Sie die feindliche Flagge ein.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Nehmen Sie die feindliche Flagge ein.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Verteidigen Sie die Flagge.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Zerstören Sie die Ziele A und B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Beschützen Sie Ziele A und B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Schalten Sie den VIP aus, er darf die Evakuierungszone nicht erreichen.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Verteidigen Sie den VIP und helfen Sie ihm, die Evakuierungszone zu erreichen.
MW2_OBJECTIVES_ARENA_HINT=Eliminieren Sie den Feind oder erobern Sie die Flagge 
MW2_OBJECTIVES_GTNW_HINT=Erobern Sie die Atombombe.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Schnappen Sie sich die feindliche Flagge.

# Round Ender
MW2_MP_DRAW=Unentschieden
MW2_MP_VICTORY=Sieg!
MW2_MP_DEFEAT=Niederlage!
MW2_MP_ROUND_DRAW=Runde unentschieden
MW2_MP_ROUND_WIN=Rundensieg
MW2_MP_ROUND_LOSS=Rundenniederlage
MW2_MP_HALFTIME=Halbzeit
MW2_MP_OVERTIME=Verlängerung
MW2_MP_MATCH_BONUS_IS=Spielbonus: %s

MW2_MP_SCORE_LIMIT_REACHED=Punktelimit erreicht.
MW2_MP_ROUND_LIMIT_REACHED=Rundenlimit erreicht.
MW2_MP_TIME_LIMIT_REACHED=Zeitlimit erreicht.

MW2_MP_OPFOR_ELIMINATED=OpFor wurde eliminiert.
MW2_MP_OPFOR_FORFEITED=OpFor hat kapituliert.
MW2_MP_SPETSNAZ_ELIMINATED=Die Speznas wurden eliminiert.
MW2_MP_SPETSNAZ_FORFEITED=Die Speznas haben kapituliert.
MW2_MP_US_ARMY_ELIMINATED=US Army ausgeschaltet
MW2_MP_US_ARMY_FORFEITED=US Army hat aufgegeben
MW2_MP_MILITIA_ELIMINATED=Miliz ausgeschaltet
MW2_MP_MILITIA_FORFEITED=Miliz hat aufgegeben
MW2_MP_TF141_ELIMINATED=SK 141 ausgeschaltet
MW2_MP_TF141_FORFEITED=SK 141 hat aufgegeben
MW2_MP_SEALS_ELIMINATED=SEALs ausgeschaltet
MW2_MP_SEALS_FORFEITED=SEALs haben aufgegeben