#---------- MW3 HUD | English
# Translator: Original Game

# Factions
MW3_MP_SAS=Special Air Service
MW3_MP_INNERCIRCLE_NAME=Innerer Kreis
MW3_MP_AFRICA_MILITIA_NAME=Afrika-Miliz
MW3_MP_DELTA_NAME=Delta Force
MW3_MP_GIGN=GIGN
MW3_MP_SPETSNAZ_NAME=Speznas
MW3_MP_PMC_NAME=P.M.C.

MW3_MP_SAS_SHORT_NAME=SAS
MW3_MP_INNERCIRCLE_SHORT_NAME=Innerer Kreis
MW3_MP_AFRICA_MILITIA_SHORT_NAME=Miliz
MW3_MP_PMC_SHORT_NAME=PMC
MW3_MP_DELTA_SHORT_NAME=Delta
MW3_MP_GIGN_SHORT_NAME=GIGN
MW3_MPUI_SPETSNAZ_SHORT=Speznas
MW3_MP_PMC_SHORT_NAME=P.M.C.