#---------- MW2 HUD | Español | Spanish
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Rangers del ejército
MW2_MP_OPFORCE_COMPOSITE_NAME=OpFor
MW2_MP_SEALS_UDT_NAME=SEAL de la marina
MW2_MP_SECRET_SERVICE_NAME=Servicio secreto
MW2_MP_MILITIA_NAME=Milicia
MW2_MP_TASKFORCE_NAME=Fuerza operativa 141
MW2_MP_OPFORCE_ARCTIC_NAME=OpFor
MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_OPFORCE_COMPOSITE_SHORT_NAME=OpFor
MW2_MP_SEALS_UDT_SHORT_NAME=SEAL
MW2_MP_SECRET_SERVICE_SHORT_NAME=Servicio secreto
MW2_MP_MILITIA_SHORT_NAME=Milicia
MW2_MP_TASKFORCE_SHORT_NAME=FO 141
MW2_MP_OPFORCE_ARCTIC_SHORT_NAME=OpFor

# Splashes
MW2_SPLASHES_HEADSHOT=¡Tiro en la cabeza!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=¡Suicidio asistido!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Has ayudado a un enemigo a suicidarse.
MW2_SPLASHES_LONGSHOT=¡Tiro lejano!
MW2_SPLASHES_LONGSHOT_DESC=¡Has acertado desde lejos!
MW2_SPLASHES_EXECUTION=¡Ejecución!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=¡Vengador!
MW2_SPLASHES_AVENGER_DESC=Has vengado a un compañero de equipo.
MW2_SPLASHES_DEFENDER=¡Rescatador!
MW2_SPLASHES_DEFENDER_DESC=Has rescatado a un compañero de equipo.
MW2_SPLASHES_POSTHUMOUS=¡La otra vida!
MW2_SPLASHES_POSTHUMOUS_DESC=Has matado a un enemigo después de morir.
MW2_SPLASHES_REVENGE=¡Venganza!
MW2_SPLASHES_REVENGE_DESC=Te has vengado.
MW2_SPLASHES_DOUBLEKILL=¡Baja doble!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=¡Triple baja!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=¡Bajas múltiples!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=¡Primera sangre!
MW2_SPLASHES_FIRSTBLOOD_DESC=Has conseguido la primera baja.
MW2_SPLASHES_BUZZKILL=¡Bajón!
MW2_SPLASHES_BUZZKILL_DESC=Has detenido al enemigo cuando estaba a punto de conseguir una racha de bajas.
MW2_SPLASHES_COMEBACK=¡Retorno!
MW2_SPLASHES_COMEBACK_DESC=Te has recuperado de una racha de bajas.
MW2_SPLASHES_FLAGRETURN=¡Bandera devuelta!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=¡Llevabanderas!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=¡Posición asegurada!
MW2_SPLASHES_CAPTURE_DESC=Has tomado un objetivo.
MW2_SPLASHES_DEFEND=¡Defensa!
MW2_SPLASHES_DEFEND_DESC=Has defendido el objetivo.
MW2_SPLASHES_ASSAULT=¡Ataque!
MW2_SPLASHES_ASSAULT_DESC=Has matado a un defensor.
MW2_SPLASHES_PLANT=¡Saboteador!
MW2_SPLASHES_PLANT_DESC=Has colocado la bomba.
MW2_SPLASHES_DEFUSE=¡Héroe!
MW2_SPLASHES_DEFUSE_DESC=Has desactivado la bomba.
MW2_SPLASHES_SAB_OVERTIME=¡Prórroga!
MW2_SPLASHES_SAB_OVERTIME_DESC=La base más cercana a la bomba será destruida.
MW2_SPLASHES_MARTYRDOM_DESC=Sueltas una granada preparada al morir.
MW2_SPLASHES_FINALSTAND_DESC=Tendrás una segunda oportunidad cuando caigas.
MW2_SPLASHES_ENDGAME_DESC=Has conseguido salud extra durante unos segundos.
MW2_SPLASHES_C4DEATH_DESC=Saca el C4 antes de morir.
MW2_SPLASHES_KNIFETHROW_DESC=Has matado a un enemigo con el cuchillo arrojadizo.
MW2_SPLASHES_KNIFETHROW=¡Blanco!
MW2_SPLASHES_HIJACKER_DESC=Has robado un cajón de suministros enemigo.
MW2_SPLASHES_HIJACKER=¡Secuestrador!
MW2_SPLASHES_HIJACKED=%s ha tomado tu cajón de suministros.
MW2_SPLASHES_DEFCON_LOWER=¡DEFCON reducido!
MW2_SPLASHES_DEFCON_RAISE=DEFCON subido
MW2_SPLASHES_DEFCON_LOWER_DESC=¡Rachas de bajas mejoradas!
MW2_SPLASHES_DEFCON_RAISE_DESC=Rachas de bajas reducidas.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=¡Iniciando partida!
MW2_SPLASHES_DEFCON_3_DESC=¡Lanzamiento de emergencia inminente!
MW2_SPLASHES_DEFCON_2_DESC=¡A por más rachas de bajas!
MW2_SPLASHES_DEFCON_1_DESC=¡Puntos dobles por los objetivos!
MW2_SPLASHES_COMBATHIGH_DESC=Salud mejorada durante un corto periodo.
MW2_SPLASHES_RESTED=¡Subida diaria de PX!
MW2_SPLASHES_RESTED_DESC=¡Te estás ganando tu bonificación diaria de PX!
MW2_SPLASHES_RESTED_DONE=Subida diaria de PX realizada.
MW2_SPLASHES_RESTED_DONE_DESC=PX adicionales conseguidos.
MW2_SPLASHES_VIP=Eres el VIP
MW2_SPLASHES_STUCK_SEMTEX=¡Pegada!
MW2_SPLASHES_STUCK_SEMTEX_DESC=¡Le has pegado una Semtex a un enemigo!
MW2_SPLASHES_HEROIC=¡Heroico!
MW2_SPLASHES_HEROIC_DESC=¡Has tomado un objetivo en última batalla!
MW2_SPLASHES_DENIED=¡Nada de eso!
MW2_SPLASHES_DENIED_DESC=¡Has destruido una inserción táctica enemiga!
MW2_SPLASHES_DESTROYED_INSERTION=¡IT bloqueada!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=¡Se llevó tu caja!
MW2_SPLASHES_REVIVER_DESC=Has revivido a un compañero caído.
MW2_SPLASHES_REVIVER=¡Sanador!
MW2_SPLASHES_GIVEAWAY_SENTRY=... ha cogido una torreta
MW2_SPLASHES_GIVEAWAY_AIRDROP=... ha cogido una racha de bajas lanzada desde el aire.
MW2_SPLASHES_SEMTEX_STUCK=Te han pegado una Semtex
MW2_SPLASHES_ONE_SHOT_KILL=Una baja de un disparo
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Un tiro... un muerto
MW2_SPLASHES_NINJA_DEFUSE=Desactivación ninja
MW2_SPLASHES_NINJA_DEFUSE_DESC=Silencio, silencio...
MW2_SPLASHES_COPYCAT_DESC=Roba la clase de tu asesino en cámara de muerte.
MW2_SPLASHES_COPIED=¡Clase copiada!
MW2_SPLASHES_REVIVED=Te han revivido
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=¡El último con vida!
MW2_SPLASHES_LAST_ENEMY_ALIVE=¡El último con vida!
MW2_SPLASHES_SHIELDASSIST=¡Control de multitudes!
MW2_SPLASHES_SHIELDASSIST_DESC=Eres una excelente distracción.
MW2_SPLASHES_DESTROYED_HELICOPTER=¡Helicóptero destruido!
MW2_SPLASHES_DESTROYED_PAVELOW=¡Pave Low destruido!
MW2_SPLASHES_DESTROYED_UAV=¡UAV destruido!
MW2_SPLASHES_DESTROYED_HARRIER=¡Harrier destruido!
MW2_SPLASHES_DESTROYED_AC130=¡AC130 destruido!
MW2_SPLASHES_DESTROYED_MINIGUNNER=¡Avión destruido!
MW2_SPLASHES_FLAG_RETURN=¡Bandera devuelta!
MW2_SPLASHES_FLAG_CAPTURE=¡Bandera tomada!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=¡Ha tomado tu bandera!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=¡Bandera tomada!
MW2_SPLASHES_FLAG_PICKUP=¡Ha tomado la bandera!
MW2_SPLASHES_CAPTURED_NUKE=¡Bomba nuclear tomada!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Bomba nuclear tomada.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=¡Cargadores ampliados desbloqueados!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=¡Sensor de ritmo cardiaco desbloqueado!
MW2_SPLASHES_UNLOCKED_AKIMBO=¡Duales desbloqueadas!
MW2_SPLASHES_UNLOCKED_THERMAL=¡Mira térmica desbloqueada!
MW2_SPLASHES_UNLOCKED_EOTECH=¡Visión holográfica desbloqueada!
MW2_SPLASHES_UNLOCKED_SHOTGUN=¡Escopeta desbloqueada!
MW2_SPLASHES_GRABBED_THE_FLAG=¡Bandera recogida!
MW2_SPLASHES_HIJACKED_SENTRY=¡Se llevó tu torreta!
MW2_SPLASHES_HIJACKED_AIRDROP=¡Se llevó tu caja!
MW2_SPLASHES_BOMB_PLANTED=¡Bomba colocada!
MW2_SPLASHES_BOMB_DEFUSED=¡Bomba desactivada!
MW2_SPLASHES_TIMEADDED=¡Tiempo añadido!
MW2_SPLASHES_GTNW_OVERTIME=¡Muerte súbita!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Sin reaparición.
MW2_SPLASHES_DESTROYED_OBJECTIVE=¡Objetivo destruido!
MW2_SPLASHES_SAVED_OBJECTIVE=¡Objetivo salvado!
MW2_SPLASHES_CAPTURED_HQ=¡CG tomado!
MW2_SPLASHES_DESTROYED_HQ=¡CG destruido!
MW2_SPLASHES_BOMB_TAKEN=¡Bomba recogida!
MW2_SPLASHES_BOMB_DROPPED=¡Bomba soltada!
MW2_SPLASHES_KILLED_CARRIER=¡Portabomba muerto!
MW2_SPLASHES_SHAREPACKAGE=¡Paquete común!
MW2_SPLASHES_SHAREPACKAGE_DESC=¡Un compañero ha salvado tu paquete de ayuda del enemigo!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=¡UAV restablecido!
MW2_SPLASHES_FLAGS_CAPTURE=ha tomado una bandera.
MW2_SPLASHES_FLAG_ASSAULT=¡Asalto a la bandera!
MW2_SPLASHES_FLAG_DEFEND=¡Defensa de bandera!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Has matado a un defensor de la bandera.
MW2_SPLASHES_FLAG_DEFEND_DESC=Has defendido la bandera.
MW2_SPLASHES_FLAG_CAPTURED=¡Bandera tomada!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Has tomado la bandera enemiga.
MW2_SPLASHES_SECURED_POSITION=¡Posición asegurada!
MW2_SPLASHES_SECURED_POSITION_A=¡A asegurada!
MW2_SPLASHES_SECURED_POSITION_B=¡B asegurada!
MW2_SPLASHES_SECURED_POSITION_C=¡C asegurada!
MW2_SPLASHES_TIME_ADDED=¡Tiempo ampliado!
MW2_SPLASHES_TIME_ADDED_DESC=Zona de bombas destruida. Tiempo de juego ampliado.

# Killstreaks
MW2_KILLSTREAKS_UAV=UAV
MW2_KILLSTREAKS_UAV_DESC=Muestra enemigos en el minimapa.
MW2_KILLSTREAKS_AIRSTRIKE=Ataque aéreo
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Solicita un ataque aéreo sobre la posición elegida.
MW2_KILLSTREAKS_HELICOPTER=Helicóptero
MW2_KILLSTREAKS_HELICOPTER_DESC=Solicita un helicóptero de apoyo.
MW2_KILLSTREAKS_AC130=AC130
MW2_KILLSTREAKS_AC130_DESC=Te conviertes en el artillero de un AC130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Misil Predator
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Un misil por control remoto.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Apoyo aéreo
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Dirige la artillería de un helicóptero.
MW2_KILLSTREAKS_HELICOPTER_MK19=Apoyo aéreo
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Control remoto de un lanzagrandas de helicóptero.
MW2_KILLSTREAKS_DOUBLE_UAV=UAV avanzado
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=Un UAV más rápido.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Ataque aéreo
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Solicita un ataque aéreo dirigido.
MW2_KILLSTREAKS_AIRDROP=Paquete de ayuda
MW2_KILLSTREAKS_AIRDROP_DESC=Lanza al azar una recompensa o munición. 
MW2_KILLSTREAKS_AIRDROP_SENTRY=Torreta
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Suelta una torreta desplegable.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Paquete de ayuda (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Suelta un misil Predator de un solo uso.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Ataque Harrier
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Un ataque aéreo con un Harrier.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Avión furtivo
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Ataque aéreo indetectable para los GPS.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Superataque aéreo
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Un ataque aéreo muy potente.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Helicóptero Blackbox
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Un helicóptero que dura más.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Helicóptero defensivo
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Un helicóptero con bengalas.
MW2_KILLSTREAKS_EMP=IEM
MW2_KILLSTREAKS_EMP_DESC=Desactiva sistemas electrónicos enemigos.
MW2_KILLSTREAKS_TANK=Tanque
MW2_KILLSTREAKS_TANK_DESC=Un tanque.
MW2_KILLSTREAKS_COUNTER_UAV=UAV de respuesta
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Desactiva temporalmente el radar enemigo.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Helicóptero de asalto blindado.
MW2_KILLSTREAKS_NONE=Ninguno
MW2_KILLSTREAKS_NONE_DESC=No se ha elegido una racha de bajas.
MW2_KILLSTREAKS_AIRDROP_MEGA=Lanzamiento emer.
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Lanza 4 recompensas y/o municiones.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Pulsa %s para usar LANZAMIENTO DE EMERGENCIA.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Bomba nuclear
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=La partida termina con una explosión.
MW2_KILLSTREAKS_SENTRY=Torreta

MW2_MP_EARNED_AIRSTRIKE=Pulsa %s para pedir ATAQUE AÉREO.
MW2_MP_EARNED_AIRDROP=Pulsa %s para LANZAMIENTO.
MW2_MP_EARNED_SENTRY_AIRDROP=Pulsa %s para LANZAMIENTO DE TORRETA.
MW2_MP_EARNED_PREDATOR_AIRDROP=Pulsa %s para LANZAMIENTO DE PREDATOR.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Pulsa %s para ATAQUE AÉREO.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Pulsa %s para AVIÓN FURTIVO.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Pulsa %s para ATAQUE HARRIER.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Pulsa %s para SUPERATAQUE.
MW2_MP_EARNED_UAV=Pulsa %s para UAV.
MW2_MP_EARNED_DOUBLE_UAV=Pulsa %s para UAV AVANZADO.
MW2_MP_EARNED_COUNTER_UAV=Pulsa %s para UAV DE RESPUESTA.
MW2_MP_EARNED_HELICOPTER=Pulsa %s para pedir un HELICÓPTERO DE ATAQUE.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Pulsa %s para APOYO AÉREO.
MW2_MP_EARNED_HELICOPTER_MK19=Pulsa %s para HELICÓPTERO CON MK19.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Pulsa %s para HELICÓPTERO BLACKBOX.
MW2_MP_EARNED_HELICOPTER_FLARES=Pulsa %s para PAVE LOW.
MW2_MP_EARNED_AC130=Pulsa %s para AC130.
MW2_MP_EARNED_PREDATOR_MISSILE=Pulsa %s para MISIL PREDATOR.
MW2_MP_EARNED_NUKE=Pulsa %s para BOMBA NUCLEAR TÁCTICA.
MW2_MP_EARNED_AUTO_SHOTGUN=Pulsa %s para ESCOPETA.
MW2_MP_EARNED_AUTO_SENTRY=Pulsa %s para TORRETA AUTOMÁTICA.
MW2_MP_EARNED_AUTO_SENTRY_GL=Pulsa %s para TORRETA CON LANZAGRANADAS.
MW2_MP_EARNED_THUMPER=Pulsa %s para THUMPER.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Pulsa %s para LITTLEBIRD.
MW2_MP_EARNED_EMP=Pulsa %s para IEM.

# Other
MW2_MP_CONNECTED=%s se ha conectado
MW2_MP_DISCONNECTED=%s se ha desconectado
MW2_EXE_LEFTGAME=%s ha abandonado la partida

MW2_PLATFORM_RELOAD=Recargar
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Munición escasa
MW2_WEAPON_NO_AMMO=Sin munición

MW2_MPUI_WINNING_CAPS=GANANDO
MW2_MPUI_LOSING_CAPS=PERDIENDO
MW2_MPUI_TIED_CAPS=EMPATE

# Round Starter
MW2_MP_MATCH_STARTING_IN=La partida empieza en:
MW2_MP_MATCH_RESUMING_IN=La partida continúa en:

MW2_MP_OBJ_DM_HINT=Elimina a los demás jugadores.
MW2_MP_OBJ_WAR_HINT=Elimina a los enemigos.
MW2_OBJECTIVES_WAR_HINT=Elimina a los enemigos.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Destruye objetivo A o B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Protege los objetivos A y B.
MW2_OBJECTIVES_SAB_HINT=Destruir el objetivo enemigo.
MW2_OBJECTIVES_DOM_HINT=Toma y defiende banderas.
MW2_OBJECTIVES_DM_HINT=Elimina a los demás jugadores.
MW2_OBJECTIVES_KOTH_HINT=Mantén el cuartel general.
MW2_OBJECTIVES_CTF_HINT=Toma la bandera enemiga.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Toma la bandera enemiga.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Defiende la bandera.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Destruye los objetivos A y B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Protege los objetivos A y B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Mata al VIP e impide que llegue a la zona de extracción.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Defiende al VIP y ayúdalo a llegar a la zona de extracción.
MW2_OBJECTIVES_ARENA_HINT=Elimina al enemigo o toma la bandera.
MW2_OBJECTIVES_GTNW_HINT=Hazte con la bomba nuclear.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Coge la bandera enemiga.