#---------- MW2 HUD | Русский | Russian
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Военные рейнджеры
MW2_MP_SEALS_UDT_NAME="Морские котики" ВМС США
MW2_MP_MILITIA_NAME=Ополчение
MW2_MP_TASKFORCE_NAME=ОТГ-141
MW2_MP_OPFOR_NAME=Сепаратисты
MW2_MP_SPETSNAZ_NAME=Спецназ

MW2_MP_US_ARMY_SHORT_NAME=Рейнджеры
MW2_MP_SEALS_UDT_SHORT_NAME="Морские котики"
MW2_MP_MILITIA_SHORT_NAME=Ополчение
MW2_MP_TASKFORCE_SHORT_NAME=ОТГ-141
MW2_MPUI_OPFOR_SHORT=Сепаратисты
MW2_MPUI_SPETSNAZ_SHORT=Спецназ

# Splashes
MW2_SPLASHES_HEADSHOT=Прямо в голову!
MW2_SPLASHES_HEADSHOT_DESC=%s
MW2_SPLASHES_ASSISTEDSUICIDE=Помощь в суициде!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Вы помогли противнику совершить самоубийство.
MW2_SPLASHES_LONGSHOT=Дальний выстрел!
MW2_SPLASHES_LONGSHOT_DESC=Убийство с дальнего расстояния!
MW2_SPLASHES_EXECUTION=Казнь!
MW2_SPLASHES_EXECUTION_DESC=%s
MW2_SPLASHES_AVENGER=Мститель!
MW2_SPLASHES_AVENGER_DESC=Вы отомстили за товарища по команде.
MW2_SPLASHES_DEFENDER=Защитник!
MW2_SPLASHES_DEFENDER_DESC=Вы спасли товарища по команде.
MW2_SPLASHES_POSTHUMOUS=Загробная жизнь!
MW2_SPLASHES_POSTHUMOUS_DESC=Вы убили противника после собственной смерти.
MW2_SPLASHES_REVENGE=Расплата!
MW2_SPLASHES_REVENGE_DESC=Вы отомстили.
MW2_SPLASHES_DOUBLEKILL=Двойное убийство!
MW2_SPLASHES_DOUBLEKILL_DESC=%s
MW2_SPLASHES_TRIPLEKILL=Тройное убийство!
MW2_SPLASHES_TRIPLEKILL_DESC=%s
MW2_SPLASHES_MULTIKILL=Множественное убийство!
MW2_SPLASHES_MULTIKILL_DESC=%s
MW2_SPLASHES_FIRSTBLOOD=Первая кровь!
MW2_SPLASHES_FIRSTBLOOD_DESC=Вы совершили первое убийство.
MW2_SPLASHES_BUZZKILL=Зануда!
MW2_SPLASHES_BUZZKILL_DESC=Вы в последний момент не дали противнику совершить серию.
MW2_SPLASHES_COMEBACK=Возвращение!
MW2_SPLASHES_COMEBACK_DESC=Вы восстановились после серии смертей.
MW2_SPLASHES_FLAGRETURN=Спасение флага!
MW2_SPLASHES_FLAGRETURN_DESC=%s
MW2_SPLASHES_FLAGPICKUP=Игрок с флагом!
MW2_SPLASHES_FLAGPICKUP_DESC=%s
MW2_SPLASHES_CAPTURE=Позиция захвачена!
MW2_SPLASHES_CAPTURE_DESC=Цель захвачена.
MW2_SPLASHES_DEFEND=Оборона!
MW2_SPLASHES_DEFEND_DESC=Вам удалось защитить цель.
MW2_SPLASHES_ASSAULT=Нападение!
MW2_SPLASHES_ASSAULT_DESC=Вы убили защитника.
MW2_SPLASHES_PLANT=Диверсант!
MW2_SPLASHES_PLANT_DESC=Вы заложили бомбу.
MW2_SPLASHES_DEFUSE=Герой!
MW2_SPLASHES_DEFUSE_DESC=Вы обезвредили бомбу.
MW2_SPLASHES_SAB_OVERTIME=Дополнительное время!
MW2_SPLASHES_SAB_OVERTIME_DESC=Ближайшая к бомбе база будет уничтожена.
MW2_SPLASHES_MARTYRDOM_DESC=После смерти вы уроните гранату.
MW2_SPLASHES_FINALSTAND_DESC=Когда вас убьют, вы получите еще один шанс.
MW2_SPLASHES_ENDGAME_DESC=Ближайшие пару секунд у вас будет дополнительное здоровье.
MW2_SPLASHES_C4DEATH_DESC=Перед смертью оттолкните заряд С4.
MW2_SPLASHES_KNIFETHROW_DESC=Вы убили противника метательным ножом.
MW2_SPLASHES_KNIFETHROW=В яблочко!
MW2_SPLASHES_HIJACKER_DESC=Захвачен вражеский контейнер со снабжением.
MW2_SPLASHES_HIJACKER=Захватчик!
MW2_SPLASHES_HIJACKED=%s похищает вашу гуманитарную помощь.
MW2_SPLASHES_DEFCON_LOWER=БОЕВАЯ ГОТОВНОСТЬ снижена!
MW2_SPLASHES_DEFCON_RAISE=БОЕВАЯ ГОТОВНОСТЬ повышена.
MW2_SPLASHES_DEFCON_LOWER_DESC=Требования к наградам повышены.
MW2_SPLASHES_DEFCON_RAISE_DESC=Требования к наградам снижены.
MW2_SPLASHES_DEFCON_5=БОЕВАЯ ГОТОВНОСТЬ 5
MW2_SPLASHES_DEFCON_4=Боевая готовность: 4.
MW2_SPLASHES_DEFCON_3=БОЕВАЯ ГОТОВНОСТЬ 3
MW2_SPLASHES_DEFCON_2=БОЕВАЯ ГОТОВНОСТЬ 2
MW2_SPLASHES_DEFCON_1=БОЕВАЯ ГОТОВНОСТЬ 1
MW2_SPLASHES_DEFCON_5_DESC=БОЕВАЯ ГОТОВНОСТЬ 5
MW2_SPLASHES_DEFCON_4_DESC=Бой начинается!
MW2_SPLASHES_DEFCON_3_DESC=Спецгруз доставлен!
MW2_SPLASHES_DEFCON_2_DESC=Изменение в наградах за серию!
MW2_SPLASHES_DEFCON_1_DESC=За захват цели очки начисляются вдвойне!
MW2_SPLASHES_COMBATHIGH_DESC=Ненадолго повышено здоровье.
MW2_SPLASHES_RESTED=Увеличение ежедневного приобретения опыта!
MW2_SPLASHES_RESTED_DESC=Каждый день вы получаете дополнительные очки опыта!
MW2_SPLASHES_RESTED_DONE=Начислены дополнительные очки опыта за день.
MW2_SPLASHES_RESTED_DONE_DESC=Получены дополнительные очки опыта.
MW2_SPLASHES_VIP=Вы теперь VIP.
MW2_SPLASHES_STUCK_SEMTEX=Прилип!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Вы поразили противника пластидом!
MW2_SPLASHES_HEROIC=Подвиг!
MW2_SPLASHES_HEROIC_DESC=Вы воспользовались последним шансом и захватили цель!
MW2_SPLASHES_DENIED=Стоп!
MW2_SPLASHES_DENIED_DESC=Вы прервали тактическую высадку противника!
MW2_SPLASHES_DESTROYED_INSERTION=Высадка десанта прервана.
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=забрал ваш ящик!
MW2_SPLASHES_REVIVER_DESC=Вы реанимировали товарища по команде.
MW2_SPLASHES_REVIVER=Реаниматор!
MW2_SPLASHES_GIVEAWAY_SENTRY=...захвачено сторожевое орудие.
MW2_SPLASHES_GIVEAWAY_AIRDROP=забрал сброшенную награду.
MW2_SPLASHES_SEMTEX_STUCK=Вас поразили пластидом.
MW2_SPLASHES_ONE_SHOT_KILL=Убийство одним выстрелом
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Один выстрел... Один труп
MW2_SPLASHES_NINJA_DEFUSE=Ниндзя
MW2_SPLASHES_NINJA_DEFUSE_DESC=Хитро - хитро...
MW2_SPLASHES_COPYCAT_DESC=Похитить класс убийцы во время просмотра повтора смерти.
MW2_SPLASHES_COPIED=Класс скопирован!
MW2_SPLASHES_REVIVED=Вас реанимировали.
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Остался один!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Остался один!
MW2_SPLASHES_SHIELDASSIST=Контроль над толпой!
MW2_SPLASHES_SHIELDASSIST_DESC=Вы мастер разрушения.
MW2_SPLASHES_DESTROYED_HELICOPTER=Вертолет уничтожен!
MW2_SPLASHES_DESTROYED_PAVELOW="Пейв лоу" уничтожен!
MW2_SPLASHES_DESTROYED_UAV=БПЛА уничтожен!
MW2_SPLASHES_DESTROYED_HARRIER="Харриер" уничтожен!
MW2_SPLASHES_DESTROYED_AC130=AC130 уничтожен!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Вертолет уничтожен!
MW2_SPLASHES_FLAG_RETURN=Флаг спасен!
MW2_SPLASHES_FLAG_CAPTURE=Флаг захвачен!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Ваш флаг захвачен!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Захвачен вражеский флаг!
MW2_SPLASHES_FLAG_PICKUP=Захвачен флаг!
MW2_SPLASHES_CAPTURED_NUKE=Захвачен ядерный заряд!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Захвачен ядерный заряд.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Доступен магазин с повышенной емкостью!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Доступен датчик сердцебиения!
MW2_SPLASHES_UNLOCKED_AKIMBO=Доступно парное оружие!
MW2_SPLASHES_UNLOCKED_THERMAL=Доступен тепловизор!
MW2_SPLASHES_UNLOCKED_EOTECH=Доступен голографический прицел.
MW2_SPLASHES_UNLOCKED_SHOTGUN=Доступен дробовик!
MW2_SPLASHES_GRABBED_THE_FLAG=Флаг захвачен!
MW2_SPLASHES_HIJACKED_SENTRY=Похищена сторожевая пушка.
MW2_SPLASHES_HIJACKED_AIRDROP=Похищен ящик со снабжением.
MW2_SPLASHES_BOMB_PLANTED=Бомба заложена!
MW2_SPLASHES_BOMB_DEFUSED=Бомба обезврежена!
MW2_SPLASHES_TIMEADDED=Дополнительное время!
MW2_SPLASHES_GTNW_OVERTIME=Внезапная смерть!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Нет возрождений.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Цель уничтожена!
MW2_SPLASHES_SAVED_OBJECTIVE=Цель защищена!
MW2_SPLASHES_CAPTURED_HQ=Штаб захвачен!
MW2_SPLASHES_DESTROYED_HQ=Штаб разрушен!
MW2_SPLASHES_BOMB_TAKEN=Бомба взята!
MW2_SPLASHES_BOMB_DROPPED=Бомба брошена!
MW2_SPLASHES_KILLED_CARRIER=Противник с бомбой убит!
MW2_SPLASHES_SHAREPACKAGE=Поделиться снабжением!
MW2_SPLASHES_SHAREPACKAGE_DESC=Ваш товарищ по команде отбил у врага ящик со снабжением!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Беспилотник восстановлен!
MW2_SPLASHES_FLAGS_CAPTURE=Захватывает флаг!
MW2_SPLASHES_FLAG_ASSAULT=Нападение на флаг!
MW2_SPLASHES_FLAG_DEFEND=Защита флага!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Вы убили защитника флага.
MW2_SPLASHES_FLAG_DEFEND_DESC=Вам удалось защитить флаг.
MW2_SPLASHES_FLAG_CAPTURED=Флаг захвачен!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Вы захватили вражеский флаг.
MW2_SPLASHES_SECURED_POSITION=Позиция захвачена!
MW2_SPLASHES_SECURED_POSITION_A=Объект А захвачен!
MW2_SPLASHES_SECURED_POSITION_B=Объект B захвачен!
MW2_SPLASHES_SECURED_POSITION_C=Объект С захвачен!
MW2_SPLASHES_TIME_ADDED=Дополнительное время!
MW2_SPLASHES_TIME_ADDED_DESC=Зона минирования разрушена. Время увеличено.

# Killstreaks
MW2_KILLSTREAKS_UAV=БПЛА
MW2_KILLSTREAKS_UAV_DESC=Показ противников на мини-карте.
MW2_KILLSTREAKS_AIRSTRIKE=Авиаудар
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Вызов авиаудара по выбранному объекту.
MW2_KILLSTREAKS_HELICOPTER=Вертолет
MW2_KILLSTREAKS_HELICOPTER_DESC=Вызов вертолета поддержки.
MW2_KILLSTREAKS_AC130=AC-130
MW2_KILLSTREAKS_AC130_DESC=Станьте бортовым стрелком AC-130.
MW2_KILLSTREAKS_PREDATOR_MISSILE="Предэйтор"
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Ракета с дистанционным управлением.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Верт. пулемет
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Управление пулеметом ударного вертолета.
MW2_KILLSTREAKS_HELICOPTER_MK19=Вертолетный стрелок
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Управление пулеметом атакующего вертолета на расстоянии.
MW2_KILLSTREAKS_DOUBLE_UAV=Улучшенные БПЛА
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=Ускоренный БПЛА.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Авиаудар
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Вызов направленного авиаудара.
MW2_KILLSTREAKS_AIRDROP=Снабжение
MW2_KILLSTREAKS_AIRDROP_DESC=Вызов доставки произвольной награды за серию или боеприпасов.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Стор. орудие
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Сброс стационарной сторожевой пушки.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Снабжение ("Предэйтор")
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Сброс одноразовой ракеты "Предэйтора".
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE="Харриер"
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Авиаудар "Харриера".
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE="Стелс"
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Авиаудар, не определяемый на картах противника.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Суперавиаудар
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Авиаудар с дополнительным уроном.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Черный ящик вертолета
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Вертолет действует дольше.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Сторожевой вертолет
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Вертолет с сигн. огнями.
MW2_KILLSTREAKS_EMP=ЭМИ
MW2_KILLSTREAKS_EMP_DESC=Временное отключение техники\nи электроники противника.
MW2_KILLSTREAKS_TANK=Танк
MW2_KILLSTREAKS_TANK_DESC=Просто танк.
MW2_KILLSTREAKS_COUNTER_UAV=Глушение БПЛА
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Временное глушение радара противника.
MW2_KILLSTREAKS_PAVELOW="Пейв Лоу"
MW2_KILLSTREAKS_PAVELOW_DESC=Тяжело вооруженный ударный вертолет.
MW2_KILLSTREAKS_NONE=Нет
MW2_KILLSTREAKS_NONE_DESC=Серия убийств не выбрана.
MW2_KILLSTREAKS_AIRDROP_MEGA=Спецгруз
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Вызов доставки четырех произвольных наград за серию или боеприпасов.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Нажмите %s для вызова СПЕЦГРУЗА.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Ядерный заряд
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Закончить игру большим взрывом.
MW2_KILLSTREAKS_SENTRY=Сторожевая пушка

MW2_MP_EARNED_AIRSTRIKE=Нажмите %s для удара с воздуха
MW2_MP_EARNED_AIRDROP=Нажмите %s для вызова ГРУЗА.
MW2_MP_EARNED_SENTRY_AIRDROP=Нажмите %s для сброса СТОРОЖЕВОЙ ПУШКИ.
MW2_MP_EARNED_PREDATOR_AIRDROP=Нажмите %s для вызова "ПРЕДЭЙТОРА"
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Нажмите %s для точечного авиаудара
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Нажмите %s для бомбардировщика "Стелс".
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Нажмите %s, чтобы вызвать "ХАРРИЕР".
MW2_MP_EARNED_SUPER_AIRSTRIKE=Нажмите %s для мощного удара с воздуха
MW2_MP_EARNED_UAV=Нажмите %s для БПЛА
MW2_MP_EARNED_DOUBLE_UAV=Нажмите %s для улучшенного БПЛА
MW2_MP_EARNED_COUNTER_UAV=Нажмите %s для противодействия БПЛА.
MW2_MP_EARNED_HELICOPTER=Нажмите %s, чтобы вызвать УДАРНЫЙ ВЕРТОЛЕТ.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Нажмите %s для вертолетного пулемета.
MW2_MP_EARNED_HELICOPTER_MK19=Нажмите %s для вертолета MK19
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Нажмите %s для черного ящика вертолета
MW2_MP_EARNED_HELICOPTER_FLARES=Нажмите %s для вертолета "Пейв Лоу".
MW2_MP_EARNED_AC130=Нажмите %s для AC130.
MW2_MP_EARNED_PREDATOR_MISSILE=Нажмите %s для ракеты "ПРЕДЭЙТОРА".
MW2_MP_EARNED_NUKE=Нажмите %s для ядерного заряда.
MW2_MP_EARNED_AUTO_SHOTGUN=Нажмите %s для дробовика
MW2_MP_EARNED_AUTO_SENTRY=Нажмите %s, чтобы вызвать доставку сторожевого орудия.
MW2_MP_EARNED_AUTO_SENTRY_GL=Нажмите %s, чтобы вызвать доставку гранатомета.
MW2_MP_EARNED_THUMPER=Нажмите %s для гранатомета М79
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Нажмите %s для вертолета "Литлберд"
MW2_MP_EARNED_EMP=Нажмите %s для ЭМИ-удара.

# Other
MW2_MP_CONNECTED=Игрок %s подключен.
MW2_MP_DISCONNECTED=Игрок %s отключен.
MW2_EXE_LEFTGAME=%s покидает игру

MW2_PLATFORM_RELOAD=Перезарядка
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Мало боеприпасов
MW2_WEAPON_NO_AMMO=Нет боеприпасов

MW2_MPUI_WINNING_CAPS=ВЫ ВЫИГРЫВАЕТЕ
MW2_MPUI_LOSING_CAPS=ВЫ ПРОИГРЫВАЕТЕ
MW2_MPUI_TIED_CAPS=НИЧЬЯ

MW2_CGAME_SB_SCORE=Счет
MW2_CGAME_SB_DEATHS=Смерти
MW2_CGAME_SB_KILLS=Убийства
MW2_CGAME_SB_ASSISTS=Помощь

MW2_PLATFORM_THROWBACKGRENADE=%s кинуть обратно

# Round Starter
MW2_MP_MATCH_STARTING_IN=До начала боя:
MW2_MP_MATCH_RESUMING_IN=До продолжения боя:
  
# Gamemodes
MW2_MPUI_SABOTAGE=Диверсия
MW2_MPUI_DEATHMATCH=Каждый за себя
MW2_MPUI_CAPTURE_THE_FLAG=Захват флага
MW2_MPUI_HEADQUARTERS=Штаб
MW2_MPUI_SEARCH_AND_DESTROY=Бомба
MW2_MPUI_WAR=Командный бой
MW2_MPUI_DOMINATION=Превосходство
MW2_MPUI_ONE_FLAG=ЗФ: один флаг
MW2_MPUI_ARENA=Арена
MW2_MPUI_DD=Уничтожение
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Третья мировая

MW2_MP_OBJ_DM_HINT=Уничтожьте других игроков
MW2_MP_OBJ_WAR_HINT=Нейтрализуйте игроков противника
MW2_OBJECTIVES_WAR_HINT=Нейтрализуйте игроков противника.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Уничтожьте объект A или Б.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Защищайте объекты A и Б.
MW2_OBJECTIVES_SAB_HINT=Уничтожьте вражеский объект.
MW2_OBJECTIVES_DOM_HINT=Захватывайте флаги и защищайте их.
MW2_OBJECTIVES_DM_HINT=Уничтожьте других игроков
MW2_OBJECTIVES_KOTH_HINT=Удерживайте штаб.
MW2_OBJECTIVES_CTF_HINT=Захватите вражеский флаг.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Захватите вражеский флаг.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Защищайте флаг.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Уничтожьте объекты А и В.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Защищайте объекты A и Б.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Убейте важную персону, не дав добраться в точку эвакуации.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Защитите важную персону, помогая добраться в точку эвакуации.
MW2_OBJECTIVES_ARENA_HINT=Уничтожьте противника или захватите флаг.
MW2_OBJECTIVES_GTNW_HINT=Захватите ядерный чемоданчик.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Захватите флаг противника.

# Round Ender
MW2_MP_DRAW=Ничья
MW2_MP_VICTORY=Победа!
MW2_MP_DEFEAT=Поражение!
MW2_MP_ROUND_DRAW=Ничья
MW2_MP_ROUND_WIN=Победа в раунде
MW2_MP_ROUND_LOSS=Поражение в раунде
MW2_MP_HALFTIME=Конец полупериода
MW2_MP_OVERTIME=Дополнительное время
MW2_MP_MATCH_BONUS_IS=Призовые очки: %s

MW2_MP_SCORE_LIMIT_REACHED=Достигнут лимит очков
MW2_MP_ROUND_LIMIT_REACHED=Все раунды завершены
MW2_MP_TIME_LIMIT_REACHED=Время вышло

MW2_MP_OPFOR_ELIMINATED=Сепаратисты уничтожены
MW2_MP_OPFOR_FORFEITED=Сепаратисты отступили
MW2_MP_SPETSNAZ_ELIMINATED=Спецназ уничтожен
MW2_MP_SPETSNAZ_FORFEITED=Спецназ отступил
MW2_MP_US_ARMY_ELIMINATED=Армия США уничтожена
MW2_MP_US_ARMY_FORFEITED=Армия США отступила
MW2_MP_MILITIA_ELIMINATED=Ополчение уничтожено
MW2_MP_MILITIA_FORFEITED=Ополчение отступило
MW2_MP_TF141_ELIMINATED=ОТГ-141 уничтожена
MW2_MP_TF141_FORFEITED=ОТГ-141 отступила
MW2_MP_SEALS_ELIMINATED=\"Морские котики\" уничтожены
MW2_MP_SEALS_FORFEITED=\"Морские котики\" отступили