#---------- CoD HUD Settings | English
# Translator: Moka

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=Client Settings
CoDHUD.Server=Server Settings

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.Admin.RoundStart=Round Start

CoDHUD.RoundStart.Gamemode=Gamemode Select
CoDHUD.RoundStart.Start=Begin Round Start Process
CoDHUD.RoundStart.Admin=This is an Admin-only process!

CoDHUD.RoundStart.Notice=Are you sure you want to start a new round?\nAll scores will be reset, and all players will respawn.
CoDHUD.RoundStart.Yes=Begin Round
CoDHUD.RoundStart.No=Cancel

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Enable "End of Match"
CoDHUD.Admin.EndScreen.desc=Enables an "end of match" system once the score limit is reached.

CoDHUD.Admin.EndScreen.StartNext=Start Next Round after End of Match
CoDHUD.Admin.EndScreen.StartNext.desc=If enabled, once the end of match duration expires, a new round will begin.\nIf disabled, all players will respawn normally.

CoDHUD.Admin.EndScreen.Scorelimit=Score Limit
CoDHUD.Admin.EndScreen.Scorelimit.desc=Sets the maximum score limit present on the Score counter.

CoDHUD.Admin.FriendlyFire=Allow Friendly Fire
CoDHUD.Admin.FriendlyFire.desc=If enabled, players on the same faction can damage one another.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Restrict Factions and HUD Type
CoDHUD.Admin.RestrictType.desc=Choose which CoD type to restrict users to.\nIf set to 'Open', then any faction and HUD type can be used by anyone.

CoDHUD.Type.Open=Open
CoDHUD.Type.CoD4=Call of Duty 4: Modern Warfare
CoDHUD.Type.WaW=Call of Duty: World at War
CoDHUD.Type.MW2=Call of Duty: Modern Warfare 2
CoDHUD.Type.BO=Call of Duty: Black Ops
CoDHUD.Type.MW3=Call of Duty: Modern Warfare 3
CoDHUD.Type.BO2=Call of Duty: Black Ops II

CoDHUD.Type.Open.desc=Allow users to pick any faction and HUD type from any CoD title.
CoDHUD.Type.Closed.desc=Restrict users to only factions and the HUD type from this CoD title.

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Faction Select
CoDHUD.Faction.Select.desc=Choose which faction to represent.\nAffects your Friend-or-Foe status and changes your announcer and theme to match the faction.
CoDHUD.Faction.SelectAgain=You can change faction in the Spawnmenu under CoD HUD > Faction Select, or by clicking the "CoD HUD" option in the Context Menu.

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Quick-Access

CoDHUD.Quick.DisableHUD=Quick-Disable All HUD Options
CoDHUD.Quick.DisableHUD.desc=Disables all CoD HUD options.

CoDHUD.Quick.DisableAudio=Quick-Disable All Audio Options
CoDHUD.Quick.DisableAudio.desc=Disables all CoD Audio options.

# ---------[ AUDIO-RELATED ]---------
CoDHUD.Audio=Audio Settings
CoDHUD.Audio.Announcer=Announcer
CoDHUD.Audio.Music=Music

CoDHUD.Audio.Announcer.Enable=Enable Announcer Voice
CoDHUD.Audio.Announcer.Enable.desc=Enables the announcer.

CoDHUD.Audio.Announcer.English=Force English Announcer
CoDHUD.Audio.Announcer.English.desc=Forces the English announcer voices to play, regardless of game language.

CoDHUD.Audio.Music.Enable=Enable Music
CoDHUD.Audio.Music.Enable.desc=Enables music.

CoDHUD.Audio.Music.Ambient=Enable Ambient Music
CoDHUD.Audio.Music.Ambient.desc=Enables ambient music playing in the background.

# ---------[ HUD-RELATED ]---------
CoDHUD.Enable.Options=HUD Settings

# Multiple
CoDHUD.HUD.Outline=Outlined Text
CoDHUD.HUD.Outline.desc=Activates outlined texts on some elements to make them easier to read in really bright areas.

CoDHUD.HUD.Sound=Play SFX
CoDHUD.HUD.Sound.desc=Plays associated sound effects if the HUD Type supports it.

CoDHUD.HUD.Time.Total=Active Time
CoDHUD.HUD.Time.Total.desc=How long the variable remains on-screen after fully fading in before it fades back out.

CoDHUD.HUD.Time.Fadein=Fade-in Time
CoDHUD.HUD.Time.Fadein.desc=How long it takes for this variable to fade in.

CoDHUD.HUD.Time.Fadeout=Fade-out Time
CoDHUD.HUD.Time.Fadeout.desc=How long it takes for this variable to fade out.

# Scoreboard
CoDHUD.HUD.Scoreboard=Scoreboard

CoDHUD.HUD.Scoreboard.Enable=Enable Scoreboard
CoDHUD.HUD.Scoreboard.Enable.desc=Enables a themed Scoreboard. Displays the factions currently occupied by all players.

# Score Counter
CoDHUD.HUD.Scorecounter=Score Counter

CoDHUD.HUD.Scorecounter.Enable=Enable Score Counter
CoDHUD.HUD.Scorecounter.Enable.desc=Enables a themed server timer, faction icon and score counters.\nSome HUD Types won't display the faction icon.

# Medals
CoDHUD.HUD.Medals=Medals

CoDHUD.HUD.Medals.Enable=Enable Medals
CoDHUD.HUD.Medals.Enable.desc=Enables themed medals, achieved by performing certain actions, such as quick kills or headshots.\nAlso activates associated sound effects.\nNote that some HUD Types have text only, while some have text and icons.

CoDHUD.HUD.Medals.Speedup=Faster if long queue
CoDHUD.HUD.Medals.Speedup.desc=Speeds up the medal queue if there's many of them queued up at once.\nDepending on the HUD Type, also disables the associated SFX if there's more than 3 medals queued.

# Kill Feed
CoDHUD.HUD.Options.Killfeed=Kill Feed

CoDHUD.HUD.Killfeed.Enable=Enable Kill Feed
CoDHUD.HUD.Killfeed.Enable.desc=Enables a themed kill feed.

# Minimap
CoDHUD.HUD.Minimap=Minimap

CoDHUD.HUD.Minimap.Enable=Enable Minimap
CoDHUD.HUD.Minimap.Enable.desc=Enables a themed minimap.

# Hitmarker
CoDHUD.HUD.Hitmarker=Hitmarker

CoDHUD.HUD.Hitmarker.Enable=Enable Hitmarker
CoDHUD.HUD.Hitmarker.Enable.desc=Enables a themed hitmarker and its associated hit sound.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Weapon Info

CoDHUD.HUD.WeaponInfo.Enable=Enable Weapon Info
CoDHUD.HUD.WeaponInfo.Enable.desc=Enables a themed weapon info tab, displaying the weapon name and ammo counter.\nSome HUD Types incorporate the compass here too.

CoDHUD.HUD.WeaponPrompts.Enable=Enable Weapon Prompts
CoDHUD.HUD.WeaponPrompts.Enable.desc=Enables themed weapon prompts, such as low ammo notifications.

# XP Counter
CoDHUD.HUD.XP=XP Prompt

CoDHUD.HUD.XP.Enable=Enable XP Prompt
CoDHUD.HUD.XP.Enable.desc=Enables a themed XP prompt.

# Target ID / IFF
CoDHUD.HUD.IFF=Identify Friend-or-Foe

CoDHUD.HUD.IFF.Enable=Enable IFF
CoDHUD.HUD.IFF.Enable.desc=Enables a themed "Identify Friend-or-Foe" system, displaying the target's name above their heads when aiming near them.

# Death Icon
CoDHUD.HUD.DeathIcon=Death Icon

CoDHUD.HUD.DeathIcon.Enable=Enable Death Icon
CoDHUD.HUD.DeathIcon.Enable.desc=Enables the death icon, displayed where any player on the same faction dies.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Enable Chat
CoDHUD.HUD.Chat.Enable.desc=Enables a themed chat.

# Challenges
CoDHUD.HUD.Challenges=Challenges

CoDHUD.HUD.Challenges.Enable=Enable Challenge Prompts
CoDHUD.HUD.Challenges.Enable.desc=Enables themed challenge prompts.\nDoes not affect the tracking of challenges, nor the unlocking of them.