#---------- MW2 HUD Settings | English
# Translator: Moka

# Client
MW2HUD.Client=[ Client Settings ]
MW2HUD.Server=[ Server Settings ]

# Factions
MW2HUD.Faction.Select=Faction Select
MW2HUD.Faction.Select.desc=Choose which faction to represent.\nAffects your Friend-or-Foe status and changes your announcer and theme to match the faction.

MW2HUD.Faction.SelectAgain=You can change faction in the Spawnmenu under Options > MW2 > Client Settings.

# Sounds
MW2HUD.Audio=Audio Options

MW2HUD.Audio.Announcer=Enable Announcer Voice
MW2HUD.Audio.Announcer.desc=Enables the announcer.

MW2HUD.Audio.Music=Enable Music
MW2HUD.Audio.Music.desc=Enables music.

MW2HUD.Audio.Announcer.English=Force English Announcer
MW2HUD.Audio.Announcer.English.desc=Forces the English announcer voices to play, regardless of game language.

# HUD
MW2HUD.Enable.Options=HUD Options

MW2HUD.Enable.AutoDisableInVeh=Auto-Disable All in Vehicles
MW2HUD.Enable.AutoDisableInVeh.desc=Disables all HUD options (except Kill Messages, XP Counter and Target ID) when operating any vehicle.

MW2HUD.Enable.Score=Enable Score Counter
MW2HUD.Enable.Score.desc=Enables the server timer, faction icon and score counters.
MW2HUD.Enable.Score.tip=Tip: If disabled, recommend to disable the Announcer Voice and Music as well.

MW2HUD.Enable.Splash=Enable Kill Messages
MW2HUD.Enable.Splash.desc=Enables the kill messages, and disables their associated sounds.

MW2HUD.Enable.Splash.Outline=Outlines for Kill Messages
MW2HUD.Enable.Splash.Outline.desc=Enables outlined text on the kill messages.

MW2HUD.Enable.Feed=Enable Kill Feed
MW2HUD.Enable.Feed.desc=Enables the kill feed.

MW2HUD.Enable.Map=Enable Minimap
MW2HUD.Enable.Map.desc=Enables the minimap.

MW2HUD.Enable.Hitmarker=Enable Hitmarker
MW2HUD.Enable.Hitmarker.desc=Enables the hitmarker and its associated hit sound.

MW2HUD.Enable.Weapon=Enable Weapon Info
MW2HUD.Enable.Weapon.desc=Enables the weapon name, ammo counter and compass.\n\nRe-enables the default HL2 ammo counter.

MW2HUD.Enable.XP=Enable XP Counter
MW2HUD.Enable.XP.desc=Enables the XP counter.

MW2HUD.Enable.Target=Enable Target ID
MW2HUD.Enable.Target.desc=Enables the target's name above their head when aiming near them.

MW2HUD.Enable.DeathIcon=Enable Death Icon
MW2HUD.Enable.DeathIcon.desc=Enables the death icon.

MW2HUD.Enable.Prompt=Enable Weapon Prompts
MW2HUD.Enable.Prompt.desc=Enables the weapon prompts, including "Reload", "Low Ammo" and "No Ammo".

# Round Start
MW2HUD.RoundStart=Round Start

MW2HUD.RoundStart.Gamemode=Gamemode Select
MW2HUD.RoundStart.Start=Begin Round Start Process
MW2HUD.RoundStart.Admin=This is an Admin-only process!

MW2HUD.RoundStart.Notice=Are you sure you want to start a new round?\nAll scores will be reset, and all players will respawn.
MW2HUD.RoundStart.Yes=Yes, let's do this
MW2HUD.RoundStart.No=No

# Admin
MW2HUD.Admin=Admin Settings

MW2HUD.Admin.Score=Score Limit
MW2HUD.Admin.Score.desc=Sets the maximum score limit present on the Score counter.\nSet to 0 for "Unlimited", i.e. always lowest value.