#---------- MW2 HUD | English
# Translator: Original Game

# Weapons
MW2_CHALLENGE_MARKSMAN_1=: Marksman I
MW2_CHALLENGE_MARKSMAN_2=: Marksman II
MW2_CHALLENGE_MARKSMAN_3=: Marksman III
MW2_CHALLENGE_MARKSMAN_4=: Marksman IV
MW2_CHALLENGE_MARKSMAN_5=: Marksman V
MW2_CHALLENGE_MARKSMAN_6=: Marksman VI
MW2_CHALLENGE_MARKSMAN_7=: Marksman VII
MW2_CHALLENGE_MARKSMAN_8=: Marksman VIII
MW2_CHALLENGE_MARKSMAN_9=: Marksman IX
MW2_CHALLENGE_MARKSMAN_10=: Marksman X
MW2_CHALLENGE_EXPERT_1=: Expert I
MW2_CHALLENGE_EXPERT_2=: Expert II
MW2_CHALLENGE_EXPERT_3=: Expert III
MW2_CHALLENGE_EXPERT_4=: Expert IV
MW2_CHALLENGE_EXPERT_5=: Expert V
MW2_CHALLENGE_EXPERT_6=: Expert VI
MW2_CHALLENGE_EXPERT_7=: Expert VII
MW2_CHALLENGE_EXPERT_8=: Expert VIII
MW2_CHALLENGE_EXPERT_9=: Expert IX
MW2_CHALLENGE_EXPERT_10=: Expert X
MW2_CHALLENGE_LEVEL_1=: I
MW2_CHALLENGE_LEVEL_2=: II
MW2_CHALLENGE_LEVEL_3=: III
MW2_CHALLENGE_LEVEL_4=: IV
MW2_CHALLENGE_LEVEL_5=: V
MW2_CHALLENGE_LEVEL_6=: VI
MW2_CHALLENGE_LEVEL_7=: VII
MW2_CHALLENGE_LEVEL_8=: VIII
MW2_CHALLENGE_LEVEL_9=: IX
MW2_CHALLENGE_LEVEL_10=: X
MW2_CHALLENGE_GET_N_KILLS=Get %d kills with this weapon.
MW2_CHALLENGE_GET_N_HEADSHOTS=Get %d headshots with this weapon.
