#---------- MW2 HUD Settings | English
# Translator: Moka

# Client
MW2HUD.Client=Client Settings

# Factions
MW2HUD.Faction.Select=Faction Select
MW2HUD.Faction.Select.desc=Choose which faction to represent.\nAffects your Friend-or-Foe status and changes your announcer and theme to match the faction.

MW2HUD.Faction.SelectAgain=You can change faction in the Spawnmenu under Options > MW2 > Client Settings.

# Disable Options
MW2HUD.Disable=Hide Options
MW2HUD.Disable.desc=Hover over the options to see what exactly is being hidden.

MW2HUD.Disable.OnFoot=On Foot
MW2HUD.Disable.InVeh=While Driving

MW2HUD.Disable.Map=Hide Minimap
MW2HUD.Disable.Map.desc=Hides the minimap.

MW2HUD.Disable.Score=Hide Score Counter
MW2HUD.Disable.Score.desc=Hides the server timer, faction icon and score counters.

MW2HUD.Disable.Weapon=Hide Weapon Info
MW2HUD.Disable.Weapon.desc=Hides the weapon name, ammo counter and compass.\n\nRe-enables the default HL2 ammo counter.

MW2HUD.Disable.Splash=Hide Kill Messages
MW2HUD.Disable.Splash.desc=Hides the kill messages, and disables their associated sounds.

MW2HUD.Disable.XP=Hide XP Counter
MW2HUD.Disable.XP.desc=Hides the XP counter.

MW2HUD.Disable.Prompt=Hide Weapon Prompts
MW2HUD.Disable.Prompt.desc=Hides the weapon prompts, including "Reload", "Low Ammo" and "No Ammo".

# Sounds
MW2HUD.Audio=Audio Options

MW2HUD.Audio.Announcer=Enable Announcer
MW2HUD.Audio.Announcer.desc=Enables the announcer.

MW2HUD.Audio.Announcer.English=Force English Announcer
MW2HUD.Audio.Announcer.English.desc=Forces the English announcer voices to play, regardless of game language.

MW2HUD.Audio.Music=Enable Music
MW2HUD.Audio.Music.desc=Enables music.

# Admin
MW2HUD.Admin=Admin Settings

MW2HUD.Admin.Score=Score Limit
MW2HUD.Admin.Score.desc=Sets the maximum score limit present on the Score counter.\nSet to 0 for "Unlimited", i.e. always lowest value.