#---------- MW2 HUD | English
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Army Rangers
MW2_MP_SEALS_UDT_NAME=Navy SEALs
MW2_MP_MILITIA_NAME=Militia
MW2_MP_TASKFORCE_NAME=Task Force 141
MW2_MP_OPFOR_NAME=OpFor
MW2_MP_SPETSNAZ_NAME=Spetsnaz

MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_SEALS_UDT_SHORT_NAME=SEALs
MW2_MP_MILITIA_SHORT_NAME=Militia
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_OPFOR_SHORT=OpFor
MW2_MPUI_SPETSNAZ_SHORT=Spetsnaz

# Splashes
MW2_SPLASHES_HEADSHOT=Headshot!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Assisted Suicide!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=You have assisted the suicide of an enemy.
MW2_SPLASHES_LONGSHOT=Longshot!
MW2_SPLASHES_LONGSHOT_DESC=Nice kill from a distance!
MW2_SPLASHES_EXECUTION=Execution!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Avenger!
MW2_SPLASHES_AVENGER_DESC=You've avenged a team-mate.
MW2_SPLASHES_DEFENDER=Rescuer!
MW2_SPLASHES_DEFENDER_DESC=You've rescued a team-mate.
MW2_SPLASHES_POSTHUMOUS=Afterlife!
MW2_SPLASHES_POSTHUMOUS_DESC=You killed an enemy after you died.
MW2_SPLASHES_REVENGE=Payback!
MW2_SPLASHES_REVENGE_DESC=You've taken revenge.
MW2_SPLASHES_DOUBLEKILL=Double Kill!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Triple Kill!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Multi-Kill!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=First Blood!
MW2_SPLASHES_FIRSTBLOOD_DESC=You got the first kill.
MW2_SPLASHES_BUZZKILL=Buzzkill!
MW2_SPLASHES_BUZZKILL_DESC=Stopped enemy short of a killstreak.
MW2_SPLASHES_COMEBACK=Comeback!
MW2_SPLASHES_COMEBACK_DESC=You've recovered from a streak of deaths.
MW2_SPLASHES_FLAGRETURN=Flag Return!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Flag Runner!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Position Secure!
MW2_SPLASHES_CAPTURE_DESC=You've taken an objective.
MW2_SPLASHES_DEFEND=Defense!
MW2_SPLASHES_DEFEND_DESC=You defended the objective.
MW2_SPLASHES_ASSAULT=Offense!
MW2_SPLASHES_ASSAULT_DESC=You killed a defender.
MW2_SPLASHES_PLANT=Saboteur!
MW2_SPLASHES_PLANT_DESC=You planted the bomb.
MW2_SPLASHES_DEFUSE=Hero!
MW2_SPLASHES_DEFUSE_DESC=You defused the bomb.
MW2_SPLASHES_SAB_OVERTIME=Overtime!
MW2_SPLASHES_SAB_OVERTIME_DESC=The base nearest to the bomb will be destroyed.
MW2_SPLASHES_MARTYRDOM_DESC=You'll drop a live grenade upon death.
MW2_SPLASHES_FINALSTAND_DESC=You'll get a second chance when you're down.
MW2_SPLASHES_ENDGAME_DESC=You've got extra health for the next few seconds.
MW2_SPLASHES_C4DEATH_DESC=Pull out C4 before you die.
MW2_SPLASHES_KNIFETHROW_DESC=You killed an enemy with a throwing knife.
MW2_SPLASHES_KNIFETHROW=Bullseye!
MW2_SPLASHES_HIJACKER_DESC=You captured an enemy supply crate.
MW2_SPLASHES_HIJACKER=Hijacker!
MW2_SPLASHES_HIJACKED=%s captured your supply crate.
MW2_SPLASHES_DEFCON_LOWER=DEFCON Lowered!
MW2_SPLASHES_DEFCON_RAISE=DEFCON Raised
MW2_SPLASHES_DEFCON_LOWER_DESC=Killstreaks upgraded!
MW2_SPLASHES_DEFCON_RAISE_DESC=Killstreaks downgraded.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Match starting!
MW2_SPLASHES_DEFCON_3_DESC=Emergency airdrop incoming!
MW2_SPLASHES_DEFCON_2_DESC=Killstreaks rollover!
MW2_SPLASHES_DEFCON_1_DESC=Double points for objectives!
MW2_SPLASHES_COMBATHIGH_DESC=Increased health for a short time.
MW2_SPLASHES_RESTED=Daily XP Boost!
MW2_SPLASHES_RESTED_DESC=Earning your daily bonus XP!
MW2_SPLASHES_RESTED_DONE=Daily XP Boost Done.
MW2_SPLASHES_RESTED_DONE_DESC=Bonus XP acquired.
MW2_SPLASHES_VIP=You are the VIP
MW2_SPLASHES_STUCK_SEMTEX=Stuck!
MW2_SPLASHES_STUCK_SEMTEX_DESC=You stuck an enemy with Semtex!
MW2_SPLASHES_HEROIC=Heroic!
MW2_SPLASHES_HEROIC_DESC=You captured an objective in last stand!
MW2_SPLASHES_DENIED=Denied!
MW2_SPLASHES_DENIED_DESC=You destroyed an enemy tactical insertion!
MW2_SPLASHES_DESTROYED_INSERTION=Blocked your TI!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Took your crate!
MW2_SPLASHES_REVIVER_DESC=You revived a fallen teamate.
MW2_SPLASHES_REVIVER=Reviver!
MW2_SPLASHES_GIVEAWAY_SENTRY=...took a Sentry Gun
MW2_SPLASHES_GIVEAWAY_AIRDROP=... took an airdropped Killstreak.
MW2_SPLASHES_SEMTEX_STUCK=Stuck you with Semtex
MW2_SPLASHES_ONE_SHOT_KILL=One Shot Kill
MW2_SPLASHES_ONE_SHOT_KILL_DESC=One shot... one kill
MW2_SPLASHES_NINJA_DEFUSE=Ninja Defuse
MW2_SPLASHES_NINJA_DEFUSE_DESC=Sneaky sneaky...
MW2_SPLASHES_COPYCAT_DESC=Steal your killer's class during killcam.
MW2_SPLASHES_COPIED=Copied class!
MW2_SPLASHES_REVIVED=Revived You
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Last Alive!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Last Alive!
MW2_SPLASHES_SHIELDASSIST=Crowd Control!
MW2_SPLASHES_SHIELDASSIST_DESC=You make an excellent distraction.
MW2_SPLASHES_DESTROYED_HELICOPTER=Destroyed Helicopter!
MW2_SPLASHES_DESTROYED_PAVELOW=Destroyed Pavelow!
MW2_SPLASHES_DESTROYED_UAV=Destroyed UAV!
MW2_SPLASHES_DESTROYED_HARRIER=Destroyed Harrier!
MW2_SPLASHES_DESTROYED_AC130=Destroyed AC130!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Destroyed Gunship!
MW2_SPLASHES_FLAG_RETURN=Returned Flag!
MW2_SPLASHES_FLAG_CAPTURE=Captured Flag!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Took Your Flag!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Took Enemy Flag!
MW2_SPLASHES_FLAG_PICKUP=Took the Flag!
MW2_SPLASHES_CAPTURED_NUKE=Nuke Captured!
MW2_SPLASHES_DESC_CAPTURED_NUKE=You've captured the nuke.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Extended Mags unlocked!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Heartbeat Sensor unlocked!
MW2_SPLASHES_UNLOCKED_AKIMBO=Akimbo unlocked!
MW2_SPLASHES_UNLOCKED_THERMAL=Thermal Scope unlocked!
MW2_SPLASHES_UNLOCKED_EOTECH=Holographic Sight unlocked!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Shotgun unlocked!
MW2_SPLASHES_GRABBED_THE_FLAG=Grabbed the flag!
MW2_SPLASHES_HIJACKED_SENTRY=Took Your Sentry!
MW2_SPLASHES_HIJACKED_AIRDROP=Took Your Crate!
MW2_SPLASHES_BOMB_PLANTED=Planted Bomb!
MW2_SPLASHES_BOMB_DEFUSED=Defused Bomb!
MW2_SPLASHES_TIMEADDED=Time Added!
MW2_SPLASHES_GTNW_OVERTIME=Sudden Death!
MW2_SPLASHES_GTNW_OVERTIME_DESC=No respawning.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Destroyed Objective!
MW2_SPLASHES_SAVED_OBJECTIVE=Saved Objective!
MW2_SPLASHES_CAPTURED_HQ=Captured HQ!
MW2_SPLASHES_DESTROYED_HQ=Destroyed HQ!
MW2_SPLASHES_BOMB_TAKEN=Took Bomb!
MW2_SPLASHES_BOMB_DROPPED=Dropped Bomb!
MW2_SPLASHES_KILLED_CARRIER=Killed Bomb Carrier!
MW2_SPLASHES_SHAREPACKAGE=Share Package!
MW2_SPLASHES_SHAREPACKAGE_DESC=A teammate saved your Care Package from the enemy!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Restored UAV!
MW2_SPLASHES_FLAGS_CAPTURE=Captured a Flag!
MW2_SPLASHES_FLAG_ASSAULT=Flag Assault!
MW2_SPLASHES_FLAG_DEFEND=Flag Defend!
MW2_SPLASHES_FLAG_ASSAULT_DESC=You killed a flag defender.
MW2_SPLASHES_FLAG_DEFEND_DESC=You defended the flag.
MW2_SPLASHES_FLAG_CAPTURED=Flag Captured!
MW2_SPLASHES_FLAG_CAPTURED_DESC=You've captured the enemy flag.
MW2_SPLASHES_SECURED_POSITION=Secured Position!
MW2_SPLASHES_SECURED_POSITION_A=Secured A!
MW2_SPLASHES_SECURED_POSITION_B=Secured B!
MW2_SPLASHES_SECURED_POSITION_C=Secured C!
MW2_SPLASHES_TIME_ADDED=Time Extension!
MW2_SPLASHES_TIME_ADDED_DESC=Bomb site destroyed. Game time extended.

# Killstreaks
MW2_KILLSTREAKS_UAV=UAV
MW2_KILLSTREAKS_UAV_DESC=Shows enemies on the minimap.
MW2_KILLSTREAKS_AIRSTRIKE=Airstrike
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Call in an air strike on selected position.
MW2_KILLSTREAKS_HELICOPTER=Attack Helicopter
MW2_KILLSTREAKS_HELICOPTER_DESC=Call in a support helicopter.
MW2_KILLSTREAKS_AC130=AC130
MW2_KILLSTREAKS_AC130_DESC=Be the gunner of an AC130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Predator Missile
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Remote control missile.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Chopper Gunner
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Be the gunner of an attack helicopter.
MW2_KILLSTREAKS_HELICOPTER_MK19=Helicopter Gunner
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Remote control of a helicopter GL.
MW2_KILLSTREAKS_DOUBLE_UAV=Advanced UAV
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=UAV with faster sweep time.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Precision Airstrike
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Call in a directional airstrike.
MW2_KILLSTREAKS_AIRDROP=Care Package
MW2_KILLSTREAKS_AIRDROP_DESC=Airdrop a random killstreak or ammo.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Sentry Gun
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Airdrop a placeable Sentry Gun.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Care Package (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Drops a single use predator missile.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Harrier Strike
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Airstrike with a hovering Harrier.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Stealth Bomber
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Airstrike undetectable on enemy maps.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Super Airstrike
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Airstrike with some extra kick.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Helicopter Blackbox
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Longer lasting helicopter.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Defensive Helicopter
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Helicopter with flares.
MW2_KILLSTREAKS_EMP=EMP
MW2_KILLSTREAKS_EMP_DESC=Temporarily disables enemy electronics.
MW2_KILLSTREAKS_TANK=Tank
MW2_KILLSTREAKS_TANK_DESC=A tank.
MW2_KILLSTREAKS_COUNTER_UAV=Counter-UAV
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Temporarily disables enemy radar.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Heavily armored assault helicopter.
MW2_KILLSTREAKS_NONE=None
MW2_KILLSTREAKS_NONE_DESC=No kill streak selected.
MW2_KILLSTREAKS_AIRDROP_MEGA=Emergency Airdrop
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Airdrop 4 random killstreaks or ammo.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Press %s for EMERGENCY AIRDROP.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Tactical Nuke
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=End the game with a bang.
MW2_KILLSTREAKS_SENTRY=Sentry Gun
  
MW2_MP_EARNED_AIRSTRIKE=Press %s for AIRSTRIKE.
MW2_MP_EARNED_AIRDROP=Press %s for AIRDROP.
MW2_MP_EARNED_SENTRY_AIRDROP=Press %s for SENTRY AIRDROP.
MW2_MP_EARNED_PREDATOR_AIRDROP=Press %s for PREDATOR AIRDROP.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Press %s for PRECISION AIRSTRIKE.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Press %s for STEALTH BOMBER.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Press %s for HARRIER AIRSTRIKE.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Press %s for SUPER AIRSTRIKE.
MW2_MP_EARNED_UAV=Press %s for UAV.
MW2_MP_EARNED_DOUBLE_UAV=Press %s for ADVANCED UAV.
MW2_MP_EARNED_COUNTER_UAV=Press %s for COUNTER-UAV.
MW2_MP_EARNED_HELICOPTER=Press %s for ATTACK HELICOPTER.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Press %s for CHOPPER GUNNER.
MW2_MP_EARNED_HELICOPTER_MK19=Press %s for HELICOPTER MK19.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Press %s for HELICOPTER BLACKBOX.
MW2_MP_EARNED_HELICOPTER_FLARES=Press %s for PAVELOW.
MW2_MP_EARNED_AC130=Press %s for AC130.
MW2_MP_EARNED_PREDATOR_MISSILE=Press %s for PREDATOR MISSILE.
MW2_MP_EARNED_NUKE=Press %s for TACTICAL NUKE.
MW2_MP_EARNED_AUTO_SHOTGUN=Press %s for SHOTGUN.
MW2_MP_EARNED_AUTO_SENTRY=Press %s for AUTO-SENTRY.
MW2_MP_EARNED_AUTO_SENTRY_GL=Press %s for AUTO-GRENADE LAUNCHER.
MW2_MP_EARNED_THUMPER=Press %s for THUMPER.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Press %s for LITTLEBIRD.
MW2_MP_EARNED_EMP=Press %s for EMP.

# Other
MW2_MP_CONNECTED=%s Connected
MW2_MP_DISCONNECTED=%s Disconnected
MW2_EXE_LEFTGAME=%s left the game

MW2_PLATFORM_RELOAD=Reload
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Low Ammo
MW2_WEAPON_NO_AMMO=No Ammo

MW2_MPUI_WINNING_CAPS=WINNING
MW2_MPUI_LOSING_CAPS=LOSING
MW2_MPUI_TIED_CAPS=TIE

MW2_CGAME_SB_SCORE=Score
MW2_CGAME_SB_DEATHS=Deaths
MW2_CGAME_SB_KILLS=Kills
MW2_CGAME_SB_ASSISTS=Assists
  
# Round Starter
MW2_MP_MATCH_STARTING_IN=Match begins in:
MW2_MP_MATCH_RESUMING_IN=Match resumes in:
  
MW2_MP_OBJ_DM_HINT=Eliminate other players.
MW2_MP_OBJ_WAR_HINT=Eliminate enemy players.
MW2_OBJECTIVES_WAR_HINT=Eliminate enemy players.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Destroy target A or B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Protect targets A and B.
MW2_OBJECTIVES_SAB_HINT=Destroy the enemy target.
MW2_OBJECTIVES_DOM_HINT=Capture the flags and defend them.
MW2_OBJECTIVES_DM_HINT=Eliminate other players.
MW2_OBJECTIVES_KOTH_HINT=Hold the headquarters.
MW2_OBJECTIVES_CTF_HINT=Capture the enemy flag.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Capture the enemy flag.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Defend the flag.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Destroy targets A and B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Protect targets A and B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Kill the VIP and keep him from reaching the extraction zone.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Defend the VIP and help him reach the extraction zone.
MW2_OBJECTIVES_ARENA_HINT=Eliminate the enemy or capture the flag
MW2_OBJECTIVES_GTNW_HINT=Capture the nuke.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Grab the enemy flag.

# Round Ender
MW2_MP_DRAW=Draw
MW2_MP_VICTORY=Victory!
MW2_MP_DEFEAT=Defeat!
MW2_MP_ROUND_DRAW=Round Draw
MW2_MP_ROUND_WIN=Round Win
MW2_MP_ROUND_LOSS=Round Loss
MW2_MP_HALFTIME=Halftime
MW2_MP_OVERTIME=Overtime
MW2_MP_MATCH_BONUS_IS=Match Bonus: %s

MW2_MP_OPFOR_ELIMINATED=OpFor eliminated
MW2_MP_OPFOR_FORFEITED=OpFor forfeited
MW2_MP_SPETSNAZ_ELIMINATED=Spetsnaz eliminated
MW2_MP_SPETSNAZ_FORFEITED=Spetsnaz forfeited
MW2_MP_US_ARMY_ELIMINATED=US Army Eliminated
MW2_MP_US_ARMY_FORFEITED=US Army Forfeited
MW2_MP_MILITIA_ELIMINATED=Militia Eliminated
MW2_MP_MILITIA_FORFEITED=Militia Forfeited
MW2_MP_TF141_ELIMINATED=TF141 Eliminated
MW2_MP_TF141_FORFEITED=TF141 Forfeited
MW2_MP_SEALS_ELIMINATED=SEALs Eliminated
MW2_MP_SEALS_FORFEITED=SEALs Forfeited