#---------- MW3 HUD | English
# Translator: Original Game

# Factions
MW3_MP_SAS=Special Air Service
MW3_MP_INNERCIRCLE_NAME=Inner Circle
MW3_MP_AFRICA_MILITIA_NAME=Africa Militia
MW3_MP_DELTA_NAME=Delta Force
MW3_MP_GIGN=GIGN
MW3_MP_SPETSNAZ_NAME=Spetsnaz
MW3_MP_PMC_NAME=P.M.C.
	
MW3_MP_SAS_SHORT_NAME=SAS
MW3_MP_INNERCIRCLE_SHORT_NAME=Inner Circle
MW3_MP_AFRICA_MILITIA_SHORT_NAME=Militia
MW3_MP_PMC_SHORT_NAME=PMC
MW3_MP_DELTA_SHORT_NAME=Delta
MW3_MP_GIGN_SHORT_NAME=GIGN
MW3_MPUI_SPETSNAZ_SHORT=Spetsnaz
MW3_MP_PMC_SHORT_NAME=PMC

# Splashes
MW3_SPLASHES_HEADSHOT=Headshot!
MW3_SPLASHES_HEADSHOT_DESC=+%s
MW3_SPLASHES_ASSISTEDSUICIDE=Assisted Suicide!
MW3_SPLASHES_ASSISTEDSUICIDE_DESC=You have assisted the suicide of an enemy. +%s
MW3_SPLASHES_LONGSHOT=Longshot!
MW3_SPLASHES_LONGSHOT_DESC=Nice kill from a distance!
MW3_SPLASHES_EXECUTION=Execution!
MW3_SPLASHES_EXECUTION_DESC=+%s
MW3_SPLASHES_AVENGER=Avenger!
MW3_SPLASHES_AVENGER_DESC=You've avenged a team-mate.
MW3_SPLASHES_DEFENDER=Rescuer!
MW3_SPLASHES_DEFENDER_DESC=You've rescued a team-mate.
MW3_SPLASHES_POSTHUMOUS=Afterlife!
MW3_SPLASHES_POSTHUMOUS_DESC=You killed an enemy after you died.
MW3_SPLASHES_REVENGE=Payback!
MW3_SPLASHES_REVENGE_DESC=You've taken revenge.
MW3_SPLASHES_DOUBLEKILL=Double Kill!
MW3_SPLASHES_DOUBLEKILL_DESC=+%s
MW3_SPLASHES_TRIPLEKILL=Triple Kill!
MW3_SPLASHES_TRIPLEKILL_DESC=+%s
MW3_SPLASHES_MULTIKILL=Multi-Kill!
MW3_SPLASHES_MULTIKILL_DESC=+%s
MW3_SPLASHES_FIRSTBLOOD=First Blood!
MW3_SPLASHES_FIRSTBLOOD_DESC=You got the first kill.
MW3_SPLASHES_BUZZKILL=Buzzkill!
MW3_SPLASHES_BUZZKILL_DESC=Stopped enemy short of a killstreak.
MW3_SPLASHES_COMEBACK=Comeback!
MW3_SPLASHES_COMEBACK_DESC=You've recovered from a streak of deaths.
MW3_SPLASHES_FLAGRETURN=Flag Return!
MW3_SPLASHES_FLAGRETURN_DESC=+%s
MW3_SPLASHES_FLAGPICKUP=Flag Runner!
MW3_SPLASHES_FLAGPICKUP_DESC=+%s
MW3_SPLASHES_CAPTURE=Position Secure!
MW3_SPLASHES_CAPTURE_DESC=You've taken an objective.
MW3_SPLASHES_DEFEND=Defense!
MW3_SPLASHES_DEFEND_DESC=You defended the objective.
MW3_SPLASHES_ASSAULT=Offense!
MW3_SPLASHES_ASSAULT_DESC=You killed a defender.
MW3_SPLASHES_PLANT=Saboteur!
MW3_SPLASHES_PLANT_DESC=You planted the bomb.
MW3_SPLASHES_DEFUSE=Hero!
MW3_SPLASHES_DEFUSE_DESC=You defused the bomb.
MW3_SPLASHES_SAB_OVERTIME=Overtime!
MW3_SPLASHES_SAB_OVERTIME_DESC=The base nearest to the bomb will be destroyed.
MW3_SPLASHES_MARTYRDOM_DESC=You'll drop a live grenade upon death.
MW3_SPLASHES_FINALSTAND_DESC=You'll get a second chance when you're down.
MW3_SPLASHES_ENDGAME_DESC=You've got extra health for the next few seconds.
MW3_SPLASHES_C4DEATH_DESC=Pull out C4 before you die.
MW3_SPLASHES_KNIFETHROW_DESC=You killed an enemy with a throwing knife.
MW3_SPLASHES_KNIFETHROW=Bullseye!
MW3_SPLASHES_HIJACKER_DESC=You captured an enemy supply crate.
MW3_SPLASHES_HIJACKER=Hijacker!
MW3_SPLASHES_HIJACKED=%s captured your supply crate.
MW3_SPLASHES_DEFCON_LOWER=DEFCON Lowered!
MW3_SPLASHES_DEFCON_RAISE=DEFCON Raised
MW3_SPLASHES_DEFCON_LOWER_DESC=Killstreaks upgraded!
MW3_SPLASHES_DEFCON_RAISE_DESC=Killstreaks downgraded.
MW3_SPLASHES_DEFCON_5=DEFCON 5
MW3_SPLASHES_DEFCON_4=DEFCON 4
MW3_SPLASHES_DEFCON_3=DEFCON 3
MW3_SPLASHES_DEFCON_2=DEFCON 2
MW3_SPLASHES_DEFCON_1=DEFCON 1
MW3_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW3_SPLASHES_DEFCON_4_DESC=Match starting!
MW3_SPLASHES_DEFCON_3_DESC=Emergency airdrop incoming!
MW3_SPLASHES_DEFCON_2_DESC=Killstreaks rollover!
MW3_SPLASHES_DEFCON_1_DESC=Double points for objectives!
MW3_SPLASHES_COMBATHIGH_DESC=Increased health for a short time.
MW3_SPLASHES_RESTED=Daily XP Boost!
MW3_SPLASHES_RESTED_DESC=Earning your daily bonus XP!
MW3_SPLASHES_RESTED_DONE=Daily XP Boost Done.
MW3_SPLASHES_RESTED_DONE_DESC=Bonus XP acquired.
MW3_SPLASHES_VIP=You are the VIP
MW3_SPLASHES_STUCK_SEMTEX=Stuck!
MW3_SPLASHES_STUCK_SEMTEX_DESC=You stuck an enemy with Semtex!
MW3_SPLASHES_HEROIC=Heroic!
MW3_SPLASHES_HEROIC_DESC=You captured an objective in last stand!
MW3_SPLASHES_DENIED=Denied!
MW3_SPLASHES_DENIED_DESC=You destroyed an enemy tactical insertion!
MW3_SPLASHES_DESTROYED_INSERTION=Blocked your TI!
MW3_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Took your crate!
MW3_SPLASHES_REVIVER_DESC=You revived a fallen teamate.
MW3_SPLASHES_REVIVER=Reviver!
MW3_SPLASHES_GIVEAWAY_SENTRY=...took a Sentry Gun
MW3_SPLASHES_GIVEAWAY_AIRDROP=... took an airdropped Killstreak.
MW3_SPLASHES_SEMTEX_STUCK=Stuck you with Semtex
MW3_SPLASHES_ONE_SHOT_KILL=One Shot Kill
MW3_SPLASHES_ONE_SHOT_KILL_DESC=One shot... one kill
MW3_SPLASHES_NINJA_DEFUSE=Ninja Defuse
MW3_SPLASHES_NINJA_DEFUSE_DESC=Sneaky sneaky...
MW3_SPLASHES_COPYCAT_DESC=Steal your killer's class during killcam.
MW3_SPLASHES_COPIED=Copied class!
MW3_SPLASHES_REVIVED=Revived You
MW3_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Last Alive!
MW3_SPLASHES_LAST_ENEMY_ALIVE=Last Alive!
MW3_SPLASHES_SHIELDASSIST=Crowd Control!
MW3_SPLASHES_SHIELDASSIST_DESC=You make an excellent distraction.
MW3_SPLASHES_DESTROYED_HELICOPTER=Destroyed Helicopter!
MW3_SPLASHES_DESTROYED_PAVELOW=Destroyed Pave Low!
MW3_SPLASHES_DESTROYED_UAV=Destroyed UAV!
MW3_SPLASHES_DESTROYED_HARRIER=Destroyed Harrier!
MW3_SPLASHES_DESTROYED_AC130=Destroyed AC-130!
MW3_SPLASHES_DESTROYED_MINIGUNNER=Destroyed Gunship!
MW3_SPLASHES_FLAG_RETURN=Returned Flag!
MW3_SPLASHES_FLAG_CAPTURE=Captured Flag!
MW3_SPLASHES_FLAG_PICKUP_FRIENDLY=Took Your Flag!
MW3_SPLASHES_FLAG_PICKUP_ENEMY=Took Enemy Flag!
MW3_SPLASHES_FLAG_PICKUP=Took the Flag!
MW3_SPLASHES_CAPTURED_NUKE=Nuke Captured!
MW3_SPLASHES_DESC_CAPTURED_NUKE=You've captured the nuke.
MW3_SPLASHES_UNLOCKED_EXTENDED_MAGS=Extended Mags unlocked!
MW3_SPLASHES_UNLOCKED_HEARTBEAT=Heartbeat Sensor unlocked!
MW3_SPLASHES_UNLOCKED_AKIMBO=Akimbo unlocked!
MW3_SPLASHES_UNLOCKED_THERMAL=Thermal Scope unlocked!
MW3_SPLASHES_UNLOCKED_EOTECH=Holographic Sight unlocked!
MW3_SPLASHES_UNLOCKED_SHOTGUN=Shotgun unlocked!
MW3_SPLASHES_GRABBED_THE_FLAG=Grabbed the flag!
MW3_SPLASHES_HIJACKED_SENTRY=Took Your Sentry!
MW3_SPLASHES_HIJACKED_AIRDROP=Took Your Crate!
MW3_SPLASHES_HIJACKED_JUGGERNAUT=Took Your Juggernaut!
MW3_SPLASHES_HIJACKED_REMOTE_TANK=Took Your Assault Drone!
MW3_SPLASHES_BOMB_PLANTED=Planted Bomb!
MW3_SPLASHES_BOMB_DEFUSED=Defused Bomb!
MW3_SPLASHES_TIMEADDED=Time Added!
MW3_SPLASHES_GTNW_OVERTIME=Sudden Death!
MW3_SPLASHES_GTNW_OVERTIME_DESC=No respawning.
MW3_SPLASHES_DESTROYED_OBJECTIVE=Destroyed Objective!
MW3_SPLASHES_SAVED_OBJECTIVE=Saved Objective!
MW3_SPLASHES_CAPTURED_HQ=Captured HQ!
MW3_SPLASHES_DESTROYED_HQ=Destroyed HQ!
MW3_SPLASHES_BOMB_TAKEN=Took Bomb!
MW3_SPLASHES_BOMB_DROPPED=Dropped Bomb!
MW3_SPLASHES_KILLED_CARRIER=Killed Bomb Carrier!
MW3_SPLASHES_SHAREPACKAGE=Share Package!
MW3_SPLASHES_SHAREPACKAGE_DESC=A teammate saved your Care Package from the enemy!
MW3_SPLASHES_DESTROYED_COUNTER_UAV=Restored UAV!
MW3_SPLASHES_FLAGS_CAPTURE=Captured a Flag!
MW3_SPLASHES_FLAG_ASSAULT=Flag Assault!
MW3_SPLASHES_FLAG_DEFEND=Flag Defend!
MW3_SPLASHES_FLAG_ASSAULT_DESC=You killed a flag defender.
MW3_SPLASHES_FLAG_DEFEND_DESC=You defended the flag.
MW3_SPLASHES_FLAG_CAPTURED=Flag Captured!
MW3_SPLASHES_FLAG_CAPTURED_DESC=You've captured the enemy flag.
MW3_SPLASHES_SECURED_POSITION=Secured Position!
MW3_SPLASHES_SECURED_POSITION_A=Secured A!
MW3_SPLASHES_SECURED_POSITION_B=Secured B!
MW3_SPLASHES_SECURED_POSITION_C=Secured C!
MW3_SPLASHES_TIME_ADDED=Time Extension!
MW3_SPLASHES_TIME_ADDED_DESC=Bomb site destroyed. Game time extended.
MW3_SPLASHES_GIVEAWAY_JUGGERNAUT=...took a Juggernaut
MW3_SPLASHES_DESTROYED_A10=Destroyed A-10!
MW3_SPLASHES_PROXIMITYASSIST=Team Assist
MW3_SPLASHES_PROXIMITYKILL=Team Kill
MW3_SPLASHES_KILLED_FLAG_CARRIER=Killed Flag Carrier!
MW3_SPLASHES_KILLED_FLAG_CARRIER_DESC=You killed a flag carrier.
MW3_SPLASHES_DESTROYED_REMOTE_MORTAR=Destroyed Reaper!
MW3_SPLASHES_KILLED_JUGGERNAUT=Killed Juggernaut!
MW3_SPLASHES_DESTROYED_REMOTE_UAV=Destroyed Recon Drone!
MW3_SPLASHES_MARKED_BY_REMOTE_UAV=Tagged by Recon Drone!
MW3_SPLASHES_TURRET_MARKED_BY_REMOTE_UAV=Turret Tagged by Recon Drone!
MW3_SPLASHES_REMOTE_UAV_MARKED=Tagged!
MW3_SPLASHES_REMOTE_UAV_ASSIST=Tagged Assist!
MW3_SPLASHES_X2_BONUS=x2 Bonus!
MW3_SPLASHES_KILL_CONFIRMED=Kill Confirmed!
MW3_SPLASHES_KILL_DENIED=Kill Denied!
MW3_SPLASHES_DENIED_KILL=Denied Kill!
MW3_SPLASHES_TAGS_RETRIEVED=Got Your Tags!
MW3_SPLASHES_TEAM_ASSIST=Team Assist!
MW3_SPLASHES_NEW_JUGGERNAUT=New Juggernaut!
MW3_SPLASHES_JUGGERNAUT_KILL=Juggernaut Kill!
MW3_SPLASHES_DROPPED_JUGGERNAUT=Dropped Juggernaut!
MW3_SPLASHES_GAINED_GUN_RANK=Gained Gun Rank!
MW3_SPLASHES_DROPPED_GUN_RANK=Dropped Gun Rank!
MW3_SPLASHES_DROPPED_ENEMY_GUN_RANK=Dropped Enemy Gun Rank!
MW3_SPLASHES_TOP_GUN_RANK=Top Gun Rank!
MW3_SPLASHES_GOT_JUGGERNAUT=Got Juggernaut!
MW3_SPLASHES_GOT_JUGGERNAUT_DESC=You are now the Juggernaut.
MW3_SPLASHES_DESTROYED_OSPREY=Destroyed Osprey!
MW3_SPLASHES_DESTROYED_LITTLE_BIRD=Destroyed AH-6!
MW3_SPLASHES_ELIMINATED=Eliminated!
MW3_SPLASHES_SURVIVOR=Survivor!
MW3_SPLASHES_DESTROYED_REMOTE_TANK=Destroyed Assault Drone!
MW3_SPLASHES_DESERTED=Ran Away!
MW3_SPLASHES_GOT_DRAFTED=Got Infected!
MW3_SPLASHES_DRAFTED_ROGUE=Infected survivor!
MW3_SPLASHES_FINAL_ROGUE=Final Survivor!
MW3_SPLASHES_DRAFTED=Infected!
MW3_SPLASHES_FIRST_MERCENARY=First Infected!
MW3_SPLASHES_JUGGERNAUT_KILL_JUGGERNAUT=Jugg Kill Jugg!
MW3_SPLASHES_EARNED_CAREPACKAGE=Earned Care Package!
MW3_SPLASHES_DESTROYED_PREDATOR_MISSILE=Destroyed Predator Missile!

# Other
MW3_MP_CONNECTED=%s Connected
MW3_MP_DISCONNECTED=%s Disconnected
MW3_EXE_LEFTGAME=%s left the game

MW3_PLATFORM_RELOAD=Reload
MW3_PLATFORM_LOW_AMMO_NO_RELOAD=Low Ammo
MW3_WEAPON_NO_AMMO=No Ammo

MW3_MPUI_WINNING_CAPS=WINNING
MW3_MPUI_LOSING_CAPS=LOSING
MW3_MPUI_TIED_CAPS=TIE

MW3_CGAME_SB_SCORE=Score
MW3_CGAME_SB_DEATHS=Deaths
MW3_CGAME_SB_KILLS=Kills
MW3_CGAME_SB_ASSISTS=Assists

MW3_PLATFORM_THROWBACKGRENADE=%s throw back

# Round Starter
MW3_MP_MATCH_STARTING_IN=Match begins in:
MW3_MP_MATCH_RESUMING_IN=Match resumes in:
  
# Gamemodes
MW3_MPUI_SABOTAGE=Sabotage
MW3_MPUI_DEATHMATCH=Free-for-all
MW3_MPUI_CAPTURE_THE_FLAG=Capture the Flag
MW3_MPUI_HEADQUARTERS=Headquarters
MW3_MPUI_SEARCH_AND_DESTROY=Search and Destroy
MW3_MPUI_WAR=Team Deathmatch
MW3_MPUI_DOMINATION=Domination
MW3_MPUI_DD=Demolition
MW3_MPUI_GRND=Drop Zone
MW3_MPUI_TDEF=Team Defender
MW3_MPUI_CONF=Kill Confirmed

MW3_OBJECTIVES_WAR_HINT=Eliminate enemy players.
MW3_OBJECTIVES_SD_ATTACKER_HINT=Destroy target A or B.
MW3_OBJECTIVES_SD_DEFENDER_HINT=Protect targets A and B.
MW3_OBJECTIVES_SAB_HINT=Destroy the enemy target.
MW3_OBJECTIVES_DOM_HINT=Capture the flags and defend them.
MW3_OBJECTIVES_DM_HINT=Eliminate other players.
MW3_OBJECTIVES_KOTH_HINT=Hold the headquarters.
MW3_OBJECTIVES_CTF_HINT=Capture the enemy flag.
MW3_OBJECTIVES_DD_ATTACKER_HINT=Destroy targets A and B.
MW3_OBJECTIVES_DD_DEFENDER_HINT=Protect targets A and B.
MW3_OBJECTIVES_GRAB_FLAG_HINT=Grab the enemy flag.
MW3_OBJECTIVES_TDEF_ATTACKER_HINT=Capture flag for team x2 bonus.
MW3_OBJECTIVES_TDEF_DEFENDER_HINT=Defend flag for team x2 bonus.
MW3_OBJECTIVES_TDEF_HINT=Capture and hold the flag.
MW3_OBJECTIVES_CONF_HINT=Recover Dog Tags for the win.
MW3_OBJECTIVES_GRND_HINT=Get to the Drop Zone!
MW3_OBJECTIVES_DD_OVERTIME_HINT=Destroy Target B to win.

# Round Ender
MW3_MP_DRAW=Draw
MW3_MP_VICTORY=Victory!
MW3_MP_DEFEAT=Defeat!
MW3_MP_ROUND_DRAW=Round Draw
MW3_MP_ROUND_WIN=Round Win
MW3_MP_ROUND_LOSS=Round Loss
MW3_MP_HALFTIME=Halftime
MW3_MP_OVERTIME=Overtime
MW3_MP_MATCH_BONUS_IS=Match Bonus: %s

MW3_MP_SCORE_LIMIT_REACHED=Score limit reached
MW3_MP_ROUND_LIMIT_REACHED=Round limit reached
MW3_MP_TIME_LIMIT_REACHED=Time limit reached