#---------- MW2 HUD | Italiano | Italian
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Ranger
MW2_MP_SEALS_UDT_NAME=Navy SEAL
MW2_MP_MILITIA_NAME=Milizie
MW2_MP_TASKFORCE_NAME=Task Force 141
MW2_MP_OPFOR_NAME=Nemici
MW2_MP_SPETSNAZ_NAME=Unità Spetsnaz

MW2_MP_US_ARMY_SHORT_NAME=Ranger
MW2_MP_SEALS_UDT_SHORT_NAME=SEAL
MW2_MP_MILITIA_SHORT_NAME=Milizie
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_OPFOR_SHORT=Nemici
MW2_MPUI_SPETSNAZ_SHORT=Unità Spetsnaz

# Splashes
MW2_SPLASHES_HEADSHOT=Colpo alla testa!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Suicidio assistito!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Hai aiutato un nemico a suicidarsi.
MW2_SPLASHES_LONGSHOT=Tiro a lunga gittata!
MW2_SPLASHES_LONGSHOT_DESC=Ottima uccisione a distanza!
MW2_SPLASHES_EXECUTION=Esecuzione!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Vendicatore!
MW2_SPLASHES_AVENGER_DESC=Hai vendicato un compagno di squadra. 
MW2_SPLASHES_DEFENDER=Soccorritore!
MW2_SPLASHES_DEFENDER_DESC=Hai soccorso un compagno di squadra.
MW2_SPLASHES_POSTHUMOUS=L'aldilà!
MW2_SPLASHES_POSTHUMOUS_DESC=Hai ucciso un nemico dopo la tua morte.
MW2_SPLASHES_REVENGE=Vendetta!
MW2_SPLASHES_REVENGE_DESC=Ti sei vendicato.
MW2_SPLASHES_DOUBLEKILL=Doppia uccisione!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Tripla uccisione!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Uccisone multipla!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Primo sangue!
MW2_SPLASHES_FIRSTBLOOD_DESC=Hai segnato la prima uccisione. 
MW2_SPLASHES_BUZZKILL=Guastafeste!
MW2_SPLASHES_BUZZKILL_DESC=Hai fermato una serie di uccisioni di un nemico.
MW2_SPLASHES_COMEBACK=Ritorno!
MW2_SPLASHES_COMEBACK_DESC=Ti sei ripreso da una serie di morti.
MW2_SPLASHES_FLAGRETURN=Recupero della bandiera!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Fuga con la bandiera!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Posizione conquistata!
MW2_SPLASHES_CAPTURE_DESC=Hai conquistato un obiettivo.
MW2_SPLASHES_DEFEND=Difesa!
MW2_SPLASHES_DEFEND_DESC=Hai difeso l'obiettivo.
MW2_SPLASHES_ASSAULT=Attacco!
MW2_SPLASHES_ASSAULT_DESC=Hai ucciso un difensore. 
MW2_SPLASHES_PLANT=Sabotatore!
MW2_SPLASHES_PLANT_DESC=Hai piazzato la bomba.
MW2_SPLASHES_DEFUSE=Eroe!
MW2_SPLASHES_DEFUSE_DESC=Hai disinnescato la bomba.
MW2_SPLASHES_SAB_OVERTIME=Tempi supplementari!
MW2_SPLASHES_SAB_OVERTIME_DESC=La base più vicina alla bomba sarà distrutta.
MW2_SPLASHES_MARTYRDOM_DESC=Morendo innescherai una granata.
MW2_SPLASHES_FINALSTAND_DESC=Avrai una seconda occasione quando sarai a terra.
MW2_SPLASHES_ENDGAME_DESC=Hai ottenuto un po' di energia extra per i prossimi secondi.
MW2_SPLASHES_C4DEATH_DESC=Estrai del C4 prima di morire.
MW2_SPLASHES_KNIFETHROW_DESC=Hai ucciso un nemico con un coltello da lancio.
MW2_SPLASHES_KNIFETHROW=Centro!
MW2_SPLASHES_HIJACKER_DESC=Hai catturato una cassa di rifornimenti del nemico.
MW2_SPLASHES_HIJACKER=Dirottatore!
MW2_SPLASHES_HIJACKED=%s ha catturato la tua cassa di rifornimenti.
MW2_SPLASHES_DEFCON_LOWER=DEFCON abbassato!
MW2_SPLASHES_DEFCON_RAISE=DEFCON alzato!
MW2_SPLASHES_DEFCON_LOWER_DESC=Serie di uccisioni migliorate!
MW2_SPLASHES_DEFCON_RAISE_DESC=Serie di uccisioni peggiorate.
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Inizio della partita!
MW2_SPLASHES_DEFCON_3_DESC=Approvvigionamenti d'emergenza in arrivo!
MW2_SPLASHES_DEFCON_2_DESC=Serie di uccisioni a catena!
MW2_SPLASHES_DEFCON_1_DESC=Punteggio raddoppiato per gli obiettivi!
MW2_SPLASHES_COMBATHIGH_DESC=Salute aumentata per un breve periodo.
MW2_SPLASHES_RESTED=Bonus esperienza quotidiana!
MW2_SPLASHES_RESTED_DESC=Guadagna la tua esperienza bonus quotidiana!
MW2_SPLASHES_RESTED_DONE=Bonus esperienza quotidiano fatto.
MW2_SPLASHES_RESTED_DONE_DESC=Esperienza bonus ottenuta.
MW2_SPLASHES_VIP=Sei il VIP
MW2_SPLASHES_STUCK_SEMTEX=Attaccato!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Hai attaccato una granata Semtex a un nemico!
MW2_SPLASHES_HEROIC=Eroico!
MW2_SPLASHES_HEROIC_DESC=Hai catturato un obiettivo mentre eri in Sopravvivenza!
MW2_SPLASHES_DENIED=Negato!
MW2_SPLASHES_DENIED_DESC=Hai sventato un'infiltrazione tattica nemica!
MW2_SPLASHES_DESTROYED_INSERTION=ha bloccato la tua IT!
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=Ha preso la tua cassa!
MW2_SPLASHES_REVIVER_DESC=Hai rianimato un compagno caduto.
MW2_SPLASHES_REVIVER=Rianimatore!
MW2_SPLASHES_GIVEAWAY_SENTRY=...torretta robot presa
MW2_SPLASHES_GIVEAWAY_AIRDROP=...serie di uccisioni sganciata presa.
MW2_SPLASHES_SEMTEX_STUCK=Semtex attaccata!
MW2_SPLASHES_ONE_SHOT_KILL=Colpo preciso
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Un colpo... un morto
MW2_SPLASHES_NINJA_DEFUSE=Disinnesco Ninja
MW2_SPLASHES_NINJA_DEFUSE_DESC=Zitto zitto..
MW2_SPLASHES_COPYCAT_DESC=Ruba la classe di chi ti uccide durante Visuale morte
MW2_SPLASHES_COPIED=Classe copiata!
MW2_SPLASHES_REVIVED=ti ha rianimato
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Ultimo sopravvissuto!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Ultimo sopravvissuto!
MW2_SPLASHES_SHIELDASSIST=Antisommossa!
MW2_SPLASHES_SHIELDASSIST_DESC=Sei un eccellente diversivo.
MW2_SPLASHES_DESTROYED_HELICOPTER=ha distrutto un elicottero!
MW2_SPLASHES_DESTROYED_PAVELOW=ha distrutto un Pave Low!
MW2_SPLASHES_DESTROYED_UAV=ha distrutto un UAV!
MW2_SPLASHES_DESTROYED_HARRIER=ha distrutto un Harrier!
MW2_SPLASHES_DESTROYED_AC130=ha distrutto un AC130!
MW2_SPLASHES_DESTROYED_MINIGUNNER=ha distrutto un velivolo!
MW2_SPLASHES_FLAG_RETURN=ha riportato la bandiera alla base!
MW2_SPLASHES_FLAG_CAPTURE=cattura la bandiera!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=ha preso la tua bandiera!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=ha preso la bandiera nemica!
MW2_SPLASHES_FLAG_PICKUP=ha preso la bandiera!
MW2_SPLASHES_CAPTURED_NUKE=Carica nucleare catturata!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Hai catturato la carica nucleare.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Caricatori modificati sbloccati!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Cardiorivelatore sbloccato!
MW2_SPLASHES_UNLOCKED_AKIMBO=Akimbo sbloccato!
MW2_SPLASHES_UNLOCKED_THERMAL=Mirino termico sbloccato!
MW2_SPLASHES_UNLOCKED_EOTECH=Mirino olografico sbloccato!
MW2_SPLASHES_UNLOCKED_SHOTGUN=Fucile a pompa sbloccato!
MW2_SPLASHES_GRABBED_THE_FLAG=Bandiera presa!
MW2_SPLASHES_HIJACKED_SENTRY=Ha rubato la torretta!
MW2_SPLASHES_HIJACKED_AIRDROP=Ha preso la tua cassa!
MW2_SPLASHES_BOMB_PLANTED=ha piazzato la bomba!
MW2_SPLASHES_BOMB_DEFUSED=disinnesca la bomba!
MW2_SPLASHES_TIMEADDED=Tempo aggiunto!
MW2_SPLASHES_GTNW_OVERTIME=Morte istantanea!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Niente rientro.
MW2_SPLASHES_DESTROYED_OBJECTIVE=ha distrutto l'obiettivo!
MW2_SPLASHES_SAVED_OBJECTIVE=ha salvato l'obiettivo!
MW2_SPLASHES_CAPTURED_HQ=ha conquistato il QG!
MW2_SPLASHES_DESTROYED_HQ=ha distrutto il QG!
MW2_SPLASHES_BOMB_TAKEN=ha preso la bomba!
MW2_SPLASHES_BOMB_DROPPED=ha perso la bomba!
MW2_SPLASHES_KILLED_CARRIER=ha ucciso chi portava la bomba!
MW2_SPLASHES_SHAREPACKAGE=Approvvigionamenti condivisi!
MW2_SPLASHES_SHAREPACKAGE_DESC=Un compagno di squadra ha salvato i tuoi approvvigionamenti dalle mani nemiche!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=UAV ripristinato!
MW2_SPLASHES_FLAGS_CAPTURE=Bandiera catturata!
MW2_SPLASHES_FLAG_ASSAULT=Attacco alla bandiera!
MW2_SPLASHES_FLAG_DEFEND=Difesa della bandiera!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Hai ucciso un difensore della bandiera.
MW2_SPLASHES_FLAG_DEFEND_DESC=Hai difeso la bandiera.(</color>)
MW2_SPLASHES_FLAG_CAPTURED=Bandiera catturata!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Hai catturato la bandiera nemica.
MW2_SPLASHES_SECURED_POSITION=Posizione conquistata!
MW2_SPLASHES_SECURED_POSITION_A=A conquistata!
MW2_SPLASHES_SECURED_POSITION_B=B conquistata!
MW2_SPLASHES_SECURED_POSITION_C=C conquistata!
MW2_SPLASHES_TIME_ADDED=Tempo bonus!
MW2_SPLASHES_TIME_ADDED_DESC=Postazione bomba distrutta. Tempo di gioco aumentato.
  
# Killstreaks
MW2_KILLSTREAKS_UAV=UAV
MW2_KILLSTREAKS_UAV_DESC=Mostra i nemici sulla minimappa.
MW2_KILLSTREAKS_AIRSTRIKE=Raid aereo
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Richiedi un raid aereo sulla posizione selezionata.
MW2_KILLSTREAKS_HELICOPTER=Elicottero
MW2_KILLSTREAKS_HELICOPTER_DESC=Richiedi un elicottero di supporto.
MW2_KILLSTREAKS_AC130=AC130
MW2_KILLSTREAKS_AC130_DESC=Spara dall'AC-130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Missile Predator 
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Missile telecomandato.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Supporto aereo
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Spara da un elicottero.
MW2_KILLSTREAKS_HELICOPTER_MK19=Supporto aereo
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Controllo a distanza di un elicottero.
MW2_KILLSTREAKS_DOUBLE_UAV=UAV avanzato
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=UAV con maggiore velocità di virata.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Raid direzionale
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Richiedi un raid direzionale.
MW2_KILLSTREAKS_AIRDROP=Approvvigionamenti
MW2_KILLSTREAKS_AIRDROP_DESC=Sgancia una serie di uccisioni o munizioni.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Torretta robot
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Sgancia una torretta robot.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Approvvigionamenti (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Sgancia un singolo missile Predator.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Raid harrier
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Raid aereo con un harrier.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Bombardiere stealth
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Raid aereo non individuabile sulle mappe nemiche.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Super raid aereo
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Raid aereo pi� aggressivo.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Scatola nera dell'elicottero
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Elicottero a durata incrementata.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Elicottero difensivo
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Elicottero munito di bengala.
MW2_KILLSTREAKS_EMP=IEM
MW2_KILLSTREAKS_EMP_DESC=Interrompi i dispositivi elettronici nemici.
MW2_KILLSTREAKS_TANK=Carro
MW2_KILLSTREAKS_TANK_DESC=Un carro.
MW2_KILLSTREAKS_COUNTER_UAV=Contrattacco UAV
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Disattiva temporaneamente il radar nemico.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Elicottero pesante d'assalto.
MW2_KILLSTREAKS_NONE=Nessuno
MW2_KILLSTREAKS_NONE_DESC=Nessuna serie di uccisioni selezionata.
MW2_KILLSTREAKS_AIRDROP_MEGA=Approvv. d'emerg.
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Sgancia 4 serie di uccisioni o munizioni.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Premi %s per richiedere APPROVVIGIONAMENTI D'EMERGENZA.
MW2_KILLSTREAKS_TACTICAL_NUKE=Carica nucleare
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Finisci il gioco con un bel botto.
MW2_KILLSTREAKS_SENTRY=Torretta robot
  
  MW2_MP_EARNED_AIRSTRIKE=Premi %s per RAID AEREO.
MW2_MP_EARNED_AIRDROP=Premi %s per APPROVVIGIONAMENTI.
MW2_MP_EARNED_SENTRY_AIRDROP=Premi %s per SGANCIARE TORRETTA.
MW2_MP_EARNED_PREDATOR_AIRDROP=Premi %s per SGANCIARE PREDATOR.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Premi %s per RAID DIREZIONALE.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Premi %s per BOMBARDIERE STEALTH.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Premi %s per RAID AEREO HARRIER.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Premi %s per RAID AEREO SUPER.
MW2_MP_EARNED_UAV=Premi %s per UAV
MW2_MP_EARNED_DOUBLE_UAV=Premi %s per UAV AVANZATO.
MW2_MP_EARNED_COUNTER_UAV=Premi %s per CONTRATTACCO UAV.
MW2_MP_EARNED_HELICOPTER=Premi %s per ELICOTTERO.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Premi %s per ARTIGLIERE DELL'ELICOTTERO.
MW2_MP_EARNED_HELICOPTER_MK19=Premi %s per MK19 DELL'ELICOTTERO.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Premi %s per SCATOLA NERA DELL' ELICOTTERO.
MW2_MP_EARNED_HELICOPTER_FLARES=Premi %s per PAVE LOW.
MW2_MP_EARNED_AC130=Premi %s per AC130.
MW2_MP_EARNED_PREDATOR_MISSILE=Premi %s per MISSILE PREDATOR.
MW2_MP_EARNED_NUKE=Premi %s per CARICA NUCLEARE.
MW2_MP_EARNED_AUTO_SHOTGUN=Premi %s per FUCILE A POMPA.
MW2_MP_EARNED_AUTO_SENTRY=Premi %s per TORRETTA ROBOT.
MW2_MP_EARNED_AUTO_SENTRY_GL=Premi %s per AUTO-GRANATA.
MW2_MP_EARNED_THUMPER=Premi %s per THUMPER
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Premi %s per LITTLEBIRD.
MW2_MP_EARNED_EMP=Premi %s per IMPULSO ELETTROMAGNETICO.
  
# Other
MW2_MP_CONNECTED=%s si è connesso
MW2_MP_DISCONNECTED=%s si è disconnesso
MW2_EXE_LEFTGAME=%s ha abbandonato la partita

MW2_PLATFORM_RELOAD=Ricarica
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Munizioni in esaurimento
MW2_WEAPON_NO_AMMO=Munizioni esaurite

MW2_MPUI_WINNING_CAPS=VITTORIA
MW2_MPUI_LOSING_CAPS=SCONFITTA
MW2_MPUI_TIED_CAPS=PAREGGIO

MW2_CGAME_SB_SCORE=Punti
MW2_CGAME_SB_DEATHS=Morti
MW2_CGAME_SB_KILLS=Ucc.
MW2_CGAME_SB_ASSISTS=Assist

# Round Starter
MW2_MP_MATCH_STARTING_IN=La partita comincia fra:
MW2_MP_MATCH_RESUMING_IN=La partita riprenderà tra:

MW2_MP_OBJ_DM_HINT=Elimina gli altri giocatori.
MW2_MP_OBJ_WAR_HINT=Elimina gli altri giocatori.
MW2_OBJECTIVES_WAR_HINT=Elimina gli altri giocatori.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Distruggi il bersaglio A o B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Proteggi gli obiettivi A e B
MW2_OBJECTIVES_SAB_HINT=Distruggi il bersaglio nemico.
MW2_OBJECTIVES_DOM_HINT=Cattura le bandiere e difendile.
MW2_OBJECTIVES_DM_HINT=Elimina gli altri giocatori.
MW2_OBJECTIVES_KOTH_HINT=Difendi il quartier generale.
MW2_OBJECTIVES_CTF_HINT=Cattura la bandiera nemica.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Cattura la bandiera nemica.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Difendi la bandiera.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Distruggi i bersagli A e B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Proteggi gli obiettivi A e B
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Uccidi il VIP ed evita che raggiunga il punto d'estrazione.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Difendi il VIP e aiutalo a raggiungere il punto di estrazione.
MW2_OBJECTIVES_ARENA_HINT=Elimina il nemico o cattura la bandiera
MW2_OBJECTIVES_GTNW_HINT=Recupera la carica nucleare.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Prendi la bandiera nemica.