#---------- MW2 HUD | Francais | French
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Rangers
MW2_MP_OPFORCE_COMPOSITE_NAME=Ennemi
MW2_MP_SEALS_UDT_NAME=Navy SEAL
MW2_MP_SECRET_SERVICE_NAME=Services secrets
MW2_MP_MILITIA_NAME=Milice
MW2_MP_TASKFORCE_NAME=Task Force 141
MW2_MP_OPFORCE_ARCTIC_NAME=Ennemi
MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_OPFORCE_COMPOSITE_SHORT_NAME=Ennemi
MW2_MP_SEALS_UDT_SHORT_NAME=SEAL
MW2_MP_SECRET_SERVICE_SHORT_NAME=Services secrets
MW2_MP_MILITIA_SHORT_NAME=Milice
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MP_OPFORCE_ARCTIC_SHORT_NAME=Ennemi
  
# Splashes
MW2_SPLASHES_HEADSHOT=Pleine tête !
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Suicide en direct !
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Vous avez été témoin du suicide d'un ennemi.
MW2_SPLASHES_LONGSHOT=Tir à longue distance !
MW2_SPLASHES_LONGSHOT_DESC=Joli tir à distance !
MW2_SPLASHES_EXECUTION=Exécution !
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Vengeur !
MW2_SPLASHES_AVENGER_DESC=Vous avez vengé un coéquipier.
MW2_SPLASHES_DEFENDER=Sauveur !
MW2_SPLASHES_DEFENDER_DESC=Vous avez sauvé un coéquipier.
MW2_SPLASHES_POSTHUMOUS=De l'au-delà !
MW2_SPLASHES_POSTHUMOUS_DESC=Vous avez tué un ennemi après votre mort.
MW2_SPLASHES_REVENGE=Vengeance !
MW2_SPLASHES_REVENGE_DESC=Vous vous êtes vengé.
MW2_SPLASHES_DOUBLEKILL=Double élimination !
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Triple élimination !
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Élimination multiple !
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Premier sang !
MW2_SPLASHES_FIRSTBLOOD_DESC=Vous avez tué la première victime.
MW2_SPLASHES_BUZZKILL=Trouble-fête !
MW2_SPLASHES_BUZZKILL_DESC=Vous avez arrêté un ennemi en pleine série d'éliminations.
MW2_SPLASHES_COMEBACK=Retour !
MW2_SPLASHES_COMEBACK_DESC=Vous avez récupéré d'une série de morts.
MW2_SPLASHES_FLAGRETURN=Retour du drapeau !
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Transporteur de drapeau !
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Position sécurisée !
MW2_SPLASHES_CAPTURE_DESC=Vous avez pris un objectif.
MW2_SPLASHES_DEFEND=Défense !
MW2_SPLASHES_DEFEND_DESC=Vous avez défendu l'objectif.
MW2_SPLASHES_ASSAULT=Attaque !
MW2_SPLASHES_ASSAULT_DESC=Vous avez tué un défenseur.
MW2_SPLASHES_PLANT=Saboteur !
MW2_SPLASHES_PLANT_DESC=Vous avez posé la bombe.
MW2_SPLASHES_DEFUSE=Héros !
MW2_SPLASHES_DEFUSE_DESC=Vous avez désamorcé la bombe.
MW2_SPLASHES_SAB_OVERTIME=Prolongation !
MW2_SPLASHES_SAB_OVERTIME_DESC=La base la plus proche de la bombe sera détruite.
MW2_SPLASHES_MARTYRDOM_DESC=Vous laisserez tomber une grenade dégoupillée à votre mort.
MW2_SPLASHES_FINALSTAND_DESC=Vous aurez une seconde chance quand vous vous ferez tuer.
MW2_SPLASHES_ENDGAME_DESC=Vous disposez d'un bonus de santé pour quelques secondes.
MW2_SPLASHES_C4DEATH_DESC=Sortez une charge de C4 avant de mourir.
MW2_SPLASHES_KNIFETHROW_DESC=Vous avez tué un ennemi au couteau de lancer.
MW2_SPLASHES_KNIFETHROW=Dans le mille !
MW2_SPLASHES_HIJACKER_DESC=Vous avez pris une caisse de ravitaillement ennemie.
MW2_SPLASHES_HIJACKER=Pirate !
MW2_SPLASHES_HIJACKED=%s a pris votre caisse.
MW2_SPLASHES_DEFCON_LOWER=DEFCON réduit !
MW2_SPLASHES_DEFCON_RAISE=DEFCON augmenté !
MW2_SPLASHES_DEFCON_LOWER_DESC=Bonus de séries d'éliminations améliorés !
MW2_SPLASHES_DEFCON_RAISE_DESC=Bonus de séries d'éliminations rétrogradés !
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Début du match !
MW2_SPLASHES_DEFCON_3_DESC=Largage aérien d'urgence imminent !
MW2_SPLASHES_DEFCON_2_DESC=Suivi des séries d'éliminations après avoir été tué
MW2_SPLASHES_DEFCON_1_DESC=Points des objectifs doublés !
MW2_SPLASHES_COMBATHIGH_DESC=Santé accrue pour une courte durée.
MW2_SPLASHES_RESTED=Boost d'EXP du jour !
MW2_SPLASHES_RESTED_DESC=Vous gagnez des points d'EXP bonus.
MW2_SPLASHES_RESTED_DONE=Fin Boost EXP du jour.
MW2_SPLASHES_RESTED_DONE_DESC=Points bonus d'EXP obtenus.
MW2_SPLASHES_VIP=Vous êtes le VIP.
MW2_SPLASHES_STUCK_SEMTEX=Ça va faire boum !
MW2_SPLASHES_STUCK_SEMTEX_DESC=Vous avez posé du Semtex sur un ennemi !
MW2_SPLASHES_HEROIC=Quelle bravoure !
MW2_SPLASHES_HEROIC_DESC=Vous avez pris un objectif en Baroud d'honneur !
MW2_SPLASHES_DENIED=Pas question !
MW2_SPLASHES_DENIED_DESC=Vous avez empêché l'insertion tactique d'un ennemi !
MW2_SPLASHES_DESTROYED_INSERTION=bloque votre insertion.
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=a pris votre caisse !
MW2_SPLASHES_REVIVER_DESC=Vous avez ranimé un coéquipier tombé au combat.
MW2_SPLASHES_REVIVER=Réanimateur !
MW2_SPLASHES_GIVEAWAY_SENTRY=a pris une tourelle.
MW2_SPLASHES_GIVEAWAY_AIRDROP=... a pris un bonus largué.
MW2_SPLASHES_SEMTEX_STUCK=Semtex collé sur vous !
MW2_SPLASHES_ONE_SHOT_KILL=Coup mortel
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Un tir... un mort.
MW2_SPLASHES_NINJA_DEFUSE=Désamorçage de Ninja
MW2_SPLASHES_NINJA_DEFUSE_DESC=En toute discrétion...
MW2_SPLASHES_COPYCAT_DESC=Volez la classe de votre tueur durant la killcam.
MW2_SPLASHES_COPIED=Classe imitée !
MW2_SPLASHES_REVIVED=vous a ranimé.
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Dernier en vie !
MW2_SPLASHES_LAST_ENEMY_ALIVE=Dernier en vie !
MW2_SPLASHES_SHIELDASSIST=Forces antiémeute !
MW2_SPLASHES_SHIELDASSIST_DESC=Vous faites une excellente diversion.
MW2_SPLASHES_DESTROYED_HELICOPTER=a détruit un hélico !
MW2_SPLASHES_DESTROYED_PAVELOW=a détruit un Pave Low !
MW2_SPLASHES_DESTROYED_UAV=a détruit un drone !
MW2_SPLASHES_DESTROYED_HARRIER=a détruit un Harrier !
MW2_SPLASHES_DESTROYED_AC130=a détruit l'AC-130 !
MW2_SPLASHES_DESTROYED_MINIGUNNER=a détruit un hélico !
MW2_SPLASHES_FLAG_RETURN=a rapporté le drapeau !
MW2_SPLASHES_FLAG_CAPTURE=a capturé le drapeau !
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=a pris votre drapeau !
MW2_SPLASHES_FLAG_PICKUP_ENEMY=a le drapeau ennemi !
MW2_SPLASHES_FLAG_PICKUP=a pris le drapeau !
MW2_SPLASHES_CAPTURED_NUKE=Bombe nucl. capturée !
MW2_SPLASHES_DESC_CAPTURED_NUKE=Bombe nucl. capturée !
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Charg. grde cap. dispo.
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Capteur card. dispo.
MW2_SPLASHES_UNLOCKED_AKIMBO=Akimbo débloqué !
MW2_SPLASHES_UNLOCKED_THERMAL=Lunette therm. dispo.
MW2_SPLASHES_UNLOCKED_EOTECH=Viseur holog. dispo.
MW2_SPLASHES_UNLOCKED_SHOTGUN=F. à pompe débloqué !
MW2_SPLASHES_GRABBED_THE_FLAG=Vous avez pris le drapeau !
MW2_SPLASHES_HIJACKED_SENTRY=a pris votre tourelle.
MW2_SPLASHES_HIJACKED_AIRDROP=a pris votre caisse.
MW2_SPLASHES_BOMB_PLANTED=Bombe posée !
MW2_SPLASHES_BOMB_DEFUSED=Bombe désamorcée !
MW2_SPLASHES_TIMEADDED=Temps ajouté !
MW2_SPLASHES_GTNW_OVERTIME=Mort subite !
MW2_SPLASHES_GTNW_OVERTIME_DESC=Pas de réapparition.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Objectif détruit !
MW2_SPLASHES_SAVED_OBJECTIVE=Objectif sauvé !
MW2_SPLASHES_CAPTURED_HQ=Q.G. capturé !
MW2_SPLASHES_DESTROYED_HQ=Q.G. détruit !
MW2_SPLASHES_BOMB_TAKEN=Bombe prise !
MW2_SPLASHES_BOMB_DROPPED=Bombe perdue !
MW2_SPLASHES_KILLED_CARRIER=Porteur de bombe tué !
MW2_SPLASHES_SHAREPACKAGE=Partage de colis !
MW2_SPLASHES_SHAREPACKAGE_DESC=Un de vos coéquipiers a sauvé votre colis stratégique de l'ennemi !
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Drone rétabli !
MW2_SPLASHES_FLAGS_CAPTURE=a capturé un drapeau !
MW2_SPLASHES_FLAG_ASSAULT=Assault du drapeau !
MW2_SPLASHES_FLAG_DEFEND=Drapeau défendu !
MW2_SPLASHES_FLAG_ASSAULT_DESC=Vous avez tué un défenseur de drapeau.
MW2_SPLASHES_FLAG_DEFEND_DESC=Vous avez défendu le drapeau.
MW2_SPLASHES_FLAG_CAPTURED=Drapeau capturé !
MW2_SPLASHES_FLAG_CAPTURED_DESC=Vous avez capturé le drapeau ennemi.
MW2_SPLASHES_SECURED_POSITION=Position sécurisée !
MW2_SPLASHES_SECURED_POSITION_A=Position A sécurisée !
MW2_SPLASHES_SECURED_POSITION_B=Position B sécurisée !
MW2_SPLASHES_SECURED_POSITION_C=Position C sécurisée !
MW2_SPLASHES_TIME_ADDED=Bonus de temps !
MW2_SPLASHES_TIME_ADDED_DESC=Site détruit. Bonus de temps de jeu.

# Killstreaks
MW2_KILLSTREAKS_UAV=Drone
MW2_KILLSTREAKS_UAV_DESC=Indique les ennemis sur la mini-carte.
MW2_KILLSTREAKS_AIRSTRIKE=Bombardement
MW2_KILLSTREAKS_AIRSTRIKE_DESC=Demandez le bombardement de la position sélectionnée.
MW2_KILLSTREAKS_HELICOPTER=Hélico. d'attaque
MW2_KILLSTREAKS_HELICOPTER_DESC=Demandez l'appui d'un hélicoptère.
MW2_KILLSTREAKS_AC130=AC130
MW2_KILLSTREAKS_AC130_DESC=Servez comme artilleur à bord d'un AC-130.
MW2_KILLSTREAKS_PREDATOR_MISSILE=Missile Predator
MW2_KILLSTREAKS_PREDATOR_MISSILE_DESC=Missile téléguidé.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN=Mitrailleur hélico.
MW2_KILLSTREAKS_HELICOPTER_MINIGUN_DESC=Mitraillez depuis un hélicoptère.
MW2_KILLSTREAKS_HELICOPTER_MK19=Artilleur d'hélicoptère
MW2_KILLSTREAKS_HELICOPTER_MK19_DESC=Contrôlez à distance un lance-grenades équipant un hélicoptère.
MW2_KILLSTREAKS_DOUBLE_UAV=Drone amélioré
MW2_KILLSTREAKS_DOUBLE_UAV_DESC=Drone avec un meilleur temps de balayage.
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE=Bomb. de précision
MW2_KILLSTREAKS_PRECISION_AIRSTRIKE_DESC=Demandez un bombardement directionnel.
MW2_KILLSTREAKS_AIRDROP=Colis stratégique
MW2_KILLSTREAKS_AIRDROP_DESC=Largue des munitions ou un atout.
MW2_KILLSTREAKS_AIRDROP_SENTRY=Tourelle automatique
MW2_KILLSTREAKS_AIRDROP_SENTRY_DESC=Largue une tourelle auto. à positionner.
MW2_KILLSTREAKS_AIRDROP_PREDATOR=Colis stratégique (Predator)
MW2_KILLSTREAKS_AIRDROP_PREDATOR_DESC=Largue un missile Predator à usage unique.
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE=Bomb. de Harrier
MW2_KILLSTREAKS_HARRIER_AIRSTRIKE_DESC=Effectuez une frappe avec un Harrier.\n
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE=Bombardier furtif
MW2_KILLSTREAKS_STEALTH_AIRSTRIKE_DESC=Effectuez un bombardement indétectable.
MW2_KILLSTREAKS_SUPER_AIRSTRIKE=Bombardement massif
MW2_KILLSTREAKS_SUPER_AIRSTRIKE_DESC=Bombardement un peu plus percutant.
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX=Hélicoptère Blackbox
MW2_KILLSTREAKS_HELICOPTER_BLACKBOX_DESC=Hélicoptère plus résistant.
MW2_KILLSTREAKS_HELICOPTER_FLARES=Hélicoptère défensif
MW2_KILLSTREAKS_HELICOPTER_FLARES_DESC=Hélicoptère disposant de contre-mesures.
MW2_KILLSTREAKS_EMP=Bombe IEM
MW2_KILLSTREAKS_EMP_DESC=Neutralise le matériel électron. ennemi.
MW2_KILLSTREAKS_TANK=Blindé
MW2_KILLSTREAKS_TANK_DESC=Un blindé.
MW2_KILLSTREAKS_COUNTER_UAV=Drone brouilleur
MW2_KILLSTREAKS_COUNTER_UAV_DESC=Neutralise temporairement le radar ennemi.
MW2_KILLSTREAKS_PAVELOW=Pave Low
MW2_KILLSTREAKS_PAVELOW_DESC=Hélicoptère d'assaut doté d'un blindage.
MW2_KILLSTREAKS_NONE=Aucun(e)
MW2_KILLSTREAKS_NONE_DESC=Aucun atout sélectionné.
MW2_KILLSTREAKS_AIRDROP_MEGA=Largage d'urgence
MW2_KILLSTREAKS_AIRDROP_MEGA_DESC=Largue des munitions ou 4 atouts.
MW2_KILLSTREAKS_EARNED_AIRDROP_MEGA=Appuyez sur %s pour obtenir un LARGAGE AÉRIEN D'URGENCE.\n
MW2_KILLSTREAKS_TACTICAL_NUKE=Bombe nucléaire
MW2_KILLSTREAKS_TACTICAL_NUKE_DESC=Terminez la partie avec un feu d'artifice.
MW2_KILLSTREAKS_SENTRY=Tourelle automatique
  
  MW2_MP_EARNED_AIRSTRIKE=Appuyez sur %s pour obtenir un BOMBARDEMENT.
MW2_MP_EARNED_AIRDROP=Appuyez sur %s pour obtenir un COLIS STRATÉGIQUE.
MW2_MP_EARNED_SENTRY_AIRDROP=Appuyez sur %s pour obtenir une TOURELLE AUTOMATIQUE.
MW2_MP_EARNED_PREDATOR_AIRDROP=Appuyez sur %s pour obtenir un PREDATOR.
MW2_MP_EARNED_PRECISION_AIRSTRIKE=Appuyez sur %s pour obtenir un BOMBARDEMENT DE PRÉCISION.
MW2_MP_EARNED_STEALTH_AIRSTRIKE=Appuyez sur %s pour obtenir un BOMBARDIER FURTIF.
MW2_MP_EARNED_HARRIER_AIRSTRIKE=Appuyez sur %s pour obtenir un BOMBARDEMENT DE HARRIER.
MW2_MP_EARNED_SUPER_AIRSTRIKE=Appuyez sur %s pour obtenir un BOMBARDEMENT MASSIF.
MW2_MP_EARNED_UAV=Appuyez sur %s pour obtenir un DRONE.
MW2_MP_EARNED_DOUBLE_UAV=Appuyez sur %s pour obtenir un DRONE AMÉLIORÉ.
MW2_MP_EARNED_COUNTER_UAV=Appuyez sur %s pour obtenir un DRONE DE BROUILLAGE.
MW2_MP_EARNED_HELICOPTER=Appuyez sur %s pour obtenir un HÉLICOPTÈRE D'ATTAQUE.
MW2_MP_EARNED_HELICOPTER_MINIGUN=Appuyez sur %s pour obtenir un MITRAILLEUR D'HÉLICOPTÈRE.
MW2_MP_EARNED_HELICOPTER_MK19=Appuyez sur %s pour obtenir un HÉLICOPTÈRE AVEC UN MK19.
MW2_MP_EARNED_HELICOPTER_BLACKBOX=Appuyez sur %s pour obtenir un HÉLICOPTÈRE BLACKBOX.
MW2_MP_EARNED_HELICOPTER_FLARES=Appuyez sur %s pour obtenir un PAVE LOW.
MW2_MP_EARNED_AC130=Appuyez sur %s pour obtenir un AC-130.
MW2_MP_EARNED_PREDATOR_MISSILE=Appuyez sur %s pour obtenir un MISSILE PREDATOR.
MW2_MP_EARNED_NUKE=Appuyez sur %s pour obtenir une BOMBE NUCLÉAIRE TACTIQUE.
MW2_MP_EARNED_AUTO_SHOTGUN=Appuyez sur %s pour obtenir un FUSIL À POMPE.
MW2_MP_EARNED_AUTO_SENTRY=Appuyez sur %s pour obtenir une TOURELLE AUTOMATIQUE.
MW2_MP_EARNED_AUTO_SENTRY_GL=Appuyez sur %s pour obtenir un LANCE-GRENADES AUTOMATIQUE.
MW2_MP_EARNED_THUMPER=Appuyez sur %s pour obtenir un THUMPER.
MW2_MP_EARNED_LITTLEBIRD_SUPPORT=Appuyez sur %s pour obtenir un LITTLE BIRD.
MW2_MP_EARNED_EMP=Appuyez sur %s pour obtenir une BOMBE IEM.
  
# Other
MW2_MP_CONNECTED=%s connecté
MW2_MP_DISCONNECTED=%s déconnecté
MW2_EXE_LEFTGAME=%s a quitté la partie

MW2_PLATFORM_RELOAD=Recharger
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Peu de munitions
MW2_WEAPON_NO_AMMO=Pas de munition

MW2_MPUI_WINNING_CAPS=EN TÊTE
MW2_MPUI_LOSING_CAPS=DÉFAITE
MW2_MPUI_TIED_CAPS=ÉGALITÉ

# Round Starter
MW2_MP_MATCH_STARTING_IN=Début du match dans :
MW2_MP_MATCH_RESUMING_IN=Reprise du match dans :

MW2_MP_OBJ_DM_HINT=Éliminez les autres joueurs.
MW2_MP_OBJ_WAR_HINT=Éliminez les joueurs ennemis.
MW2_OBJECTIVES_WAR_HINT=Éliminez les joueurs ennemis.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Détruisez la cible A ou la cible B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Protégez les cibles A et B.
MW2_OBJECTIVES_SAB_HINT=Détruisez la cible de l'ennemi.
MW2_OBJECTIVES_DOM_HINT=Capturez les drapeaux et défendez-les.
MW2_OBJECTIVES_DM_HINT=Éliminez les autres joueurs.
MW2_OBJECTIVES_KOTH_HINT=Tenez le QG.
MW2_OBJECTIVES_CTF_HINT=Capturez le drapeau ennemi.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Capturez le drapeau ennemi.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Défendez le drapeau.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Détruisez les cibles A et B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Protégez les cibles A et B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Tuez le VIP et empêchez-le d'atteindre la zone d'extraction.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Défendez le VIP et aidez-le à atteindre la zone d'extraction.
MW2_OBJECTIVES_ARENA_HINT=Éliminez l'ennemi ou capturez le drapeau.
MW2_OBJECTIVES_GTNW_HINT=Prenez la bombe nucléaire.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Attrapez le drapeau ennemi.